// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package counselingdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCounselings = `-- name: CountCounselings :one
SELECT COUNT(*) FROM counselings co
WHERE co.school_id = $1::bigint
  AND ($2::bigint IS NULL OR co.student_id = $2::bigint)
`

type CountCounselingsParams struct {
	SchoolID  int64       `json:"school_id"`
	StudentID pgtype.Int8 `json:"student_id"`
}

func (q *Queries) CountCounselings(ctx context.Context, arg CountCounselingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCounselings, arg.SchoolID, arg.StudentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCounseling = `-- name: CreateCounseling :one

INSERT INTO counselings (school_id, academic_year_id, student_id, counselor_id, career_goals, problem_description, follow_up_plan, evidence, evidence_name, evidence_mime)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, school_id, academic_year_id, student_id, counselor_id, career_goals, problem_description, follow_up_plan, evidence, evidence_name, evidence_mime, created_at, updated_at
`

type CreateCounselingParams struct {
	SchoolID           int64       `json:"school_id"`
	AcademicYearID     int64       `json:"academic_year_id"`
	StudentID          int64       `json:"student_id"`
	CounselorID        int64       `json:"counselor_id"`
	CareerGoals        string      `json:"career_goals"`
	ProblemDescription string      `json:"problem_description"`
	FollowUpPlan       string      `json:"follow_up_plan"`
	Evidence           pgtype.Text `json:"evidence"`
	EvidenceName       pgtype.Text `json:"evidence_name"`
	EvidenceMime       pgtype.Text `json:"evidence_mime"`
}

// Query modul counseling (sqlc). Semua query tenant-scoped WAJIB filter
// school_id. Join read-only ke students/classes/enrollments/users (dimiliki
// modul lain) dipakai untuk menampilkan nama tanpa N+1 call lintas modul —
// pola yang sama dengan internal/discipline/queries.sql. Kelas diresolusi
// dari enrollment PADA academic_year_id baris counseling itu sendiri (bukan
// TA aktif sekarang) — sama keputusan dengan
// discipline.GetStudentViolationByID (potret kelas saat sesi dicatat).
func (q *Queries) CreateCounseling(ctx context.Context, arg CreateCounselingParams) (Counseling, error) {
	row := q.db.QueryRow(ctx, createCounseling,
		arg.SchoolID,
		arg.AcademicYearID,
		arg.StudentID,
		arg.CounselorID,
		arg.CareerGoals,
		arg.ProblemDescription,
		arg.FollowUpPlan,
		arg.Evidence,
		arg.EvidenceName,
		arg.EvidenceMime,
	)
	var i Counseling
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.StudentID,
		&i.CounselorID,
		&i.CareerGoals,
		&i.ProblemDescription,
		&i.FollowUpPlan,
		&i.Evidence,
		&i.EvidenceName,
		&i.EvidenceMime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCounseling = `-- name: DeleteCounseling :execrows
DELETE FROM counselings WHERE id = $1 AND school_id = $2
`

type DeleteCounselingParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) DeleteCounseling(ctx context.Context, arg DeleteCounselingParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCounseling, arg.ID, arg.SchoolID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCounselingByID = `-- name: GetCounselingByID :one
SELECT id, school_id, academic_year_id, student_id, counselor_id, career_goals, problem_description, follow_up_plan, evidence, evidence_name, evidence_mime, created_at, updated_at FROM counselings WHERE id = $1 AND school_id = $2
`

type GetCounselingByIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) GetCounselingByID(ctx context.Context, arg GetCounselingByIDParams) (Counseling, error) {
	row := q.db.QueryRow(ctx, getCounselingByID, arg.ID, arg.SchoolID)
	var i Counseling
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.StudentID,
		&i.CounselorID,
		&i.CareerGoals,
		&i.ProblemDescription,
		&i.FollowUpPlan,
		&i.Evidence,
		&i.EvidenceName,
		&i.EvidenceMime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCounselingRow = `-- name: GetCounselingRow :one
SELECT co.id, co.school_id, co.academic_year_id, co.student_id, co.counselor_id,
       co.career_goals, co.problem_description, co.follow_up_plan,
       co.evidence, co.evidence_name, co.evidence_mime, co.created_at, co.updated_at,
       s.name AS student_name, s.nis AS student_nis, COALESCE(c.name, '') AS class_name,
       u.name AS counselor_name
FROM counselings co
JOIN students s ON s.id = co.student_id
JOIN users u ON u.id = co.counselor_id
LEFT JOIN enrollments e ON e.student_id = s.id
LEFT JOIN classes c ON c.id = e.class_id AND c.academic_year_id = co.academic_year_id
WHERE co.id = $1 AND co.school_id = $2
`

type GetCounselingRowParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetCounselingRowRow struct {
	ID                 int64              `json:"id"`
	SchoolID           int64              `json:"school_id"`
	AcademicYearID     int64              `json:"academic_year_id"`
	StudentID          int64              `json:"student_id"`
	CounselorID        int64              `json:"counselor_id"`
	CareerGoals        string             `json:"career_goals"`
	ProblemDescription string             `json:"problem_description"`
	FollowUpPlan       string             `json:"follow_up_plan"`
	Evidence           pgtype.Text        `json:"evidence"`
	EvidenceName       pgtype.Text        `json:"evidence_name"`
	EvidenceMime       pgtype.Text        `json:"evidence_mime"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	StudentName        string             `json:"student_name"`
	StudentNis         string             `json:"student_nis"`
	ClassName          string             `json:"class_name"`
	CounselorName      string             `json:"counselor_name"`
}

func (q *Queries) GetCounselingRow(ctx context.Context, arg GetCounselingRowParams) (GetCounselingRowRow, error) {
	row := q.db.QueryRow(ctx, getCounselingRow, arg.ID, arg.SchoolID)
	var i GetCounselingRowRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.StudentID,
		&i.CounselorID,
		&i.CareerGoals,
		&i.ProblemDescription,
		&i.FollowUpPlan,
		&i.Evidence,
		&i.EvidenceName,
		&i.EvidenceMime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudentName,
		&i.StudentNis,
		&i.ClassName,
		&i.CounselorName,
	)
	return i, err
}

const getStudentBasic = `-- name: GetStudentBasic :one

SELECT id, name, nis FROM students WHERE id = $1 AND school_id = $2
`

type GetStudentBasicParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetStudentBasicRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Nis  string `json:"nis"`
}

// -- validasi lintas modul (join read-only ke tabel bersama, pola yang sama
// -- dengan internal/discipline/queries.sql "GetStudentBasic") --
func (q *Queries) GetStudentBasic(ctx context.Context, arg GetStudentBasicParams) (GetStudentBasicRow, error) {
	row := q.db.QueryRow(ctx, getStudentBasic, arg.ID, arg.SchoolID)
	var i GetStudentBasicRow
	err := row.Scan(&i.ID, &i.Name, &i.Nis)
	return i, err
}

const listCounselings = `-- name: ListCounselings :many
SELECT co.id, co.school_id, co.academic_year_id, co.student_id, co.counselor_id,
       co.career_goals, co.problem_description, co.follow_up_plan,
       co.evidence, co.evidence_name, co.evidence_mime, co.created_at, co.updated_at,
       s.name AS student_name, s.nis AS student_nis, COALESCE(c.name, '') AS class_name,
       u.name AS counselor_name
FROM counselings co
JOIN students s ON s.id = co.student_id
JOIN users u ON u.id = co.counselor_id
LEFT JOIN enrollments e ON e.student_id = s.id
LEFT JOIN classes c ON c.id = e.class_id AND c.academic_year_id = co.academic_year_id
WHERE co.school_id = $1::bigint
  AND ($2::bigint IS NULL OR co.student_id = $2::bigint)
ORDER BY co.created_at DESC, co.id DESC
LIMIT $4::int OFFSET $3::int
`

type ListCounselingsParams struct {
	SchoolID   int64       `json:"school_id"`
	StudentID  pgtype.Int8 `json:"student_id"`
	OffsetRows int32       `json:"offset_rows"`
	LimitRows  int32       `json:"limit_rows"`
}

type ListCounselingsRow struct {
	ID                 int64              `json:"id"`
	SchoolID           int64              `json:"school_id"`
	AcademicYearID     int64              `json:"academic_year_id"`
	StudentID          int64              `json:"student_id"`
	CounselorID        int64              `json:"counselor_id"`
	CareerGoals        string             `json:"career_goals"`
	ProblemDescription string             `json:"problem_description"`
	FollowUpPlan       string             `json:"follow_up_plan"`
	Evidence           pgtype.Text        `json:"evidence"`
	EvidenceName       pgtype.Text        `json:"evidence_name"`
	EvidenceMime       pgtype.Text        `json:"evidence_mime"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	StudentName        string             `json:"student_name"`
	StudentNis         string             `json:"student_nis"`
	ClassName          string             `json:"class_name"`
	CounselorName      string             `json:"counselor_name"`
}

func (q *Queries) ListCounselings(ctx context.Context, arg ListCounselingsParams) ([]ListCounselingsRow, error) {
	rows, err := q.db.Query(ctx, listCounselings,
		arg.SchoolID,
		arg.StudentID,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCounselingsRow
	for rows.Next() {
		var i ListCounselingsRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.AcademicYearID,
			&i.StudentID,
			&i.CounselorID,
			&i.CareerGoals,
			&i.ProblemDescription,
			&i.FollowUpPlan,
			&i.Evidence,
			&i.EvidenceName,
			&i.EvidenceMime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudentName,
			&i.StudentNis,
			&i.ClassName,
			&i.CounselorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCounseling = `-- name: UpdateCounseling :one
UPDATE counselings SET
    career_goals = $3,
    problem_description = $4,
    follow_up_plan = $5,
    updated_at = now()
WHERE id = $1 AND school_id = $2
RETURNING id, school_id, academic_year_id, student_id, counselor_id, career_goals, problem_description, follow_up_plan, evidence, evidence_name, evidence_mime, created_at, updated_at
`

type UpdateCounselingParams struct {
	ID                 int64  `json:"id"`
	SchoolID           int64  `json:"school_id"`
	CareerGoals        string `json:"career_goals"`
	ProblemDescription string `json:"problem_description"`
	FollowUpPlan       string `json:"follow_up_plan"`
}

func (q *Queries) UpdateCounseling(ctx context.Context, arg UpdateCounselingParams) (Counseling, error) {
	row := q.db.QueryRow(ctx, updateCounseling,
		arg.ID,
		arg.SchoolID,
		arg.CareerGoals,
		arg.ProblemDescription,
		arg.FollowUpPlan,
	)
	var i Counseling
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.StudentID,
		&i.CounselorID,
		&i.CareerGoals,
		&i.ProblemDescription,
		&i.FollowUpPlan,
		&i.Evidence,
		&i.EvidenceName,
		&i.EvidenceMime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCounselingEvidence = `-- name: UpdateCounselingEvidence :exec
UPDATE counselings SET evidence = $3, evidence_name = $4, evidence_mime = $5, updated_at = now()
WHERE id = $1 AND school_id = $2
`

type UpdateCounselingEvidenceParams struct {
	ID           int64       `json:"id"`
	SchoolID     int64       `json:"school_id"`
	Evidence     pgtype.Text `json:"evidence"`
	EvidenceName pgtype.Text `json:"evidence_name"`
	EvidenceMime pgtype.Text `json:"evidence_mime"`
}

func (q *Queries) UpdateCounselingEvidence(ctx context.Context, arg UpdateCounselingEvidenceParams) error {
	_, err := q.db.Exec(ctx, updateCounselingEvidence,
		arg.ID,
		arg.SchoolID,
		arg.Evidence,
		arg.EvidenceName,
		arg.EvidenceMime,
	)
	return err
}
