// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package studentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGuardiansForStudent = `-- name: CountGuardiansForStudent :one
SELECT COUNT(*) FROM guardians WHERE student_id = $1
`

func (q *Queries) CountGuardiansForStudent(ctx context.Context, studentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countGuardiansForStudent, studentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStudents = `-- name: CountStudents :one
SELECT COUNT(*) FROM students s
WHERE s.school_id = $1::bigint
  AND ($2::text IS NULL OR s.name ILIKE '%' || $2::text || '%' OR s.nis ILIKE '%' || $2::text || '%')
  AND ($3::bigint IS NULL OR EXISTS (
        SELECT 1 FROM enrollments e2 WHERE e2.student_id = s.id AND e2.class_id = $3::bigint
      ))
`

type CountStudentsParams struct {
	SchoolID int64       `json:"school_id"`
	Q        pgtype.Text `json:"q"`
	ClassID  pgtype.Int8 `json:"class_id"`
}

func (q *Queries) CountStudents(ctx context.Context, arg CountStudentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudents, arg.SchoolID, arg.Q, arg.ClassID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClass = `-- name: CreateClass :one

INSERT INTO classes (school_id, academic_year_id, name, grade, major, homeroom_teacher_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, school_id, academic_year_id, name, grade, major, homeroom_teacher_id
`

type CreateClassParams struct {
	SchoolID          int64       `json:"school_id"`
	AcademicYearID    int64       `json:"academic_year_id"`
	Name              string      `json:"name"`
	Grade             string      `json:"grade"`
	Major             pgtype.Text `json:"major"`
	HomeroomTeacherID pgtype.Int8 `json:"homeroom_teacher_id"`
}

// -- classes --
func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, createClass,
		arg.SchoolID,
		arg.AcademicYearID,
		arg.Name,
		arg.Grade,
		arg.Major,
		arg.HomeroomTeacherID,
	)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.Name,
		&i.Grade,
		&i.Major,
		&i.HomeroomTeacherID,
	)
	return i, err
}

const createGuardian = `-- name: CreateGuardian :one

INSERT INTO guardians (school_id, user_id, student_id, relation)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, student_id) DO UPDATE SET relation = EXCLUDED.relation
RETURNING id, school_id, user_id, student_id, relation
`

type CreateGuardianParams struct {
	SchoolID  int64  `json:"school_id"`
	UserID    int64  `json:"user_id"`
	StudentID int64  `json:"student_id"`
	Relation  string `json:"relation"`
}

// -- guardians --
func (q *Queries) CreateGuardian(ctx context.Context, arg CreateGuardianParams) (Guardian, error) {
	row := q.db.QueryRow(ctx, createGuardian,
		arg.SchoolID,
		arg.UserID,
		arg.StudentID,
		arg.Relation,
	)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.UserID,
		&i.StudentID,
		&i.Relation,
	)
	return i, err
}

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (school_id, nis, nisn, name, gender, birth_date, status)
VALUES ($1, $2, $3, $4, $5, $6, 'active')
RETURNING id, school_id, nis, nisn, name, gender, birth_date, user_id, status, created_at
`

type CreateStudentParams struct {
	SchoolID  int64       `json:"school_id"`
	Nis       string      `json:"nis"`
	Nisn      pgtype.Text `json:"nisn"`
	Name      string      `json:"name"`
	Gender    pgtype.Text `json:"gender"`
	BirthDate pgtype.Date `json:"birth_date"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.SchoolID,
		arg.Nis,
		arg.Nisn,
		arg.Name,
		arg.Gender,
		arg.BirthDate,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Nis,
		&i.Nisn,
		&i.Name,
		&i.Gender,
		&i.BirthDate,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createSubject = `-- name: CreateSubject :one

INSERT INTO subjects (school_id, code, name) VALUES ($1, $2, $3) RETURNING id, school_id, code, name
`

type CreateSubjectParams struct {
	SchoolID int64  `json:"school_id"`
	Code     string `json:"code"`
	Name     string `json:"name"`
}

// -- subjects --
func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, createSubject, arg.SchoolID, arg.Code, arg.Name)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Code,
		&i.Name,
	)
	return i, err
}

const createTeacher = `-- name: CreateTeacher :one

INSERT INTO teachers (school_id, user_id, nip)
VALUES ($1, $2, $3)
RETURNING id, school_id, user_id, nip
`

type CreateTeacherParams struct {
	SchoolID int64       `json:"school_id"`
	UserID   int64       `json:"user_id"`
	Nip      pgtype.Text `json:"nip"`
}

// -- teachers --
func (q *Queries) CreateTeacher(ctx context.Context, arg CreateTeacherParams) (Teacher, error) {
	row := q.db.QueryRow(ctx, createTeacher, arg.SchoolID, arg.UserID, arg.Nip)
	var i Teacher
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.UserID,
		&i.Nip,
	)
	return i, err
}

const deleteEnrollment = `-- name: DeleteEnrollment :exec
DELETE FROM enrollments WHERE id = $1
`

func (q *Queries) DeleteEnrollment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteEnrollment, id)
	return err
}

const deleteEnrollmentByStudentClass = `-- name: DeleteEnrollmentByStudentClass :exec
DELETE FROM enrollments WHERE student_id = $1 AND class_id = $2
`

type DeleteEnrollmentByStudentClassParams struct {
	StudentID int64 `json:"student_id"`
	ClassID   int64 `json:"class_id"`
}

func (q *Queries) DeleteEnrollmentByStudentClass(ctx context.Context, arg DeleteEnrollmentByStudentClassParams) error {
	_, err := q.db.Exec(ctx, deleteEnrollmentByStudentClass, arg.StudentID, arg.ClassID)
	return err
}

const getClassByID = `-- name: GetClassByID :one
SELECT id, school_id, academic_year_id, name, grade, major, homeroom_teacher_id FROM classes WHERE id = $1 AND school_id = $2
`

type GetClassByIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) GetClassByID(ctx context.Context, arg GetClassByIDParams) (Class, error) {
	row := q.db.QueryRow(ctx, getClassByID, arg.ID, arg.SchoolID)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.Name,
		&i.Grade,
		&i.Major,
		&i.HomeroomTeacherID,
	)
	return i, err
}

const getClassByNameYear = `-- name: GetClassByNameYear :one
SELECT id, school_id, academic_year_id, name, grade, major, homeroom_teacher_id FROM classes WHERE school_id = $1 AND academic_year_id = $2 AND name = $3
`

type GetClassByNameYearParams struct {
	SchoolID       int64  `json:"school_id"`
	AcademicYearID int64  `json:"academic_year_id"`
	Name           string `json:"name"`
}

func (q *Queries) GetClassByNameYear(ctx context.Context, arg GetClassByNameYearParams) (Class, error) {
	row := q.db.QueryRow(ctx, getClassByNameYear, arg.SchoolID, arg.AcademicYearID, arg.Name)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.Name,
		&i.Grade,
		&i.Major,
		&i.HomeroomTeacherID,
	)
	return i, err
}

const getEnrollmentInYear = `-- name: GetEnrollmentInYear :one
SELECT e.id, e.school_id, e.student_id, e.class_id, e.created_at FROM enrollments e
JOIN classes c ON c.id = e.class_id
WHERE e.student_id = $1 AND c.academic_year_id = $2
`

type GetEnrollmentInYearParams struct {
	StudentID      int64 `json:"student_id"`
	AcademicYearID int64 `json:"academic_year_id"`
}

func (q *Queries) GetEnrollmentInYear(ctx context.Context, arg GetEnrollmentInYearParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollmentInYear, arg.StudentID, arg.AcademicYearID)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.StudentID,
		&i.ClassID,
		&i.CreatedAt,
	)
	return i, err
}

const getGuardianByUserStudent = `-- name: GetGuardianByUserStudent :one
SELECT id, school_id, user_id, student_id, relation FROM guardians WHERE user_id = $1 AND student_id = $2
`

type GetGuardianByUserStudentParams struct {
	UserID    int64 `json:"user_id"`
	StudentID int64 `json:"student_id"`
}

func (q *Queries) GetGuardianByUserStudent(ctx context.Context, arg GetGuardianByUserStudentParams) (Guardian, error) {
	row := q.db.QueryRow(ctx, getGuardianByUserStudent, arg.UserID, arg.StudentID)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.UserID,
		&i.StudentID,
		&i.Relation,
	)
	return i, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT s.id, s.school_id, s.nis, s.nisn, s.name, s.gender, s.birth_date, s.user_id, s.status, s.created_at,
       c.id AS class_id, c.name AS class_name
FROM students s
LEFT JOIN enrollments e ON e.student_id = s.id
LEFT JOIN classes c ON c.id = e.class_id AND c.academic_year_id = $1::bigint
WHERE s.id = $2::bigint AND s.school_id = $3::bigint
`

type GetStudentByIDParams struct {
	AcademicYearID int64 `json:"academic_year_id"`
	ID             int64 `json:"id"`
	SchoolID       int64 `json:"school_id"`
}

type GetStudentByIDRow struct {
	ID        int64              `json:"id"`
	SchoolID  int64              `json:"school_id"`
	Nis       string             `json:"nis"`
	Nisn      pgtype.Text        `json:"nisn"`
	Name      string             `json:"name"`
	Gender    pgtype.Text        `json:"gender"`
	BirthDate pgtype.Date        `json:"birth_date"`
	UserID    pgtype.Int8        `json:"user_id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ClassID   pgtype.Int8        `json:"class_id"`
	ClassName pgtype.Text        `json:"class_name"`
}

func (q *Queries) GetStudentByID(ctx context.Context, arg GetStudentByIDParams) (GetStudentByIDRow, error) {
	row := q.db.QueryRow(ctx, getStudentByID, arg.AcademicYearID, arg.ID, arg.SchoolID)
	var i GetStudentByIDRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Nis,
		&i.Nisn,
		&i.Name,
		&i.Gender,
		&i.BirthDate,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.ClassID,
		&i.ClassName,
	)
	return i, err
}

const getStudentByNIS = `-- name: GetStudentByNIS :one
SELECT id, school_id, nis, nisn, name, gender, birth_date, user_id, status, created_at FROM students WHERE school_id = $1 AND nis = $2
`

type GetStudentByNISParams struct {
	SchoolID int64  `json:"school_id"`
	Nis      string `json:"nis"`
}

func (q *Queries) GetStudentByNIS(ctx context.Context, arg GetStudentByNISParams) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByNIS, arg.SchoolID, arg.Nis)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Nis,
		&i.Nisn,
		&i.Name,
		&i.Gender,
		&i.BirthDate,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getSubjectByCode = `-- name: GetSubjectByCode :one
SELECT id, school_id, code, name FROM subjects WHERE school_id = $1 AND code = $2
`

type GetSubjectByCodeParams struct {
	SchoolID int64  `json:"school_id"`
	Code     string `json:"code"`
}

func (q *Queries) GetSubjectByCode(ctx context.Context, arg GetSubjectByCodeParams) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubjectByCode, arg.SchoolID, arg.Code)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Code,
		&i.Name,
	)
	return i, err
}

const getTeacherByEmail = `-- name: GetTeacherByEmail :one
SELECT t.id, t.school_id, t.user_id, t.nip, u.name AS user_name, u.email AS user_email
FROM teachers t JOIN users u ON u.id = t.user_id
WHERE t.school_id = $1 AND u.email = $2
`

type GetTeacherByEmailParams struct {
	SchoolID int64       `json:"school_id"`
	Email    pgtype.Text `json:"email"`
}

type GetTeacherByEmailRow struct {
	ID        int64       `json:"id"`
	SchoolID  int64       `json:"school_id"`
	UserID    int64       `json:"user_id"`
	Nip       pgtype.Text `json:"nip"`
	UserName  string      `json:"user_name"`
	UserEmail pgtype.Text `json:"user_email"`
}

func (q *Queries) GetTeacherByEmail(ctx context.Context, arg GetTeacherByEmailParams) (GetTeacherByEmailRow, error) {
	row := q.db.QueryRow(ctx, getTeacherByEmail, arg.SchoolID, arg.Email)
	var i GetTeacherByEmailRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.UserID,
		&i.Nip,
		&i.UserName,
		&i.UserEmail,
	)
	return i, err
}

const getTeacherByID = `-- name: GetTeacherByID :one
SELECT t.id, t.school_id, t.user_id, t.nip, u.name AS user_name, u.email AS user_email
FROM teachers t JOIN users u ON u.id = t.user_id
WHERE t.id = $1 AND t.school_id = $2
`

type GetTeacherByIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetTeacherByIDRow struct {
	ID        int64       `json:"id"`
	SchoolID  int64       `json:"school_id"`
	UserID    int64       `json:"user_id"`
	Nip       pgtype.Text `json:"nip"`
	UserName  string      `json:"user_name"`
	UserEmail pgtype.Text `json:"user_email"`
}

func (q *Queries) GetTeacherByID(ctx context.Context, arg GetTeacherByIDParams) (GetTeacherByIDRow, error) {
	row := q.db.QueryRow(ctx, getTeacherByID, arg.ID, arg.SchoolID)
	var i GetTeacherByIDRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.UserID,
		&i.Nip,
		&i.UserName,
		&i.UserEmail,
	)
	return i, err
}

const getTeacherByNIP = `-- name: GetTeacherByNIP :one
SELECT t.id, t.school_id, t.user_id, t.nip, u.name AS user_name, u.email AS user_email
FROM teachers t JOIN users u ON u.id = t.user_id
WHERE t.school_id = $1 AND t.nip = $2
`

type GetTeacherByNIPParams struct {
	SchoolID int64       `json:"school_id"`
	Nip      pgtype.Text `json:"nip"`
}

type GetTeacherByNIPRow struct {
	ID        int64       `json:"id"`
	SchoolID  int64       `json:"school_id"`
	UserID    int64       `json:"user_id"`
	Nip       pgtype.Text `json:"nip"`
	UserName  string      `json:"user_name"`
	UserEmail pgtype.Text `json:"user_email"`
}

func (q *Queries) GetTeacherByNIP(ctx context.Context, arg GetTeacherByNIPParams) (GetTeacherByNIPRow, error) {
	row := q.db.QueryRow(ctx, getTeacherByNIP, arg.SchoolID, arg.Nip)
	var i GetTeacherByNIPRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.UserID,
		&i.Nip,
		&i.UserName,
		&i.UserEmail,
	)
	return i, err
}

const getTeacherByUserID = `-- name: GetTeacherByUserID :one
SELECT t.id, t.school_id, t.user_id, t.nip, u.name AS user_name, u.email AS user_email
FROM teachers t JOIN users u ON u.id = t.user_id
WHERE t.school_id = $1 AND t.user_id = $2
`

type GetTeacherByUserIDParams struct {
	SchoolID int64 `json:"school_id"`
	UserID   int64 `json:"user_id"`
}

type GetTeacherByUserIDRow struct {
	ID        int64       `json:"id"`
	SchoolID  int64       `json:"school_id"`
	UserID    int64       `json:"user_id"`
	Nip       pgtype.Text `json:"nip"`
	UserName  string      `json:"user_name"`
	UserEmail pgtype.Text `json:"user_email"`
}

func (q *Queries) GetTeacherByUserID(ctx context.Context, arg GetTeacherByUserIDParams) (GetTeacherByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getTeacherByUserID, arg.SchoolID, arg.UserID)
	var i GetTeacherByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.UserID,
		&i.Nip,
		&i.UserName,
		&i.UserEmail,
	)
	return i, err
}

const listChildrenForGuardian = `-- name: ListChildrenForGuardian :many
SELECT s.id, s.name, c.name AS class_name
FROM guardians g
JOIN students s ON s.id = g.student_id
LEFT JOIN enrollments e ON e.student_id = s.id
LEFT JOIN classes c ON c.id = e.class_id AND c.academic_year_id = $1::bigint
WHERE g.user_id = $2::bigint AND s.school_id = $3::bigint
ORDER BY s.name
`

type ListChildrenForGuardianParams struct {
	AcademicYearID int64 `json:"academic_year_id"`
	UserID         int64 `json:"user_id"`
	SchoolID       int64 `json:"school_id"`
}

type ListChildrenForGuardianRow struct {
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
	ClassName pgtype.Text `json:"class_name"`
}

func (q *Queries) ListChildrenForGuardian(ctx context.Context, arg ListChildrenForGuardianParams) ([]ListChildrenForGuardianRow, error) {
	rows, err := q.db.Query(ctx, listChildrenForGuardian, arg.AcademicYearID, arg.UserID, arg.SchoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildrenForGuardianRow
	for rows.Next() {
		var i ListChildrenForGuardianRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ClassName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClasses = `-- name: ListClasses :many
SELECT c.id, c.school_id, c.academic_year_id, c.name, c.grade, c.major, c.homeroom_teacher_id,
       t.id AS teacher_row_id, u.id AS teacher_user_id, u.name AS teacher_name,
       COUNT(e.id) AS student_count
FROM classes c
LEFT JOIN teachers t ON t.id = c.homeroom_teacher_id
LEFT JOIN users u ON u.id = t.user_id
LEFT JOIN enrollments e ON e.class_id = c.id
WHERE c.school_id = $1 AND c.academic_year_id = $2
GROUP BY c.id, t.id, u.id, u.name
ORDER BY c.name
`

type ListClassesParams struct {
	SchoolID       int64 `json:"school_id"`
	AcademicYearID int64 `json:"academic_year_id"`
}

type ListClassesRow struct {
	ID                int64       `json:"id"`
	SchoolID          int64       `json:"school_id"`
	AcademicYearID    int64       `json:"academic_year_id"`
	Name              string      `json:"name"`
	Grade             string      `json:"grade"`
	Major             pgtype.Text `json:"major"`
	HomeroomTeacherID pgtype.Int8 `json:"homeroom_teacher_id"`
	TeacherRowID      pgtype.Int8 `json:"teacher_row_id"`
	TeacherUserID     pgtype.Int8 `json:"teacher_user_id"`
	TeacherName       pgtype.Text `json:"teacher_name"`
	StudentCount      int64       `json:"student_count"`
}

func (q *Queries) ListClasses(ctx context.Context, arg ListClassesParams) ([]ListClassesRow, error) {
	rows, err := q.db.Query(ctx, listClasses, arg.SchoolID, arg.AcademicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassesRow
	for rows.Next() {
		var i ListClassesRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.AcademicYearID,
			&i.Name,
			&i.Grade,
			&i.Major,
			&i.HomeroomTeacherID,
			&i.TeacherRowID,
			&i.TeacherUserID,
			&i.TeacherName,
			&i.StudentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudents = `-- name: ListStudents :many

SELECT s.id, s.nis, s.nisn, s.name, s.gender, s.birth_date, s.status,
       c.id AS class_id, c.name AS class_name
FROM students s
LEFT JOIN enrollments e ON e.student_id = s.id
LEFT JOIN classes c ON c.id = e.class_id AND c.academic_year_id = $1::bigint
WHERE s.school_id = $2::bigint
  AND ($3::text IS NULL OR s.name ILIKE '%' || $3::text || '%' OR s.nis ILIKE '%' || $3::text || '%')
  AND ($4::bigint IS NULL OR EXISTS (
        SELECT 1 FROM enrollments e2 WHERE e2.student_id = s.id AND e2.class_id = $4::bigint
      ))
ORDER BY s.name
LIMIT $6::bigint OFFSET $5::bigint
`

type ListStudentsParams struct {
	AcademicYearID int64       `json:"academic_year_id"`
	SchoolID       int64       `json:"school_id"`
	Q              pgtype.Text `json:"q"`
	ClassID        pgtype.Int8 `json:"class_id"`
	Offset         int64       `json:"offset_"`
	Limit          int64       `json:"limit_"`
}

type ListStudentsRow struct {
	ID        int64       `json:"id"`
	Nis       string      `json:"nis"`
	Nisn      pgtype.Text `json:"nisn"`
	Name      string      `json:"name"`
	Gender    pgtype.Text `json:"gender"`
	BirthDate pgtype.Date `json:"birth_date"`
	Status    string      `json:"status"`
	ClassID   pgtype.Int8 `json:"class_id"`
	ClassName pgtype.Text `json:"class_name"`
}

// Query modul student (sqlc). Semua query tenant-scoped WAJIB filter school_id.
// Catatan: join read-only ke users (dimiliki modul identity) dipakai untuk
// menampilkan nama/email guru/wali kelas tanpa N+1 call lintas modul. Semua
// TULIS ke users/memberships/sessions/invitations tetap lewat IdentityGateway
// (consumer-side interface), tidak pernah lewat query di sini.
func (q *Queries) ListStudents(ctx context.Context, arg ListStudentsParams) ([]ListStudentsRow, error) {
	rows, err := q.db.Query(ctx, listStudents,
		arg.AcademicYearID,
		arg.SchoolID,
		arg.Q,
		arg.ClassID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentsRow
	for rows.Next() {
		var i ListStudentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Nis,
			&i.Nisn,
			&i.Name,
			&i.Gender,
			&i.BirthDate,
			&i.Status,
			&i.ClassID,
			&i.ClassName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsByIDs = `-- name: ListStudentsByIDs :many
SELECT id, school_id, nis, nisn, name, gender, birth_date, user_id, status, created_at FROM students WHERE school_id = $1 AND id = ANY($2::bigint[])
`

type ListStudentsByIDsParams struct {
	SchoolID int64   `json:"school_id"`
	Ids      []int64 `json:"ids"`
}

func (q *Queries) ListStudentsByIDs(ctx context.Context, arg ListStudentsByIDsParams) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudentsByIDs, arg.SchoolID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Nis,
			&i.Nisn,
			&i.Name,
			&i.Gender,
			&i.BirthDate,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, school_id, code, name FROM subjects WHERE school_id = $1 ORDER BY code
`

func (q *Queries) ListSubjects(ctx context.Context, schoolID int64) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjects, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Code,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachers = `-- name: ListTeachers :many
SELECT t.id, t.school_id, t.user_id, t.nip, u.name AS user_name, u.email AS user_email
FROM teachers t JOIN users u ON u.id = t.user_id
WHERE t.school_id = $1
ORDER BY u.name
`

type ListTeachersRow struct {
	ID        int64       `json:"id"`
	SchoolID  int64       `json:"school_id"`
	UserID    int64       `json:"user_id"`
	Nip       pgtype.Text `json:"nip"`
	UserName  string      `json:"user_name"`
	UserEmail pgtype.Text `json:"user_email"`
}

func (q *Queries) ListTeachers(ctx context.Context, schoolID int64) ([]ListTeachersRow, error) {
	rows, err := q.db.Query(ctx, listTeachers, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeachersRow
	for rows.Next() {
		var i ListTeachersRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.UserID,
			&i.Nip,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStudentUserID = `-- name: SetStudentUserID :exec
UPDATE students SET user_id = $2 WHERE id = $1
`

type SetStudentUserIDParams struct {
	ID     int64       `json:"id"`
	UserID pgtype.Int8 `json:"user_id"`
}

func (q *Queries) SetStudentUserID(ctx context.Context, arg SetStudentUserIDParams) error {
	_, err := q.db.Exec(ctx, setStudentUserID, arg.ID, arg.UserID)
	return err
}

const updateClass = `-- name: UpdateClass :one
UPDATE classes SET
    name                = COALESCE($1, name),
    grade               = COALESCE($2, grade),
    major               = COALESCE($3, major),
    homeroom_teacher_id = COALESCE($4, homeroom_teacher_id)
WHERE id = $5 AND school_id = $6
RETURNING id, school_id, academic_year_id, name, grade, major, homeroom_teacher_id
`

type UpdateClassParams struct {
	Name              pgtype.Text `json:"name"`
	Grade             pgtype.Text `json:"grade"`
	Major             pgtype.Text `json:"major"`
	HomeroomTeacherID pgtype.Int8 `json:"homeroom_teacher_id"`
	ID                int64       `json:"id"`
	SchoolID          int64       `json:"school_id"`
}

func (q *Queries) UpdateClass(ctx context.Context, arg UpdateClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, updateClass,
		arg.Name,
		arg.Grade,
		arg.Major,
		arg.HomeroomTeacherID,
		arg.ID,
		arg.SchoolID,
	)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.Name,
		&i.Grade,
		&i.Major,
		&i.HomeroomTeacherID,
	)
	return i, err
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE students SET
    nis        = COALESCE($1, nis),
    nisn       = COALESCE($2, nisn),
    name       = COALESCE($3, name),
    gender     = COALESCE($4, gender),
    birth_date = COALESCE($5, birth_date),
    status     = COALESCE($6, status)
WHERE id = $7 AND school_id = $8
RETURNING id, school_id, nis, nisn, name, gender, birth_date, user_id, status, created_at
`

type UpdateStudentParams struct {
	Nis       pgtype.Text `json:"nis"`
	Nisn      pgtype.Text `json:"nisn"`
	Name      pgtype.Text `json:"name"`
	Gender    pgtype.Text `json:"gender"`
	BirthDate pgtype.Date `json:"birth_date"`
	Status    pgtype.Text `json:"status"`
	ID        int64       `json:"id"`
	SchoolID  int64       `json:"school_id"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudent,
		arg.Nis,
		arg.Nisn,
		arg.Name,
		arg.Gender,
		arg.BirthDate,
		arg.Status,
		arg.ID,
		arg.SchoolID,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Nis,
		&i.Nisn,
		&i.Name,
		&i.Gender,
		&i.BirthDate,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateSubject = `-- name: UpdateSubject :one
UPDATE subjects SET
    code = COALESCE($1, code),
    name = COALESCE($2, name)
WHERE id = $3 AND school_id = $4
RETURNING id, school_id, code, name
`

type UpdateSubjectParams struct {
	Code     pgtype.Text `json:"code"`
	Name     pgtype.Text `json:"name"`
	ID       int64       `json:"id"`
	SchoolID int64       `json:"school_id"`
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, updateSubject,
		arg.Code,
		arg.Name,
		arg.ID,
		arg.SchoolID,
	)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Code,
		&i.Name,
	)
	return i, err
}

const updateTeacher = `-- name: UpdateTeacher :one
UPDATE teachers SET nip = COALESCE($1, nip)
WHERE id = $2 AND school_id = $3
RETURNING id, school_id, user_id, nip
`

type UpdateTeacherParams struct {
	Nip      pgtype.Text `json:"nip"`
	ID       int64       `json:"id"`
	SchoolID int64       `json:"school_id"`
}

func (q *Queries) UpdateTeacher(ctx context.Context, arg UpdateTeacherParams) (Teacher, error) {
	row := q.db.QueryRow(ctx, updateTeacher, arg.Nip, arg.ID, arg.SchoolID)
	var i Teacher
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.UserID,
		&i.Nip,
	)
	return i, err
}

const upsertEnrollment = `-- name: UpsertEnrollment :one

INSERT INTO enrollments (school_id, student_id, class_id)
VALUES ($1, $2, $3)
ON CONFLICT (student_id, class_id) DO UPDATE SET class_id = EXCLUDED.class_id
RETURNING id, school_id, student_id, class_id, created_at
`

type UpsertEnrollmentParams struct {
	SchoolID  int64 `json:"school_id"`
	StudentID int64 `json:"student_id"`
	ClassID   int64 `json:"class_id"`
}

// -- enrollments --
func (q *Queries) UpsertEnrollment(ctx context.Context, arg UpsertEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, upsertEnrollment, arg.SchoolID, arg.StudentID, arg.ClassID)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.StudentID,
		&i.ClassID,
		&i.CreatedAt,
	)
	return i, err
}
