// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package substitutiondb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeSubstituteForSlotDate = `-- name: ActiveSubstituteForSlotDate :one
SELECT usub.id AS user_id, usub.name AS name
FROM teacher_substitution_requests tsr
JOIN users usub ON usub.id = tsr.substitute_user_id
WHERE tsr.schedule_slot_id = $1 AND tsr.school_id = $2 AND tsr.date = $3 AND tsr.status = 'accepted'
`

type ActiveSubstituteForSlotDateParams struct {
	ScheduleSlotID int64       `json:"schedule_slot_id"`
	SchoolID       int64       `json:"school_id"`
	Date           pgtype.Date `json:"date"`
}

type ActiveSubstituteForSlotDateRow struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

// Dipakai interface publik Service.SubstituteFor (docs tugas Gelombang D:
// dikonsumsi modul teaching lewat consumer-side interface SubstitutionLookup)
// — HANYA status accepted yang berlaku sbg pengganti sah.
func (q *Queries) ActiveSubstituteForSlotDate(ctx context.Context, arg ActiveSubstituteForSlotDateParams) (ActiveSubstituteForSlotDateRow, error) {
	row := q.db.QueryRow(ctx, activeSubstituteForSlotDate, arg.ScheduleSlotID, arg.SchoolID, arg.Date)
	var i ActiveSubstituteForSlotDateRow
	err := row.Scan(&i.UserID, &i.Name)
	return i, err
}

const createSubstitutionRequest = `-- name: CreateSubstitutionRequest :one

INSERT INTO teacher_substitution_requests (school_id, schedule_slot_id, date, requested_by, substitute_user_id, reason)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, school_id, schedule_slot_id, date, requested_by, substitute_user_id, reason, status, decided_at, created_at
`

type CreateSubstitutionRequestParams struct {
	SchoolID         int64       `json:"school_id"`
	ScheduleSlotID   int64       `json:"schedule_slot_id"`
	Date             pgtype.Date `json:"date"`
	RequestedBy      int64       `json:"requested_by"`
	SubstituteUserID int64       `json:"substitute_user_id"`
	Reason           string      `json:"reason"`
}

// Query modul substitution (sqlc). Semua query tenant-scoped WAJIB filter
// school_id. Join read-only ke schedule_slots/classes/subjects/users
// (dimiliki modul lain) dipakai untuk menampilkan nama tanpa N+1 call lintas
// modul — pola yang sama dengan internal/discipline/queries.sql.
func (q *Queries) CreateSubstitutionRequest(ctx context.Context, arg CreateSubstitutionRequestParams) (TeacherSubstitutionRequest, error) {
	row := q.db.QueryRow(ctx, createSubstitutionRequest,
		arg.SchoolID,
		arg.ScheduleSlotID,
		arg.Date,
		arg.RequestedBy,
		arg.SubstituteUserID,
		arg.Reason,
	)
	var i TeacherSubstitutionRequest
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.ScheduleSlotID,
		&i.Date,
		&i.RequestedBy,
		&i.SubstituteUserID,
		&i.Reason,
		&i.Status,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSlotBasic = `-- name: GetSlotBasic :one

SELECT id, school_id, teacher_id, day_of_week FROM schedule_slots WHERE id = $1 AND school_id = $2
`

type GetSlotBasicParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetSlotBasicRow struct {
	ID        int64 `json:"id"`
	SchoolID  int64 `json:"school_id"`
	TeacherID int64 `json:"teacher_id"`
	DayOfWeek int32 `json:"day_of_week"`
}

// -- validasi lintas modul (join read-only ke tabel bersama) --
func (q *Queries) GetSlotBasic(ctx context.Context, arg GetSlotBasicParams) (GetSlotBasicRow, error) {
	row := q.db.QueryRow(ctx, getSlotBasic, arg.ID, arg.SchoolID)
	var i GetSlotBasicRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.TeacherID,
		&i.DayOfWeek,
	)
	return i, err
}

const getSubstitutionRequestByID = `-- name: GetSubstitutionRequestByID :one
SELECT id, school_id, schedule_slot_id, date, requested_by, substitute_user_id, reason, status, decided_at, created_at FROM teacher_substitution_requests WHERE id = $1 AND school_id = $2
`

type GetSubstitutionRequestByIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) GetSubstitutionRequestByID(ctx context.Context, arg GetSubstitutionRequestByIDParams) (TeacherSubstitutionRequest, error) {
	row := q.db.QueryRow(ctx, getSubstitutionRequestByID, arg.ID, arg.SchoolID)
	var i TeacherSubstitutionRequest
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.ScheduleSlotID,
		&i.Date,
		&i.RequestedBy,
		&i.SubstituteUserID,
		&i.Reason,
		&i.Status,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSubstitutionRow = `-- name: GetSubstitutionRow :one
SELECT tsr.id, tsr.school_id, tsr.schedule_slot_id, tsr.date, tsr.requested_by, tsr.substitute_user_id,
       tsr.reason, tsr.status, tsr.decided_at, tsr.created_at,
       ss.class_id, c.name AS class_name, ss.subject_id, sub.name AS subject_name,
       ss.day_of_week, ss.period_start, ss.period_end,
       ureq.name AS requested_by_name, usub.name AS substitute_name
FROM teacher_substitution_requests tsr
JOIN schedule_slots ss ON ss.id = tsr.schedule_slot_id
JOIN classes c ON c.id = ss.class_id
JOIN subjects sub ON sub.id = ss.subject_id
JOIN users ureq ON ureq.id = tsr.requested_by
JOIN users usub ON usub.id = tsr.substitute_user_id
WHERE tsr.id = $1 AND tsr.school_id = $2
`

type GetSubstitutionRowParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetSubstitutionRowRow struct {
	ID               int64              `json:"id"`
	SchoolID         int64              `json:"school_id"`
	ScheduleSlotID   int64              `json:"schedule_slot_id"`
	Date             pgtype.Date        `json:"date"`
	RequestedBy      int64              `json:"requested_by"`
	SubstituteUserID int64              `json:"substitute_user_id"`
	Reason           string             `json:"reason"`
	Status           string             `json:"status"`
	DecidedAt        pgtype.Timestamptz `json:"decided_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ClassID          int64              `json:"class_id"`
	ClassName        string             `json:"class_name"`
	SubjectID        int64              `json:"subject_id"`
	SubjectName      string             `json:"subject_name"`
	DayOfWeek        int32              `json:"day_of_week"`
	PeriodStart      int32              `json:"period_start"`
	PeriodEnd        int32              `json:"period_end"`
	RequestedByName  string             `json:"requested_by_name"`
	SubstituteName   string             `json:"substitute_name"`
}

func (q *Queries) GetSubstitutionRow(ctx context.Context, arg GetSubstitutionRowParams) (GetSubstitutionRowRow, error) {
	row := q.db.QueryRow(ctx, getSubstitutionRow, arg.ID, arg.SchoolID)
	var i GetSubstitutionRowRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.ScheduleSlotID,
		&i.Date,
		&i.RequestedBy,
		&i.SubstituteUserID,
		&i.Reason,
		&i.Status,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.ClassID,
		&i.ClassName,
		&i.SubjectID,
		&i.SubjectName,
		&i.DayOfWeek,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.RequestedByName,
		&i.SubstituteName,
	)
	return i, err
}

const getTeacherUserID = `-- name: GetTeacherUserID :one
SELECT user_id FROM teachers WHERE id = $1 AND school_id = $2
`

type GetTeacherUserIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

// Dipakai validasi "guru pemilik slot" (bandingkan user_id pemilik profil
// teacher_id slot dgn actor yang mengajukan) — join langsung ke teachers
// (dimiliki modul student), pola sama internal/discipline "GetHomeroomTeacherUserID".
func (q *Queries) GetTeacherUserID(ctx context.Context, arg GetTeacherUserIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTeacherUserID, arg.ID, arg.SchoolID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const isActiveGuru = `-- name: IsActiveGuru :one
SELECT EXISTS (SELECT 1 FROM memberships WHERE user_id = $1 AND school_id = $2 AND role = 'guru' AND status = 'active')
`

type IsActiveGuruParams struct {
	UserID   int64 `json:"user_id"`
	SchoolID int64 `json:"school_id"`
}

// Dipakai validasi substitute_user_id: harus anggota AKTIF sekolah ini
// dengan role guru — join langsung ke memberships (dimiliki modul identity).
func (q *Queries) IsActiveGuru(ctx context.Context, arg IsActiveGuruParams) (bool, error) {
	row := q.db.QueryRow(ctx, isActiveGuru, arg.UserID, arg.SchoolID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listSubstitutionRequests = `-- name: ListSubstitutionRequests :many
SELECT tsr.id, tsr.school_id, tsr.schedule_slot_id, tsr.date, tsr.requested_by, tsr.substitute_user_id,
       tsr.reason, tsr.status, tsr.decided_at, tsr.created_at,
       ss.class_id, c.name AS class_name, ss.subject_id, sub.name AS subject_name,
       ss.day_of_week, ss.period_start, ss.period_end,
       ureq.name AS requested_by_name, usub.name AS substitute_name
FROM teacher_substitution_requests tsr
JOIN schedule_slots ss ON ss.id = tsr.schedule_slot_id
JOIN classes c ON c.id = ss.class_id
JOIN subjects sub ON sub.id = ss.subject_id
JOIN users ureq ON ureq.id = tsr.requested_by
JOIN users usub ON usub.id = tsr.substitute_user_id
WHERE tsr.school_id = $1::bigint
  AND ($2::bigint IS NULL OR tsr.requested_by = $2::bigint)
  AND ($3::bigint IS NULL OR tsr.substitute_user_id = $3::bigint)
  AND ($4::date IS NULL OR tsr.date = $4::date)
ORDER BY tsr.date DESC, tsr.id DESC
`

type ListSubstitutionRequestsParams struct {
	SchoolID         int64       `json:"school_id"`
	RequestedBy      pgtype.Int8 `json:"requested_by"`
	SubstituteUserID pgtype.Int8 `json:"substitute_user_id"`
	Date             pgtype.Date `json:"date"`
}

type ListSubstitutionRequestsRow struct {
	ID               int64              `json:"id"`
	SchoolID         int64              `json:"school_id"`
	ScheduleSlotID   int64              `json:"schedule_slot_id"`
	Date             pgtype.Date        `json:"date"`
	RequestedBy      int64              `json:"requested_by"`
	SubstituteUserID int64              `json:"substitute_user_id"`
	Reason           string             `json:"reason"`
	Status           string             `json:"status"`
	DecidedAt        pgtype.Timestamptz `json:"decided_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ClassID          int64              `json:"class_id"`
	ClassName        string             `json:"class_name"`
	SubjectID        int64              `json:"subject_id"`
	SubjectName      string             `json:"subject_name"`
	DayOfWeek        int32              `json:"day_of_week"`
	PeriodStart      int32              `json:"period_start"`
	PeriodEnd        int32              `json:"period_end"`
	RequestedByName  string             `json:"requested_by_name"`
	SubstituteName   string             `json:"substitute_name"`
}

func (q *Queries) ListSubstitutionRequests(ctx context.Context, arg ListSubstitutionRequestsParams) ([]ListSubstitutionRequestsRow, error) {
	rows, err := q.db.Query(ctx, listSubstitutionRequests,
		arg.SchoolID,
		arg.RequestedBy,
		arg.SubstituteUserID,
		arg.Date,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubstitutionRequestsRow
	for rows.Next() {
		var i ListSubstitutionRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.ScheduleSlotID,
			&i.Date,
			&i.RequestedBy,
			&i.SubstituteUserID,
			&i.Reason,
			&i.Status,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.ClassID,
			&i.ClassName,
			&i.SubjectID,
			&i.SubjectName,
			&i.DayOfWeek,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.RequestedByName,
			&i.SubstituteName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slotIDsAcceptedSubstituteForDate = `-- name: SlotIDsAcceptedSubstituteForDate :many
SELECT schedule_slot_id FROM teacher_substitution_requests
WHERE school_id = $1 AND substitute_user_id = $2 AND date = $3 AND status = 'accepted'
`

type SlotIDsAcceptedSubstituteForDateParams struct {
	SchoolID         int64       `json:"school_id"`
	SubstituteUserID int64       `json:"substitute_user_id"`
	Date             pgtype.Date `json:"date"`
}

// Dipakai interface publik Service.IsSubstituteToday.
func (q *Queries) SlotIDsAcceptedSubstituteForDate(ctx context.Context, arg SlotIDsAcceptedSubstituteForDateParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, slotIDsAcceptedSubstituteForDate, arg.SchoolID, arg.SubstituteUserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var schedule_slot_id int64
		if err := rows.Scan(&schedule_slot_id); err != nil {
			return nil, err
		}
		items = append(items, schedule_slot_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionSubstitutionStatus = `-- name: TransitionSubstitutionStatus :one
UPDATE teacher_substitution_requests
SET status = $1::text, decided_at = $2::timestamptz
WHERE id = $3 AND school_id = $4 AND status = $5::text
RETURNING id, school_id, schedule_slot_id, date, requested_by, substitute_user_id, reason, status, decided_at, created_at
`

type TransitionSubstitutionStatusParams struct {
	ToStatus   string             `json:"to_status"`
	DecidedAt  pgtype.Timestamptz `json:"decided_at"`
	ID         int64              `json:"id"`
	SchoolID   int64              `json:"school_id"`
	FromStatus string             `json:"from_status"`
}

// Race guard transaksional (pola sama internal/exitpermit: "UPDATE ... WHERE
// status = $tahap_lama") — mengembalikan pgx.ErrNoRows bila status saat ini
// BUKAN from_status (sudah diputuskan pihak lain / dibatalkan duluan).
func (q *Queries) TransitionSubstitutionStatus(ctx context.Context, arg TransitionSubstitutionStatusParams) (TeacherSubstitutionRequest, error) {
	row := q.db.QueryRow(ctx, transitionSubstitutionStatus,
		arg.ToStatus,
		arg.DecidedAt,
		arg.ID,
		arg.SchoolID,
		arg.FromStatus,
	)
	var i TeacherSubstitutionRequest
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.ScheduleSlotID,
		&i.Date,
		&i.RequestedBy,
		&i.SubstituteUserID,
		&i.Reason,
		&i.Status,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}
