// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package tenantdb

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AcademicYear struct {
	ID       int64       `json:"id"`
	SchoolID int64       `json:"school_id"`
	Name     string      `json:"name"`
	StartsOn pgtype.Date `json:"starts_on"`
	EndsOn   pgtype.Date `json:"ends_on"`
	IsActive bool        `json:"is_active"`
}

type AttendanceRecord struct {
	ID        int64              `json:"id"`
	SchoolID  int64              `json:"school_id"`
	SessionID int64              `json:"session_id"`
	StudentID int64              `json:"student_id"`
	Status    string             `json:"status"`
	Method    string             `json:"method"`
	MarkedBy  int64              `json:"marked_by"`
	MarkedAt  pgtype.Timestamptz `json:"marked_at"`
	Meta      []byte             `json:"meta"`
	Note      pgtype.Text        `json:"note"`
}

type AttendanceSession struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	AcademicYearID int64              `json:"academic_year_id"`
	ClassID        int64              `json:"class_id"`
	Date           pgtype.Date        `json:"date"`
	Type           string             `json:"type"`
	ScheduleSlotID pgtype.Int8        `json:"schedule_slot_id"`
	OpenedBy       int64              `json:"opened_by"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID       int64              `json:"id"`
	SchoolID pgtype.Int8        `json:"school_id"`
	UserID   pgtype.Int8        `json:"user_id"`
	Action   string             `json:"action"`
	Entity   string             `json:"entity"`
	EntityID pgtype.Int8        `json:"entity_id"`
	OldValue []byte             `json:"old_value"`
	NewValue []byte             `json:"new_value"`
	At       pgtype.Timestamptz `json:"at"`
}

type Class struct {
	ID                int64       `json:"id"`
	SchoolID          int64       `json:"school_id"`
	AcademicYearID    int64       `json:"academic_year_id"`
	Name              string      `json:"name"`
	Grade             string      `json:"grade"`
	Major             pgtype.Text `json:"major"`
	HomeroomTeacherID pgtype.Int8 `json:"homeroom_teacher_id"`
}

type Enrollment struct {
	ID        int64              `json:"id"`
	SchoolID  int64              `json:"school_id"`
	StudentID int64              `json:"student_id"`
	ClassID   int64              `json:"class_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Guardian struct {
	ID        int64  `json:"id"`
	SchoolID  int64  `json:"school_id"`
	UserID    int64  `json:"user_id"`
	StudentID int64  `json:"student_id"`
	Relation  string `json:"relation"`
}

type Invitation struct {
	ID        int64              `json:"id"`
	SchoolID  int64              `json:"school_id"`
	Code      string             `json:"code"`
	Role      string             `json:"role"`
	TargetID  pgtype.Int8        `json:"target_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

type LeaveApprovalStep struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	LeaveRequestID int64              `json:"leave_request_id"`
	StepOrder      int32              `json:"step_order"`
	ApproverRole   string             `json:"approver_role"`
	ApproverUserID pgtype.Int8        `json:"approver_user_id"`
	DecidedBy      pgtype.Int8        `json:"decided_by"`
	Decision       pgtype.Text        `json:"decision"`
	DecidedAt      pgtype.Timestamptz `json:"decided_at"`
	Comment        pgtype.Text        `json:"comment"`
}

type LeaveRequest struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	TeacherID      int64              `json:"teacher_id"`
	Type           string             `json:"type"`
	DateStart      pgtype.Date        `json:"date_start"`
	DateEnd        pgtype.Date        `json:"date_end"`
	Reason         string             `json:"reason"`
	Attachment     pgtype.Text        `json:"attachment"`
	AttachmentName pgtype.Text        `json:"attachment_name"`
	AttachmentMime pgtype.Text        `json:"attachment_mime"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Membership struct {
	ID       int64  `json:"id"`
	UserID   int64  `json:"user_id"`
	SchoolID int64  `json:"school_id"`
	Role     string `json:"role"`
	Status   string `json:"status"`
}

type Period struct {
	ID       int64       `json:"id"`
	SchoolID int64       `json:"school_id"`
	Number   int32       `json:"number"`
	StartsAt pgtype.Time `json:"starts_at"`
	EndsAt   pgtype.Time `json:"ends_at"`
	Label    pgtype.Text `json:"label"`
}

type Room struct {
	ID       int64  `json:"id"`
	SchoolID int64  `json:"school_id"`
	Name     string `json:"name"`
	QrToken  string `json:"qr_token"`
}

type ScheduleSlot struct {
	ID             int64       `json:"id"`
	SchoolID       int64       `json:"school_id"`
	AcademicYearID int64       `json:"academic_year_id"`
	ClassID        int64       `json:"class_id"`
	SubjectID      int64       `json:"subject_id"`
	TeacherID      int64       `json:"teacher_id"`
	RoomID         pgtype.Int8 `json:"room_id"`
	DayOfWeek      int32       `json:"day_of_week"`
	PeriodStart    int32       `json:"period_start"`
	PeriodEnd      int32       `json:"period_end"`
}

type School struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Slug         string             `json:"slug"`
	CustomDomain pgtype.Text        `json:"custom_domain"`
	Timezone     string             `json:"timezone"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SchoolSetting struct {
	SchoolID  int64              `json:"school_id"`
	Module    string             `json:"module"`
	Settings  []byte             `json:"settings"`
	UpdatedBy pgtype.Int8        `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	SchoolID  pgtype.Int8        `json:"school_id"`
	TokenHash []byte             `json:"token_hash"`
	Role      string             `json:"role"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Ip        *netip.Addr        `json:"ip"`
	UserAgent pgtype.Text        `json:"user_agent"`
}

type Student struct {
	ID        int64              `json:"id"`
	SchoolID  int64              `json:"school_id"`
	Nis       string             `json:"nis"`
	Nisn      pgtype.Text        `json:"nisn"`
	Name      string             `json:"name"`
	Gender    pgtype.Text        `json:"gender"`
	BirthDate pgtype.Date        `json:"birth_date"`
	UserID    pgtype.Int8        `json:"user_id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Subject struct {
	ID       int64  `json:"id"`
	SchoolID int64  `json:"school_id"`
	Code     string `json:"code"`
	Name     string `json:"name"`
}

type Teacher struct {
	ID       int64       `json:"id"`
	SchoolID int64       `json:"school_id"`
	UserID   int64       `json:"user_id"`
	Nip      pgtype.Text `json:"nip"`
}

type TeachingJournal struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	TeacherID      int64              `json:"teacher_id"`
	ScheduleSlotID pgtype.Int8        `json:"schedule_slot_id"`
	ClassID        int64              `json:"class_id"`
	SubjectID      pgtype.Int8        `json:"subject_id"`
	RoomID         pgtype.Int8        `json:"room_id"`
	Date           pgtype.Date        `json:"date"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	EndedAt        pgtype.Timestamptz `json:"ended_at"`
	Material       pgtype.Text        `json:"material"`
	Note           pgtype.Text        `json:"note"`
	Flags          []string           `json:"flags"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        pgtype.Text        `json:"email"`
	Username     pgtype.Text        `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Phone        pgtype.Text        `json:"phone"`
	IsSuperAdmin bool               `json:"is_super_admin"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
