// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package tenantdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateAcademicYear = `-- name: ActivateAcademicYear :one
UPDATE academic_years SET is_active = true WHERE id = $1 AND school_id = $2
RETURNING id, school_id, name, starts_on, ends_on, is_active
`

type ActivateAcademicYearParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) ActivateAcademicYear(ctx context.Context, arg ActivateAcademicYearParams) (AcademicYear, error) {
	row := q.db.QueryRow(ctx, activateAcademicYear, arg.ID, arg.SchoolID)
	var i AcademicYear
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsActive,
	)
	return i, err
}

const clearDomain = `-- name: ClearDomain :one
UPDATE schools SET custom_domain = NULL, pending_domain = NULL
WHERE id = $1
RETURNING id, name, slug, custom_domain, timezone, status, created_at, pending_domain
`

// DELETE /api/custom-domain: hapus baik custom_domain aktif maupun yang
// masih pending sekaligus (satu aksi "lepas domain sendiri").
func (q *Queries) ClearDomain(ctx context.Context, id int64) (School, error) {
	row := q.db.QueryRow(ctx, clearDomain, id)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CustomDomain,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.PendingDomain,
	)
	return i, err
}

const createAcademicYear = `-- name: CreateAcademicYear :one
INSERT INTO academic_years (school_id, name, starts_on, ends_on, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, school_id, name, starts_on, ends_on, is_active
`

type CreateAcademicYearParams struct {
	SchoolID int64       `json:"school_id"`
	Name     string      `json:"name"`
	StartsOn pgtype.Date `json:"starts_on"`
	EndsOn   pgtype.Date `json:"ends_on"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) CreateAcademicYear(ctx context.Context, arg CreateAcademicYearParams) (AcademicYear, error) {
	row := q.db.QueryRow(ctx, createAcademicYear,
		arg.SchoolID,
		arg.Name,
		arg.StartsOn,
		arg.EndsOn,
		arg.IsActive,
	)
	var i AcademicYear
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsActive,
	)
	return i, err
}

const createInterestLead = `-- name: CreateInterestLead :one

INSERT INTO interest_leads (school_name, contact_name, phone, email, note)
VALUES ($1::text, $2::text, $3::text,
        $4::text, $5::text)
RETURNING id, school_name, contact_name, phone, email, note, created_at
`

type CreateInterestLeadParams struct {
	SchoolName  string      `json:"school_name"`
	ContactName string      `json:"contact_name"`
	Phone       string      `json:"phone"`
	Email       pgtype.Text `json:"email"`
	Note        pgtype.Text `json:"note"`
}

// -- registrasi minat sekolah (Fase 11, landing page host platform) --
// interest_leads TANPA school_id (platform-level, calon sekolah belum jadi
// tenant) — lihat catatan migrations/00012_branding_domain_interest.sql.
func (q *Queries) CreateInterestLead(ctx context.Context, arg CreateInterestLeadParams) (InterestLead, error) {
	row := q.db.QueryRow(ctx, createInterestLead,
		arg.SchoolName,
		arg.ContactName,
		arg.Phone,
		arg.Email,
		arg.Note,
	)
	var i InterestLead
	err := row.Scan(
		&i.ID,
		&i.SchoolName,
		&i.ContactName,
		&i.Phone,
		&i.Email,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const createSchool = `-- name: CreateSchool :one
INSERT INTO schools (name, slug, timezone)
VALUES ($1, $2, $3)
RETURNING id, name, slug, custom_domain, timezone, status, created_at, pending_domain
`

type CreateSchoolParams struct {
	Name     string `json:"name"`
	Slug     string `json:"slug"`
	Timezone string `json:"timezone"`
}

func (q *Queries) CreateSchool(ctx context.Context, arg CreateSchoolParams) (School, error) {
	row := q.db.QueryRow(ctx, createSchool, arg.Name, arg.Slug, arg.Timezone)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CustomDomain,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.PendingDomain,
	)
	return i, err
}

const deactivateAcademicYears = `-- name: DeactivateAcademicYears :exec
UPDATE academic_years SET is_active = false WHERE school_id = $1 AND is_active = true
`

func (q *Queries) DeactivateAcademicYears(ctx context.Context, schoolID int64) error {
	_, err := q.db.Exec(ctx, deactivateAcademicYears, schoolID)
	return err
}

const existsDomainUsedByOtherSchool = `-- name: ExistsDomainUsedByOtherSchool :one

SELECT EXISTS (
    SELECT 1 FROM schools
    WHERE id != $1::bigint
      AND (custom_domain = $2::text OR pending_domain = $2::text)
) AS used
`

type ExistsDomainUsedByOtherSchoolParams struct {
	ExcludeID int64  `json:"exclude_id"`
	Domain    string `json:"domain"`
}

// -- custom domain (Fase 11, docs/01-tenant.md "Custom domain & Caddy") --
// Unik LINTAS sekolah, menyilang custom_domain (aktif) dan pending_domain
// (menunggu verifikasi) — partial unique index per kolom tidak bisa
// menyilang dua kolom berbeda, jadi dicek di sini sebelum SetPendingDomain.
func (q *Queries) ExistsDomainUsedByOtherSchool(ctx context.Context, arg ExistsDomainUsedByOtherSchoolParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsDomainUsedByOtherSchool, arg.ExcludeID, arg.Domain)
	var used bool
	err := row.Scan(&used)
	return used, err
}

const getAcademicYear = `-- name: GetAcademicYear :one
SELECT id, school_id, name, starts_on, ends_on, is_active FROM academic_years WHERE id = $1 AND school_id = $2
`

type GetAcademicYearParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) GetAcademicYear(ctx context.Context, arg GetAcademicYearParams) (AcademicYear, error) {
	row := q.db.QueryRow(ctx, getAcademicYear, arg.ID, arg.SchoolID)
	var i AcademicYear
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsActive,
	)
	return i, err
}

const getActiveAcademicYear = `-- name: GetActiveAcademicYear :one
SELECT id, school_id, name, starts_on, ends_on, is_active FROM academic_years WHERE school_id = $1 AND is_active = true
`

func (q *Queries) GetActiveAcademicYear(ctx context.Context, schoolID int64) (AcademicYear, error) {
	row := q.db.QueryRow(ctx, getActiveAcademicYear, schoolID)
	var i AcademicYear
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.StartsOn,
		&i.EndsOn,
		&i.IsActive,
	)
	return i, err
}

const getSchoolByCustomDomain = `-- name: GetSchoolByCustomDomain :one
SELECT id, name, slug, custom_domain, timezone, status, created_at, pending_domain FROM schools WHERE custom_domain = $1 AND status = 'active'
`

func (q *Queries) GetSchoolByCustomDomain(ctx context.Context, customDomain pgtype.Text) (School, error) {
	row := q.db.QueryRow(ctx, getSchoolByCustomDomain, customDomain)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CustomDomain,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.PendingDomain,
	)
	return i, err
}

const getSchoolByID = `-- name: GetSchoolByID :one
SELECT id, name, slug, custom_domain, timezone, status, created_at, pending_domain FROM schools WHERE id = $1
`

func (q *Queries) GetSchoolByID(ctx context.Context, id int64) (School, error) {
	row := q.db.QueryRow(ctx, getSchoolByID, id)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CustomDomain,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.PendingDomain,
	)
	return i, err
}

const getSchoolBySlug = `-- name: GetSchoolBySlug :one

SELECT id, name, slug, custom_domain, timezone, status, created_at, pending_domain FROM schools WHERE slug = $1 AND status = 'active'
`

// Query modul tenant (sqlc). Semua query tenant-scoped WAJIB filter school_id.
func (q *Queries) GetSchoolBySlug(ctx context.Context, slug string) (School, error) {
	row := q.db.QueryRow(ctx, getSchoolBySlug, slug)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CustomDomain,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.PendingDomain,
	)
	return i, err
}

const getSchoolBySlugAny = `-- name: GetSchoolBySlugAny :one
SELECT id, name, slug, custom_domain, timezone, status, created_at, pending_domain FROM schools WHERE slug = $1
`

// Dipakai admin/bootstrap: tanpa filter status (untuk cek idempoten & manajemen).
func (q *Queries) GetSchoolBySlugAny(ctx context.Context, slug string) (School, error) {
	row := q.db.QueryRow(ctx, getSchoolBySlugAny, slug)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CustomDomain,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.PendingDomain,
	)
	return i, err
}

const getSchoolSetting = `-- name: GetSchoolSetting :one
SELECT school_id, module, settings, updated_by, updated_at FROM school_settings WHERE school_id = $1 AND module = $2
`

type GetSchoolSettingParams struct {
	SchoolID int64  `json:"school_id"`
	Module   string `json:"module"`
}

func (q *Queries) GetSchoolSetting(ctx context.Context, arg GetSchoolSettingParams) (SchoolSetting, error) {
	row := q.db.QueryRow(ctx, getSchoolSetting, arg.SchoolID, arg.Module)
	var i SchoolSetting
	err := row.Scan(
		&i.SchoolID,
		&i.Module,
		&i.Settings,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listAcademicYears = `-- name: ListAcademicYears :many
SELECT id, school_id, name, starts_on, ends_on, is_active FROM academic_years WHERE school_id = $1 ORDER BY starts_on DESC
`

func (q *Queries) ListAcademicYears(ctx context.Context, schoolID int64) ([]AcademicYear, error) {
	rows, err := q.db.Query(ctx, listAcademicYears, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcademicYear
	for rows.Next() {
		var i AcademicYear
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Name,
			&i.StartsOn,
			&i.EndsOn,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInterestLeads = `-- name: ListInterestLeads :many
SELECT id, school_name, contact_name, phone, email, note, created_at FROM interest_leads ORDER BY created_at DESC
`

func (q *Queries) ListInterestLeads(ctx context.Context) ([]InterestLead, error) {
	rows, err := q.db.Query(ctx, listInterestLeads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InterestLead
	for rows.Next() {
		var i InterestLead
		if err := rows.Scan(
			&i.ID,
			&i.SchoolName,
			&i.ContactName,
			&i.Phone,
			&i.Email,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchools = `-- name: ListSchools :many
SELECT id, name, slug, custom_domain, timezone, status, created_at, pending_domain FROM schools ORDER BY created_at DESC
`

func (q *Queries) ListSchools(ctx context.Context) ([]School, error) {
	rows, err := q.db.Query(ctx, listSchools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []School
	for rows.Next() {
		var i School
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CustomDomain,
			&i.Timezone,
			&i.Status,
			&i.CreatedAt,
			&i.PendingDomain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPendingDomain = `-- name: SetPendingDomain :one
UPDATE schools SET pending_domain = $1::text WHERE id = $2::bigint
RETURNING id, name, slug, custom_domain, timezone, status, created_at, pending_domain
`

type SetPendingDomainParams struct {
	Domain string `json:"domain"`
	ID     int64  `json:"id"`
}

func (q *Queries) SetPendingDomain(ctx context.Context, arg SetPendingDomainParams) (School, error) {
	row := q.db.QueryRow(ctx, setPendingDomain, arg.Domain, arg.ID)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CustomDomain,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.PendingDomain,
	)
	return i, err
}

const updateSchool = `-- name: UpdateSchool :one
UPDATE schools SET
    name          = COALESCE($1, name),
    custom_domain = COALESCE($2, custom_domain),
    timezone      = COALESCE($3, timezone),
    status        = COALESCE($4, status)
WHERE id = $5
RETURNING id, name, slug, custom_domain, timezone, status, created_at, pending_domain
`

type UpdateSchoolParams struct {
	Name         pgtype.Text `json:"name"`
	CustomDomain pgtype.Text `json:"custom_domain"`
	Timezone     pgtype.Text `json:"timezone"`
	Status       pgtype.Text `json:"status"`
	ID           int64       `json:"id"`
}

func (q *Queries) UpdateSchool(ctx context.Context, arg UpdateSchoolParams) (School, error) {
	row := q.db.QueryRow(ctx, updateSchool,
		arg.Name,
		arg.CustomDomain,
		arg.Timezone,
		arg.Status,
		arg.ID,
	)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CustomDomain,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.PendingDomain,
	)
	return i, err
}

const upsertSchoolSetting = `-- name: UpsertSchoolSetting :one
INSERT INTO school_settings (school_id, module, settings, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (school_id, module) DO UPDATE
    SET settings = EXCLUDED.settings, updated_by = EXCLUDED.updated_by, updated_at = now()
RETURNING school_id, module, settings, updated_by, updated_at
`

type UpsertSchoolSettingParams struct {
	SchoolID  int64       `json:"school_id"`
	Module    string      `json:"module"`
	Settings  []byte      `json:"settings"`
	UpdatedBy pgtype.Int8 `json:"updated_by"`
}

func (q *Queries) UpsertSchoolSetting(ctx context.Context, arg UpsertSchoolSettingParams) (SchoolSetting, error) {
	row := q.db.QueryRow(ctx, upsertSchoolSetting,
		arg.SchoolID,
		arg.Module,
		arg.Settings,
		arg.UpdatedBy,
	)
	var i SchoolSetting
	err := row.Scan(
		&i.SchoolID,
		&i.Module,
		&i.Settings,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyPendingDomain = `-- name: VerifyPendingDomain :one
UPDATE schools SET custom_domain = pending_domain, pending_domain = NULL
WHERE id = $1
RETURNING id, name, slug, custom_domain, timezone, status, created_at, pending_domain
`

// Verifikasi sukses: pending_domain pindah jadi custom_domain aktif.
func (q *Queries) VerifyPendingDomain(ctx context.Context, id int64) (School, error) {
	row := q.db.QueryRow(ctx, verifyPendingDomain, id)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CustomDomain,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.PendingDomain,
	)
	return i, err
}
