// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package scheduledb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSlotsForRoom = `-- name: CountSlotsForRoom :one
SELECT COUNT(*) FROM schedule_slots WHERE room_id = $1 AND school_id = $2
`

type CountSlotsForRoomParams struct {
	RoomID   pgtype.Int8 `json:"room_id"`
	SchoolID int64       `json:"school_id"`
}

func (q *Queries) CountSlotsForRoom(ctx context.Context, arg CountSlotsForRoomParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSlotsForRoom, arg.RoomID, arg.SchoolID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRoom = `-- name: CreateRoom :one

INSERT INTO rooms (school_id, name, qr_token) VALUES ($1, $2, $3) RETURNING id, school_id, name, qr_token
`

type CreateRoomParams struct {
	SchoolID int64  `json:"school_id"`
	Name     string `json:"name"`
	QrToken  string `json:"qr_token"`
}

// -- rooms --
func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.SchoolID, arg.Name, arg.QrToken)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.QrToken,
	)
	return i, err
}

const deletePeriodOverridesForDay = `-- name: DeletePeriodOverridesForDay :exec
DELETE FROM period_day_overrides WHERE school_id = $1 AND day_of_week = $2
`

type DeletePeriodOverridesForDayParams struct {
	SchoolID  int64 `json:"school_id"`
	DayOfWeek int32 `json:"day_of_week"`
}

func (q *Queries) DeletePeriodOverridesForDay(ctx context.Context, arg DeletePeriodOverridesForDayParams) error {
	_, err := q.db.Exec(ctx, deletePeriodOverridesForDay, arg.SchoolID, arg.DayOfWeek)
	return err
}

const deletePeriods = `-- name: DeletePeriods :exec
DELETE FROM periods WHERE school_id = $1
`

func (q *Queries) DeletePeriods(ctx context.Context, schoolID int64) error {
	_, err := q.db.Exec(ctx, deletePeriods, schoolID)
	return err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE id = $1 AND school_id = $2
`

type DeleteRoomParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) DeleteRoom(ctx context.Context, arg DeleteRoomParams) error {
	_, err := q.db.Exec(ctx, deleteRoom, arg.ID, arg.SchoolID)
	return err
}

const deleteSlot = `-- name: DeleteSlot :exec
DELETE FROM schedule_slots WHERE id = $1 AND school_id = $2
`

type DeleteSlotParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) DeleteSlot(ctx context.Context, arg DeleteSlotParams) error {
	_, err := q.db.Exec(ctx, deleteSlot, arg.ID, arg.SchoolID)
	return err
}

const getClassRef = `-- name: GetClassRef :one

SELECT id, name, academic_year_id FROM classes WHERE id = $1 AND school_id = $2
`

type GetClassRefParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetClassRefRow struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	AcademicYearID int64  `json:"academic_year_id"`
}

// -- referensi (validasi & lookup by kode/nama, dipakai builder & import) --
func (q *Queries) GetClassRef(ctx context.Context, arg GetClassRefParams) (GetClassRefRow, error) {
	row := q.db.QueryRow(ctx, getClassRef, arg.ID, arg.SchoolID)
	var i GetClassRefRow
	err := row.Scan(&i.ID, &i.Name, &i.AcademicYearID)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, school_id, name, qr_token FROM rooms WHERE id = $1 AND school_id = $2
`

type GetRoomByIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) GetRoomByID(ctx context.Context, arg GetRoomByIDParams) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, arg.ID, arg.SchoolID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.QrToken,
	)
	return i, err
}

const getRoomRef = `-- name: GetRoomRef :one
SELECT id, name FROM rooms WHERE id = $1 AND school_id = $2
`

type GetRoomRefParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetRoomRefRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetRoomRef(ctx context.Context, arg GetRoomRefParams) (GetRoomRefRow, error) {
	row := q.db.QueryRow(ctx, getRoomRef, arg.ID, arg.SchoolID)
	var i GetRoomRefRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getSlotByID = `-- name: GetSlotByID :one
SELECT sl.id, sl.school_id, sl.academic_year_id,
       sl.class_id, c.name AS class_name,
       sl.subject_id, sub.code AS subject_code, sub.name AS subject_name,
       sl.teacher_id, u.name AS teacher_name,
       sl.room_id, COALESCE(r.name, '') AS room_name,
       sl.day_of_week, sl.period_start, sl.period_end
FROM schedule_slots sl
JOIN classes c ON c.id = sl.class_id
JOIN subjects sub ON sub.id = sl.subject_id
JOIN teachers t ON t.id = sl.teacher_id
JOIN users u ON u.id = t.user_id
LEFT JOIN rooms r ON r.id = sl.room_id
WHERE sl.id = $1 AND sl.school_id = $2
`

type GetSlotByIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetSlotByIDRow struct {
	ID             int64       `json:"id"`
	SchoolID       int64       `json:"school_id"`
	AcademicYearID int64       `json:"academic_year_id"`
	ClassID        int64       `json:"class_id"`
	ClassName      string      `json:"class_name"`
	SubjectID      int64       `json:"subject_id"`
	SubjectCode    string      `json:"subject_code"`
	SubjectName    string      `json:"subject_name"`
	TeacherID      int64       `json:"teacher_id"`
	TeacherName    string      `json:"teacher_name"`
	RoomID         pgtype.Int8 `json:"room_id"`
	RoomName       string      `json:"room_name"`
	DayOfWeek      int32       `json:"day_of_week"`
	PeriodStart    int32       `json:"period_start"`
	PeriodEnd      int32       `json:"period_end"`
}

func (q *Queries) GetSlotByID(ctx context.Context, arg GetSlotByIDParams) (GetSlotByIDRow, error) {
	row := q.db.QueryRow(ctx, getSlotByID, arg.ID, arg.SchoolID)
	var i GetSlotByIDRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.ClassID,
		&i.ClassName,
		&i.SubjectID,
		&i.SubjectCode,
		&i.SubjectName,
		&i.TeacherID,
		&i.TeacherName,
		&i.RoomID,
		&i.RoomName,
		&i.DayOfWeek,
		&i.PeriodStart,
		&i.PeriodEnd,
	)
	return i, err
}

const getSubjectRef = `-- name: GetSubjectRef :one
SELECT id, code, name FROM subjects WHERE id = $1 AND school_id = $2
`

type GetSubjectRefParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetSubjectRefRow struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) GetSubjectRef(ctx context.Context, arg GetSubjectRefParams) (GetSubjectRefRow, error) {
	row := q.db.QueryRow(ctx, getSubjectRef, arg.ID, arg.SchoolID)
	var i GetSubjectRefRow
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const getTeacherRef = `-- name: GetTeacherRef :one
SELECT t.id, u.name FROM teachers t JOIN users u ON u.id = t.user_id WHERE t.id = $1 AND t.school_id = $2
`

type GetTeacherRefParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetTeacherRefRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetTeacherRef(ctx context.Context, arg GetTeacherRefParams) (GetTeacherRefRow, error) {
	row := q.db.QueryRow(ctx, getTeacherRef, arg.ID, arg.SchoolID)
	var i GetTeacherRefRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const insertPeriod = `-- name: InsertPeriod :one
INSERT INTO periods (school_id, number, starts_at, ends_at, label)
VALUES ($1, $2, $3, $4, $5::text)
RETURNING id, school_id, number, starts_at, ends_at, label
`

type InsertPeriodParams struct {
	SchoolID int64       `json:"school_id"`
	Number   int32       `json:"number"`
	StartsAt pgtype.Time `json:"starts_at"`
	EndsAt   pgtype.Time `json:"ends_at"`
	Label    pgtype.Text `json:"label"`
}

func (q *Queries) InsertPeriod(ctx context.Context, arg InsertPeriodParams) (Period, error) {
	row := q.db.QueryRow(ctx, insertPeriod,
		arg.SchoolID,
		arg.Number,
		arg.StartsAt,
		arg.EndsAt,
		arg.Label,
	)
	var i Period
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Number,
		&i.StartsAt,
		&i.EndsAt,
		&i.Label,
	)
	return i, err
}

const insertPeriodOverride = `-- name: InsertPeriodOverride :one
INSERT INTO period_day_overrides (school_id, day_of_week, number, starts_at, ends_at, label)
VALUES ($1, $2, $3, $4, $5, $6::text)
RETURNING id, school_id, day_of_week, number, starts_at, ends_at, label
`

type InsertPeriodOverrideParams struct {
	SchoolID  int64       `json:"school_id"`
	DayOfWeek int32       `json:"day_of_week"`
	Number    int32       `json:"number"`
	StartsAt  pgtype.Time `json:"starts_at"`
	EndsAt    pgtype.Time `json:"ends_at"`
	Label     pgtype.Text `json:"label"`
}

func (q *Queries) InsertPeriodOverride(ctx context.Context, arg InsertPeriodOverrideParams) (PeriodDayOverride, error) {
	row := q.db.QueryRow(ctx, insertPeriodOverride,
		arg.SchoolID,
		arg.DayOfWeek,
		arg.Number,
		arg.StartsAt,
		arg.EndsAt,
		arg.Label,
	)
	var i PeriodDayOverride
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.DayOfWeek,
		&i.Number,
		&i.StartsAt,
		&i.EndsAt,
		&i.Label,
	)
	return i, err
}

const insertSlot = `-- name: InsertSlot :one
INSERT INTO schedule_slots (school_id, academic_year_id, class_id, subject_id, teacher_id, room_id, day_of_week, period_start, period_end)
VALUES ($1, $2, $3, $4, $5, $9::bigint, $6, $7, $8)
RETURNING id
`

type InsertSlotParams struct {
	SchoolID       int64       `json:"school_id"`
	AcademicYearID int64       `json:"academic_year_id"`
	ClassID        int64       `json:"class_id"`
	SubjectID      int64       `json:"subject_id"`
	TeacherID      int64       `json:"teacher_id"`
	DayOfWeek      int32       `json:"day_of_week"`
	PeriodStart    int32       `json:"period_start"`
	PeriodEnd      int32       `json:"period_end"`
	RoomID         pgtype.Int8 `json:"room_id"`
}

func (q *Queries) InsertSlot(ctx context.Context, arg InsertSlotParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSlot,
		arg.SchoolID,
		arg.AcademicYearID,
		arg.ClassID,
		arg.SubjectID,
		arg.TeacherID,
		arg.DayOfWeek,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.RoomID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listPeriodOverridesForDay = `-- name: ListPeriodOverridesForDay :many

SELECT id, school_id, day_of_week, number, starts_at, ends_at, label FROM period_day_overrides WHERE school_id = $1 AND day_of_week = $2 ORDER BY number
`

type ListPeriodOverridesForDayParams struct {
	SchoolID  int64 `json:"school_id"`
	DayOfWeek int32 `json:"day_of_week"`
}

// -- period_day_overrides (Fase 14 Gelombang D, docs/12-sion-parity.md) --
func (q *Queries) ListPeriodOverridesForDay(ctx context.Context, arg ListPeriodOverridesForDayParams) ([]PeriodDayOverride, error) {
	rows, err := q.db.Query(ctx, listPeriodOverridesForDay, arg.SchoolID, arg.DayOfWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeriodDayOverride
	for rows.Next() {
		var i PeriodDayOverride
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.DayOfWeek,
			&i.Number,
			&i.StartsAt,
			&i.EndsAt,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriods = `-- name: ListPeriods :many


SELECT id, school_id, number, starts_at, ends_at, label FROM periods WHERE school_id = $1 ORDER BY number
`

// Query modul schedule (sqlc). Semua query tenant-scoped WAJIB filter
// school_id. Catatan: join read-only ke classes/subjects/teachers (dimiliki
// modul student) dan users (dimiliki modul identity) dipakai untuk
// menampilkan nama tanpa N+1 call lintas modul — pola yang sama dengan
// internal/attendance/queries.sql. Semua TULIS ke tabel modul lain tetap
// TIDAK PERNAH dilakukan di sini.
// -- periods --
func (q *Queries) ListPeriods(ctx context.Context, schoolID int64) ([]Period, error) {
	rows, err := q.db.Query(ctx, listPeriods, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Period
	for rows.Next() {
		var i Period
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Number,
			&i.StartsAt,
			&i.EndsAt,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, school_id, name, qr_token FROM rooms WHERE school_id = $1 ORDER BY name
`

func (q *Queries) ListRooms(ctx context.Context, schoolID int64) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Name,
			&i.QrToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlotPeriodRanges = `-- name: ListSlotPeriodRanges :many
SELECT DISTINCT period_start, period_end FROM schedule_slots WHERE school_id = $1
`

type ListSlotPeriodRangesRow struct {
	PeriodStart int32 `json:"period_start"`
	PeriodEnd   int32 `json:"period_end"`
}

func (q *Queries) ListSlotPeriodRanges(ctx context.Context, schoolID int64) ([]ListSlotPeriodRangesRow, error) {
	rows, err := q.db.Query(ctx, listSlotPeriodRanges, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSlotPeriodRangesRow
	for rows.Next() {
		var i ListSlotPeriodRangesRow
		if err := rows.Scan(&i.PeriodStart, &i.PeriodEnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlotsForYear = `-- name: ListSlotsForYear :many

SELECT sl.id, sl.school_id, sl.academic_year_id,
       sl.class_id, c.name AS class_name,
       sl.subject_id, sub.code AS subject_code, sub.name AS subject_name,
       sl.teacher_id, u.name AS teacher_name,
       sl.room_id, COALESCE(r.name, '') AS room_name,
       sl.day_of_week, sl.period_start, sl.period_end
FROM schedule_slots sl
JOIN classes c ON c.id = sl.class_id
JOIN subjects sub ON sub.id = sl.subject_id
JOIN teachers t ON t.id = sl.teacher_id
JOIN users u ON u.id = t.user_id
LEFT JOIN rooms r ON r.id = sl.room_id
WHERE sl.school_id = $1 AND sl.academic_year_id = $2
ORDER BY sl.day_of_week, sl.period_start
`

type ListSlotsForYearParams struct {
	SchoolID       int64 `json:"school_id"`
	AcademicYearID int64 `json:"academic_year_id"`
}

type ListSlotsForYearRow struct {
	ID             int64       `json:"id"`
	SchoolID       int64       `json:"school_id"`
	AcademicYearID int64       `json:"academic_year_id"`
	ClassID        int64       `json:"class_id"`
	ClassName      string      `json:"class_name"`
	SubjectID      int64       `json:"subject_id"`
	SubjectCode    string      `json:"subject_code"`
	SubjectName    string      `json:"subject_name"`
	TeacherID      int64       `json:"teacher_id"`
	TeacherName    string      `json:"teacher_name"`
	RoomID         pgtype.Int8 `json:"room_id"`
	RoomName       string      `json:"room_name"`
	DayOfWeek      int32       `json:"day_of_week"`
	PeriodStart    int32       `json:"period_start"`
	PeriodEnd      int32       `json:"period_end"`
}

// -- schedule_slots --
func (q *Queries) ListSlotsForYear(ctx context.Context, arg ListSlotsForYearParams) ([]ListSlotsForYearRow, error) {
	rows, err := q.db.Query(ctx, listSlotsForYear, arg.SchoolID, arg.AcademicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSlotsForYearRow
	for rows.Next() {
		var i ListSlotsForYearRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.AcademicYearID,
			&i.ClassID,
			&i.ClassName,
			&i.SubjectID,
			&i.SubjectCode,
			&i.SubjectName,
			&i.TeacherID,
			&i.TeacherName,
			&i.RoomID,
			&i.RoomName,
			&i.DayOfWeek,
			&i.PeriodStart,
			&i.PeriodEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupClassIDByName = `-- name: LookupClassIDByName :one
SELECT id FROM classes WHERE school_id = $1 AND academic_year_id = $2 AND name = $3
`

type LookupClassIDByNameParams struct {
	SchoolID       int64  `json:"school_id"`
	AcademicYearID int64  `json:"academic_year_id"`
	Name           string `json:"name"`
}

func (q *Queries) LookupClassIDByName(ctx context.Context, arg LookupClassIDByNameParams) (int64, error) {
	row := q.db.QueryRow(ctx, lookupClassIDByName, arg.SchoolID, arg.AcademicYearID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lookupRoomIDByName = `-- name: LookupRoomIDByName :one
SELECT id FROM rooms WHERE school_id = $1 AND name = $2
`

type LookupRoomIDByNameParams struct {
	SchoolID int64  `json:"school_id"`
	Name     string `json:"name"`
}

func (q *Queries) LookupRoomIDByName(ctx context.Context, arg LookupRoomIDByNameParams) (int64, error) {
	row := q.db.QueryRow(ctx, lookupRoomIDByName, arg.SchoolID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lookupSubjectByCode = `-- name: LookupSubjectByCode :one
SELECT id, code, name FROM subjects WHERE school_id = $1 AND code = $2
`

type LookupSubjectByCodeParams struct {
	SchoolID int64  `json:"school_id"`
	Code     string `json:"code"`
}

type LookupSubjectByCodeRow struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) LookupSubjectByCode(ctx context.Context, arg LookupSubjectByCodeParams) (LookupSubjectByCodeRow, error) {
	row := q.db.QueryRow(ctx, lookupSubjectByCode, arg.SchoolID, arg.Code)
	var i LookupSubjectByCodeRow
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const lookupTeacherByEmail = `-- name: LookupTeacherByEmail :one
SELECT t.id, u.name FROM teachers t JOIN users u ON u.id = t.user_id WHERE t.school_id = $1 AND u.email = $2
`

type LookupTeacherByEmailParams struct {
	SchoolID int64       `json:"school_id"`
	Email    pgtype.Text `json:"email"`
}

type LookupTeacherByEmailRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) LookupTeacherByEmail(ctx context.Context, arg LookupTeacherByEmailParams) (LookupTeacherByEmailRow, error) {
	row := q.db.QueryRow(ctx, lookupTeacherByEmail, arg.SchoolID, arg.Email)
	var i LookupTeacherByEmailRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const regenerateRoomQRToken = `-- name: RegenerateRoomQRToken :one
UPDATE rooms SET qr_token = $3 WHERE id = $1 AND school_id = $2 RETURNING id, school_id, name, qr_token
`

type RegenerateRoomQRTokenParams struct {
	ID       int64  `json:"id"`
	SchoolID int64  `json:"school_id"`
	QrToken  string `json:"qr_token"`
}

func (q *Queries) RegenerateRoomQRToken(ctx context.Context, arg RegenerateRoomQRTokenParams) (Room, error) {
	row := q.db.QueryRow(ctx, regenerateRoomQRToken, arg.ID, arg.SchoolID, arg.QrToken)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.QrToken,
	)
	return i, err
}

const updateRoomName = `-- name: UpdateRoomName :one
UPDATE rooms SET name = $3 WHERE id = $1 AND school_id = $2 RETURNING id, school_id, name, qr_token
`

type UpdateRoomNameParams struct {
	ID       int64  `json:"id"`
	SchoolID int64  `json:"school_id"`
	Name     string `json:"name"`
}

func (q *Queries) UpdateRoomName(ctx context.Context, arg UpdateRoomNameParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoomName, arg.ID, arg.SchoolID, arg.Name)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.QrToken,
	)
	return i, err
}

const updateSlot = `-- name: UpdateSlot :exec
UPDATE schedule_slots SET
    class_id = $3, subject_id = $4, teacher_id = $5, room_id = $9::bigint,
    day_of_week = $6, period_start = $7, period_end = $8
WHERE id = $1 AND school_id = $2
`

type UpdateSlotParams struct {
	ID          int64       `json:"id"`
	SchoolID    int64       `json:"school_id"`
	ClassID     int64       `json:"class_id"`
	SubjectID   int64       `json:"subject_id"`
	TeacherID   int64       `json:"teacher_id"`
	DayOfWeek   int32       `json:"day_of_week"`
	PeriodStart int32       `json:"period_start"`
	PeriodEnd   int32       `json:"period_end"`
	RoomID      pgtype.Int8 `json:"room_id"`
}

func (q *Queries) UpdateSlot(ctx context.Context, arg UpdateSlotParams) error {
	_, err := q.db.Exec(ctx, updateSlot,
		arg.ID,
		arg.SchoolID,
		arg.ClassID,
		arg.SubjectID,
		arg.TeacherID,
		arg.DayOfWeek,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.RoomID,
	)
	return err
}
