// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package employeedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (school_id, user_id, nip)
VALUES ($1, $2, $3)
RETURNING id, school_id, user_id, nip
`

type CreateEmployeeParams struct {
	SchoolID int64  `json:"school_id"`
	UserID   int64  `json:"user_id"`
	Nip      string `json:"nip"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee, arg.SchoolID, arg.UserID, arg.Nip)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.UserID,
		&i.Nip,
	)
	return i, err
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
SELECT e.id, e.school_id, e.user_id, e.nip, u.name, u.email, u.username
FROM employees e JOIN users u ON u.id = e.user_id
WHERE e.id = $1 AND e.school_id = $2
`

type GetEmployeeByIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetEmployeeByIDRow struct {
	ID       int64       `json:"id"`
	SchoolID int64       `json:"school_id"`
	UserID   int64       `json:"user_id"`
	Nip      string      `json:"nip"`
	Name     string      `json:"name"`
	Email    pgtype.Text `json:"email"`
	Username pgtype.Text `json:"username"`
}

func (q *Queries) GetEmployeeByID(ctx context.Context, arg GetEmployeeByIDParams) (GetEmployeeByIDRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeByID, arg.ID, arg.SchoolID)
	var i GetEmployeeByIDRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.UserID,
		&i.Nip,
		&i.Name,
		&i.Email,
		&i.Username,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many
SELECT e.id, e.school_id, e.user_id, e.nip, u.name, u.email, u.username
FROM employees e JOIN users u ON u.id = e.user_id
WHERE e.school_id = $1
ORDER BY u.name
`

type ListEmployeesRow struct {
	ID       int64       `json:"id"`
	SchoolID int64       `json:"school_id"`
	UserID   int64       `json:"user_id"`
	Nip      string      `json:"nip"`
	Name     string      `json:"name"`
	Email    pgtype.Text `json:"email"`
	Username pgtype.Text `json:"username"`
}

func (q *Queries) ListEmployees(ctx context.Context, schoolID int64) ([]ListEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listEmployees, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmployeesRow
	for rows.Next() {
		var i ListEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.UserID,
			&i.Nip,
			&i.Name,
			&i.Email,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployeeNIP = `-- name: UpdateEmployeeNIP :one
UPDATE employees SET nip = $3 WHERE id = $1 AND school_id = $2
RETURNING id, school_id, user_id, nip
`

type UpdateEmployeeNIPParams struct {
	ID       int64  `json:"id"`
	SchoolID int64  `json:"school_id"`
	Nip      string `json:"nip"`
}

func (q *Queries) UpdateEmployeeNIP(ctx context.Context, arg UpdateEmployeeNIPParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployeeNIP, arg.ID, arg.SchoolID, arg.Nip)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.UserID,
		&i.Nip,
	)
	return i, err
}
