// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package attendancedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEnrolledForClass = `-- name: CountEnrolledForClass :one
SELECT COUNT(*) FROM enrollments WHERE class_id = $1
`

func (q *Queries) CountEnrolledForClass(ctx context.Context, classID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countEnrolledForClass, classID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecordsForSession = `-- name: CountRecordsForSession :one
SELECT COUNT(*) FROM attendance_records WHERE session_id = $1
`

func (q *Queries) CountRecordsForSession(ctx context.Context, sessionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRecordsForSession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO attendance_sessions (school_id, academic_year_id, class_id, date, type, opened_by, status)
VALUES ($1, $2, $3, $4, 'daily', $5, 'open')
RETURNING id, school_id, academic_year_id, class_id, date, type, schedule_slot_id, opened_by, status, created_at
`

type CreateSessionParams struct {
	SchoolID       int64       `json:"school_id"`
	AcademicYearID int64       `json:"academic_year_id"`
	ClassID        int64       `json:"class_id"`
	Date           pgtype.Date `json:"date"`
	OpenedBy       int64       `json:"opened_by"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AttendanceSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.SchoolID,
		arg.AcademicYearID,
		arg.ClassID,
		arg.Date,
		arg.OpenedBy,
	)
	var i AttendanceSession
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.ClassID,
		&i.Date,
		&i.Type,
		&i.ScheduleSlotID,
		&i.OpenedBy,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createSubjectSession = `-- name: CreateSubjectSession :one

INSERT INTO attendance_sessions (school_id, academic_year_id, class_id, date, type, schedule_slot_id, opened_by, status)
VALUES ($1, $2, $3, $4, 'subject', $5, $6, 'open')
RETURNING id, school_id, academic_year_id, class_id, date, type, schedule_slot_id, opened_by, status, created_at
`

type CreateSubjectSessionParams struct {
	SchoolID       int64       `json:"school_id"`
	AcademicYearID int64       `json:"academic_year_id"`
	ClassID        int64       `json:"class_id"`
	Date           pgtype.Date `json:"date"`
	ScheduleSlotID pgtype.Int8 `json:"schedule_slot_id"`
	OpenedBy       int64       `json:"opened_by"`
}

// -- mode per_subject (fase 6, docs/05 & docs/06): sesi type='subject' terikat
// -- schedule_slot_id, bukan class_id+date langsung — dibuka via scan QR
// -- ruangan (teaching.Scan -> attendance.OpenSubjectSession) ATAU manual dari
// -- layar "slot hari ini" guru (POST /api/attendance/sessions {schedule_slot_id}).
func (q *Queries) CreateSubjectSession(ctx context.Context, arg CreateSubjectSessionParams) (AttendanceSession, error) {
	row := q.db.QueryRow(ctx, createSubjectSession,
		arg.SchoolID,
		arg.AcademicYearID,
		arg.ClassID,
		arg.Date,
		arg.ScheduleSlotID,
		arg.OpenedBy,
	)
	var i AttendanceSession
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.ClassID,
		&i.Date,
		&i.Type,
		&i.ScheduleSlotID,
		&i.OpenedBy,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const finalizeSession = `-- name: FinalizeSession :one
UPDATE attendance_sessions SET status = 'finalized' WHERE id = $1 AND school_id = $2 RETURNING id, school_id, academic_year_id, class_id, date, type, schedule_slot_id, opened_by, status, created_at
`

type FinalizeSessionParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) FinalizeSession(ctx context.Context, arg FinalizeSessionParams) (AttendanceSession, error) {
	row := q.db.QueryRow(ctx, finalizeSession, arg.ID, arg.SchoolID)
	var i AttendanceSession
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.ClassID,
		&i.Date,
		&i.Type,
		&i.ScheduleSlotID,
		&i.OpenedBy,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveQRTokenByStudent = `-- name: GetActiveQRTokenByStudent :one
SELECT token FROM student_qr_tokens
WHERE student_id = $1 AND school_id = $2 AND revoked_at IS NULL
`

type GetActiveQRTokenByStudentParams struct {
	StudentID int64 `json:"student_id"`
	SchoolID  int64 `json:"school_id"`
}

func (q *Queries) GetActiveQRTokenByStudent(ctx context.Context, arg GetActiveQRTokenByStudentParams) (string, error) {
	row := q.db.QueryRow(ctx, getActiveQRTokenByStudent, arg.StudentID, arg.SchoolID)
	var token string
	err := row.Scan(&token)
	return token, err
}

const getActiveQRTokenStudentID = `-- name: GetActiveQRTokenStudentID :one
SELECT student_id FROM student_qr_tokens
WHERE token = $1 AND school_id = $2 AND revoked_at IS NULL
`

type GetActiveQRTokenStudentIDParams struct {
	Token    string `json:"token"`
	SchoolID int64  `json:"school_id"`
}

func (q *Queries) GetActiveQRTokenStudentID(ctx context.Context, arg GetActiveQRTokenStudentIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getActiveQRTokenStudentID, arg.Token, arg.SchoolID)
	var student_id int64
	err := row.Scan(&student_id)
	return student_id, err
}

const getAttendanceSettingsRaw = `-- name: GetAttendanceSettingsRaw :one

SELECT settings FROM school_settings WHERE school_id = $1 AND module = 'attendance'
`

// -- settings (dibaca langsung dari school_settings module='attendance' —
// -- tabel & pola yang sama dipakai GET/PUT /api/settings/attendance lewat
// -- tenant.SettingsService; ini hanya baca untuk kebutuhan aturan bisnis
// -- internal, mis. edit_window_hours — lihat CLAUDE.md "satu pola settings").
func (q *Queries) GetAttendanceSettingsRaw(ctx context.Context, schoolID int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getAttendanceSettingsRaw, schoolID)
	var settings []byte
	err := row.Scan(&settings)
	return settings, err
}

const getClassMeta = `-- name: GetClassMeta :one
SELECT id, name, academic_year_id FROM classes WHERE id = $1 AND school_id = $2
`

type GetClassMetaParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetClassMetaRow struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	AcademicYearID int64  `json:"academic_year_id"`
}

func (q *Queries) GetClassMeta(ctx context.Context, arg GetClassMetaParams) (GetClassMetaRow, error) {
	row := q.db.QueryRow(ctx, getClassMeta, arg.ID, arg.SchoolID)
	var i GetClassMetaRow
	err := row.Scan(&i.ID, &i.Name, &i.AcademicYearID)
	return i, err
}

const getRecordForStudent = `-- name: GetRecordForStudent :one
SELECT student_id, status, method, note, marked_at FROM attendance_records
WHERE session_id = $1 AND student_id = $2
`

type GetRecordForStudentParams struct {
	SessionID int64 `json:"session_id"`
	StudentID int64 `json:"student_id"`
}

type GetRecordForStudentRow struct {
	StudentID int64              `json:"student_id"`
	Status    string             `json:"status"`
	Method    string             `json:"method"`
	Note      pgtype.Text        `json:"note"`
	MarkedAt  pgtype.Timestamptz `json:"marked_at"`
}

func (q *Queries) GetRecordForStudent(ctx context.Context, arg GetRecordForStudentParams) (GetRecordForStudentRow, error) {
	row := q.db.QueryRow(ctx, getRecordForStudent, arg.SessionID, arg.StudentID)
	var i GetRecordForStudentRow
	err := row.Scan(
		&i.StudentID,
		&i.Status,
		&i.Method,
		&i.Note,
		&i.MarkedAt,
	)
	return i, err
}

const getSessionByClassDate = `-- name: GetSessionByClassDate :one
SELECT id, school_id, academic_year_id, class_id, date, type, schedule_slot_id, opened_by, status, created_at FROM attendance_sessions
WHERE school_id = $1 AND class_id = $2 AND date = $3 AND type = 'daily'
`

type GetSessionByClassDateParams struct {
	SchoolID int64       `json:"school_id"`
	ClassID  int64       `json:"class_id"`
	Date     pgtype.Date `json:"date"`
}

func (q *Queries) GetSessionByClassDate(ctx context.Context, arg GetSessionByClassDateParams) (AttendanceSession, error) {
	row := q.db.QueryRow(ctx, getSessionByClassDate, arg.SchoolID, arg.ClassID, arg.Date)
	var i AttendanceSession
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.ClassID,
		&i.Date,
		&i.Type,
		&i.ScheduleSlotID,
		&i.OpenedBy,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, school_id, academic_year_id, class_id, date, type, schedule_slot_id, opened_by, status, created_at FROM attendance_sessions WHERE id = $1 AND school_id = $2
`

type GetSessionByIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) GetSessionByID(ctx context.Context, arg GetSessionByIDParams) (AttendanceSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, arg.ID, arg.SchoolID)
	var i AttendanceSession
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.ClassID,
		&i.Date,
		&i.Type,
		&i.ScheduleSlotID,
		&i.OpenedBy,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionBySlotDate = `-- name: GetSessionBySlotDate :one
SELECT id, school_id, academic_year_id, class_id, date, type, schedule_slot_id, opened_by, status, created_at FROM attendance_sessions
WHERE school_id = $1 AND schedule_slot_id = $2 AND date = $3 AND type = 'subject'
`

type GetSessionBySlotDateParams struct {
	SchoolID       int64       `json:"school_id"`
	ScheduleSlotID pgtype.Int8 `json:"schedule_slot_id"`
	Date           pgtype.Date `json:"date"`
}

func (q *Queries) GetSessionBySlotDate(ctx context.Context, arg GetSessionBySlotDateParams) (AttendanceSession, error) {
	row := q.db.QueryRow(ctx, getSessionBySlotDate, arg.SchoolID, arg.ScheduleSlotID, arg.Date)
	var i AttendanceSession
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.ClassID,
		&i.Date,
		&i.Type,
		&i.ScheduleSlotID,
		&i.OpenedBy,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionDetail = `-- name: GetSessionDetail :one
SELECT s.id, s.school_id, s.academic_year_id, s.class_id, s.date, s.type, s.schedule_slot_id, s.opened_by, s.status, s.created_at, c.name AS class_name, u.name AS opened_by_name
FROM attendance_sessions s
JOIN classes c ON c.id = s.class_id
JOIN users u ON u.id = s.opened_by
WHERE s.id = $1 AND s.school_id = $2
`

type GetSessionDetailParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetSessionDetailRow struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	AcademicYearID int64              `json:"academic_year_id"`
	ClassID        int64              `json:"class_id"`
	Date           pgtype.Date        `json:"date"`
	Type           string             `json:"type"`
	ScheduleSlotID pgtype.Int8        `json:"schedule_slot_id"`
	OpenedBy       int64              `json:"opened_by"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ClassName      string             `json:"class_name"`
	OpenedByName   string             `json:"opened_by_name"`
}

func (q *Queries) GetSessionDetail(ctx context.Context, arg GetSessionDetailParams) (GetSessionDetailRow, error) {
	row := q.db.QueryRow(ctx, getSessionDetail, arg.ID, arg.SchoolID)
	var i GetSessionDetailRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.ClassID,
		&i.Date,
		&i.Type,
		&i.ScheduleSlotID,
		&i.OpenedBy,
		&i.Status,
		&i.CreatedAt,
		&i.ClassName,
		&i.OpenedByName,
	)
	return i, err
}

const getStudentBasicByID = `-- name: GetStudentBasicByID :one

SELECT id, name, nis FROM students WHERE id = $1 AND school_id = $2
`

type GetStudentBasicByIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetStudentBasicByIDRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Nis  string `json:"nis"`
}

// -- QR kartu siswa (Fase 8, docs/05-attendance.md "QR kartu siswa") — token
// -- acak per siswa di tabel student_qr_tokens (dimiliki modul attendance,
// -- migrations/00009_student_qr.sql). Join read-only ke students/enrollments
// -- (dimiliki modul student) sama seperti join lain di file ini.
func (q *Queries) GetStudentBasicByID(ctx context.Context, arg GetStudentBasicByIDParams) (GetStudentBasicByIDRow, error) {
	row := q.db.QueryRow(ctx, getStudentBasicByID, arg.ID, arg.SchoolID)
	var i GetStudentBasicByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Nis)
	return i, err
}

const insertAttendanceRecordWithMeta = `-- name: InsertAttendanceRecordWithMeta :one

INSERT INTO attendance_records (school_id, session_id, student_id, status, method, marked_by, meta)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, school_id, session_id, student_id, status, method, marked_by, marked_at, meta, note
`

type InsertAttendanceRecordWithMetaParams struct {
	SchoolID  int64  `json:"school_id"`
	SessionID int64  `json:"session_id"`
	StudentID int64  `json:"student_id"`
	Status    string `json:"status"`
	Method    string `json:"method"`
	MarkedBy  int64  `json:"marked_by"`
	Meta      []byte `json:"meta"`
}

// -- record dengan meta (Fase 8: scan QR & self check-in) — beda dari
// -- UpsertRecord/BulkUpsertRecords (dipakai input manual guru, selalu
// -- menang/replace): ini INSERT MURNI supaya konflik (session_id,student_id)
// -- terdeteksi lewat unique violation -> Service menerjemahkannya jadi
// -- "already_marked" (QR scan) atau "sudah check-in" (self check-in) — record
// -- yang SUDAH ada TIDAK PERNAH didowngrade oleh baris ini.
func (q *Queries) InsertAttendanceRecordWithMeta(ctx context.Context, arg InsertAttendanceRecordWithMetaParams) (AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, insertAttendanceRecordWithMeta,
		arg.SchoolID,
		arg.SessionID,
		arg.StudentID,
		arg.Status,
		arg.Method,
		arg.MarkedBy,
		arg.Meta,
	)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.SessionID,
		&i.StudentID,
		&i.Status,
		&i.Method,
		&i.MarkedBy,
		&i.MarkedAt,
		&i.Meta,
		&i.Note,
	)
	return i, err
}

const insertQRToken = `-- name: InsertQRToken :one
INSERT INTO student_qr_tokens (school_id, student_id, token)
VALUES ($1, $2, $3)
RETURNING id, school_id, student_id, token, created_at, revoked_at
`

type InsertQRTokenParams struct {
	SchoolID  int64  `json:"school_id"`
	StudentID int64  `json:"student_id"`
	Token     string `json:"token"`
}

func (q *Queries) InsertQRToken(ctx context.Context, arg InsertQRTokenParams) (StudentQrToken, error) {
	row := q.db.QueryRow(ctx, insertQRToken, arg.SchoolID, arg.StudentID, arg.Token)
	var i StudentQrToken
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.StudentID,
		&i.Token,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listClassStudents = `-- name: ListClassStudents :many
SELECT s.id, s.name, s.nis
FROM students s
JOIN enrollments e ON e.student_id = s.id
WHERE e.class_id = $1 AND s.school_id = $2
ORDER BY s.name
`

type ListClassStudentsParams struct {
	ClassID  int64 `json:"class_id"`
	SchoolID int64 `json:"school_id"`
}

type ListClassStudentsRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Nis  string `json:"nis"`
}

func (q *Queries) ListClassStudents(ctx context.Context, arg ListClassStudentsParams) ([]ListClassStudentsRow, error) {
	rows, err := q.db.Query(ctx, listClassStudents, arg.ClassID, arg.SchoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassStudentsRow
	for rows.Next() {
		var i ListClassStudentsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Nis); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassStudentsWithActiveToken = `-- name: ListClassStudentsWithActiveToken :many
SELECT s.id, s.name, s.nis, t.token AS token
FROM students s
JOIN enrollments e ON e.student_id = s.id
LEFT JOIN student_qr_tokens t ON t.student_id = s.id AND t.revoked_at IS NULL
WHERE e.class_id = $1 AND s.school_id = $2
ORDER BY s.name
`

type ListClassStudentsWithActiveTokenParams struct {
	ClassID  int64 `json:"class_id"`
	SchoolID int64 `json:"school_id"`
}

type ListClassStudentsWithActiveTokenRow struct {
	ID    int64       `json:"id"`
	Name  string      `json:"name"`
	Nis   string      `json:"nis"`
	Token pgtype.Text `json:"token"`
}

func (q *Queries) ListClassStudentsWithActiveToken(ctx context.Context, arg ListClassStudentsWithActiveTokenParams) ([]ListClassStudentsWithActiveTokenRow, error) {
	rows, err := q.db.Query(ctx, listClassStudentsWithActiveToken, arg.ClassID, arg.SchoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassStudentsWithActiveTokenRow
	for rows.Next() {
		var i ListClassStudentsWithActiveTokenRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Nis,
			&i.Token,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassesForDate = `-- name: ListClassesForDate :many

SELECT
    c.id, c.name,
    COUNT(DISTINCT e.student_id) AS student_count,
    s.id AS session_id,
    s.status AS session_status,
    (SELECT COUNT(*) FROM attendance_records r WHERE r.session_id = s.id) AS marked_count
FROM classes c
LEFT JOIN enrollments e ON e.class_id = c.id
LEFT JOIN attendance_sessions s
    ON s.class_id = c.id AND s.date = $1::date AND s.type = 'daily' AND s.school_id = $2::bigint
WHERE c.school_id = $2::bigint AND c.academic_year_id = $3::bigint
GROUP BY c.id, s.id, s.status
ORDER BY c.name
`

type ListClassesForDateParams struct {
	Date           pgtype.Date `json:"date"`
	SchoolID       int64       `json:"school_id"`
	AcademicYearID int64       `json:"academic_year_id"`
}

type ListClassesForDateRow struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	StudentCount  int64       `json:"student_count"`
	SessionID     pgtype.Int8 `json:"session_id"`
	SessionStatus pgtype.Text `json:"session_status"`
	MarkedCount   int64       `json:"marked_count"`
}

// Query modul attendance (sqlc). Semua query tenant-scoped WAJIB filter
// school_id. Catatan: join read-only ke classes/enrollments/students
// (dimiliki modul student) dan users (dimiliki modul identity) dipakai untuk
// menampilkan nama rombel/siswa/pembuka sesi tanpa N+1 call lintas modul —
// pola yang sama dengan internal/student/queries.sql (join ke users/teachers).
// Semua TULIS ke tabel modul lain (classes, students, dst) tetap TIDAK PERNAH
// dilakukan di sini. Object-level access check (ortu/siswa) tetap lewat
// consumer-side interface StudentAccess (lihat service.go), bukan query SQL.
func (q *Queries) ListClassesForDate(ctx context.Context, arg ListClassesForDateParams) ([]ListClassesForDateRow, error) {
	rows, err := q.db.Query(ctx, listClassesForDate, arg.Date, arg.SchoolID, arg.AcademicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassesForDateRow
	for rows.Next() {
		var i ListClassesForDateRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StudentCount,
			&i.SessionID,
			&i.SessionStatus,
			&i.MarkedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionRecords = `-- name: ListSessionRecords :many
SELECT student_id, status, method, note, marked_at FROM attendance_records WHERE session_id = $1
`

type ListSessionRecordsRow struct {
	StudentID int64              `json:"student_id"`
	Status    string             `json:"status"`
	Method    string             `json:"method"`
	Note      pgtype.Text        `json:"note"`
	MarkedAt  pgtype.Timestamptz `json:"marked_at"`
}

func (q *Queries) ListSessionRecords(ctx context.Context, sessionID int64) ([]ListSessionRecordsRow, error) {
	rows, err := q.db.Query(ctx, listSessionRecords, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionRecordsRow
	for rows.Next() {
		var i ListSessionRecordsRow
		if err := rows.Scan(
			&i.StudentID,
			&i.Status,
			&i.Method,
			&i.Note,
			&i.MarkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlyAttendanceRecords = `-- name: MonthlyAttendanceRecords :many
SELECT
    c.id AS class_id, c.name AS class_name,
    s2.id AS student_id, s2.name AS student_name, s2.nis AS student_nis,
    ses.date AS date, r.status AS status
FROM classes c
JOIN enrollments e ON e.class_id = c.id
JOIN students s2 ON s2.id = e.student_id
LEFT JOIN attendance_sessions ses
    ON ses.class_id = c.id AND ses.type = 'daily' AND ses.school_id = $1::bigint
   AND ses.date >= $2::date AND ses.date <= $3::date
LEFT JOIN attendance_records r ON r.session_id = ses.id AND r.student_id = s2.id
WHERE c.school_id = $1::bigint AND c.academic_year_id = $4::bigint
  AND ($5::bigint IS NULL OR c.id = $5::bigint)
ORDER BY c.name, s2.name, ses.date
`

type MonthlyAttendanceRecordsParams struct {
	SchoolID       int64       `json:"school_id"`
	FromDate       pgtype.Date `json:"from_date"`
	ToDate         pgtype.Date `json:"to_date"`
	AcademicYearID int64       `json:"academic_year_id"`
	ClassID        pgtype.Int8 `json:"class_id"`
}

type MonthlyAttendanceRecordsRow struct {
	ClassID     int64       `json:"class_id"`
	ClassName   string      `json:"class_name"`
	StudentID   int64       `json:"student_id"`
	StudentName string      `json:"student_name"`
	StudentNis  string      `json:"student_nis"`
	Date        pgtype.Date `json:"date"`
	Status      pgtype.Text `json:"status"`
}

// Dipakai export Excel bulanan (Fase 11, GET /api/attendance/export): satu
// baris per (siswa, tanggal sesi daily) dalam rentang [from_date,to_date].
// LEFT JOIN sessions/records (bukan INNER) supaya siswa TETAP muncul sekali
// walau sekolah belum pernah buka sesi absen sama sekali bulan itu (date/status
// akan NULL, ditangani di Go — lihat internal/attendance/export.go).
func (q *Queries) MonthlyAttendanceRecords(ctx context.Context, arg MonthlyAttendanceRecordsParams) ([]MonthlyAttendanceRecordsRow, error) {
	rows, err := q.db.Query(ctx, monthlyAttendanceRecords,
		arg.SchoolID,
		arg.FromDate,
		arg.ToDate,
		arg.AcademicYearID,
		arg.ClassID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyAttendanceRecordsRow
	for rows.Next() {
		var i MonthlyAttendanceRecordsRow
		if err := rows.Scan(
			&i.ClassID,
			&i.ClassName,
			&i.StudentID,
			&i.StudentName,
			&i.StudentNis,
			&i.Date,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeActiveQRToken = `-- name: RevokeActiveQRToken :exec
UPDATE student_qr_tokens SET revoked_at = now()
WHERE student_id = $1 AND school_id = $2 AND revoked_at IS NULL
`

type RevokeActiveQRTokenParams struct {
	StudentID int64 `json:"student_id"`
	SchoolID  int64 `json:"school_id"`
}

func (q *Queries) RevokeActiveQRToken(ctx context.Context, arg RevokeActiveQRTokenParams) error {
	_, err := q.db.Exec(ctx, revokeActiveQRToken, arg.StudentID, arg.SchoolID)
	return err
}

const selfCheckinRecordsForDate = `-- name: SelfCheckinRecordsForDate :many

SELECT r.student_id, st.name AS student_name, c.name AS class_name, r.meta
FROM attendance_records r
JOIN attendance_sessions s ON s.id = r.session_id
JOIN students st ON st.id = r.student_id
JOIN classes c ON c.id = s.class_id
WHERE s.school_id = $1::bigint AND s.date = $2::date AND s.type = 'daily'
  AND r.method = 'self_checkin'
  AND ($3::bigint IS NULL OR s.class_id = $3::bigint)
ORDER BY st.name
`

type SelfCheckinRecordsForDateParams struct {
	SchoolID int64       `json:"school_id"`
	Date     pgtype.Date `json:"date"`
	ClassID  pgtype.Int8 `json:"class_id"`
}

type SelfCheckinRecordsForDateRow struct {
	StudentID   int64  `json:"student_id"`
	StudentName string `json:"student_name"`
	ClassName   string `json:"class_name"`
	Meta        []byte `json:"meta"`
}

// -- anomali self check-in (Fase 8, docs/05: "alat bantu deteksi", BUKAN
// -- anti-curang — keputusan akhir tetap guru/wali kelas via override manual).
func (q *Queries) SelfCheckinRecordsForDate(ctx context.Context, arg SelfCheckinRecordsForDateParams) ([]SelfCheckinRecordsForDateRow, error) {
	rows, err := q.db.Query(ctx, selfCheckinRecordsForDate, arg.SchoolID, arg.Date, arg.ClassID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelfCheckinRecordsForDateRow
	for rows.Next() {
		var i SelfCheckinRecordsForDateRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentName,
			&i.ClassName,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const studentAttendanceCounts = `-- name: StudentAttendanceCounts :one
SELECT
    COUNT(*) FILTER (WHERE r.status = 'hadir')     AS hadir,
    COUNT(*) FILTER (WHERE r.status = 'terlambat') AS terlambat,
    COUNT(*) FILTER (WHERE r.status = 'izin')      AS izin,
    COUNT(*) FILTER (WHERE r.status = 'sakit')     AS sakit,
    COUNT(*) FILTER (WHERE r.status = 'alpa')      AS alpa
FROM attendance_records r
JOIN attendance_sessions s ON s.id = r.session_id
WHERE r.student_id = $1::bigint AND r.school_id = $2::bigint
  AND s.date >= $3::date AND s.date <= $4::date
`

type StudentAttendanceCountsParams struct {
	StudentID int64       `json:"student_id"`
	SchoolID  int64       `json:"school_id"`
	FromDate  pgtype.Date `json:"from_date"`
	ToDate    pgtype.Date `json:"to_date"`
}

type StudentAttendanceCountsRow struct {
	Hadir     int64 `json:"hadir"`
	Terlambat int64 `json:"terlambat"`
	Izin      int64 `json:"izin"`
	Sakit     int64 `json:"sakit"`
	Alpa      int64 `json:"alpa"`
}

func (q *Queries) StudentAttendanceCounts(ctx context.Context, arg StudentAttendanceCountsParams) (StudentAttendanceCountsRow, error) {
	row := q.db.QueryRow(ctx, studentAttendanceCounts,
		arg.StudentID,
		arg.SchoolID,
		arg.FromDate,
		arg.ToDate,
	)
	var i StudentAttendanceCountsRow
	err := row.Scan(
		&i.Hadir,
		&i.Terlambat,
		&i.Izin,
		&i.Sakit,
		&i.Alpa,
	)
	return i, err
}

const studentAttendanceHistory = `-- name: StudentAttendanceHistory :many
SELECT s.date, r.status, r.note
FROM attendance_records r
JOIN attendance_sessions s ON s.id = r.session_id
WHERE r.student_id = $1::bigint AND r.school_id = $2::bigint
  AND s.date >= $3::date AND s.date <= $4::date
ORDER BY s.date DESC
LIMIT 200
`

type StudentAttendanceHistoryParams struct {
	StudentID int64       `json:"student_id"`
	SchoolID  int64       `json:"school_id"`
	FromDate  pgtype.Date `json:"from_date"`
	ToDate    pgtype.Date `json:"to_date"`
}

type StudentAttendanceHistoryRow struct {
	Date   pgtype.Date `json:"date"`
	Status string      `json:"status"`
	Note   pgtype.Text `json:"note"`
}

func (q *Queries) StudentAttendanceHistory(ctx context.Context, arg StudentAttendanceHistoryParams) ([]StudentAttendanceHistoryRow, error) {
	rows, err := q.db.Query(ctx, studentAttendanceHistory,
		arg.StudentID,
		arg.SchoolID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentAttendanceHistoryRow
	for rows.Next() {
		var i StudentAttendanceHistoryRow
		if err := rows.Scan(&i.Date, &i.Status, &i.Note); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const studentCalendarRecords = `-- name: StudentCalendarRecords :many
SELECT s.date, s.type, r.status, r.note
FROM attendance_records r
JOIN attendance_sessions s ON s.id = r.session_id
WHERE r.student_id = $1::bigint AND r.school_id = $2::bigint
  AND s.date >= $3::date AND s.date <= $4::date
ORDER BY s.date, s.type
`

type StudentCalendarRecordsParams struct {
	StudentID int64       `json:"student_id"`
	SchoolID  int64       `json:"school_id"`
	FromDate  pgtype.Date `json:"from_date"`
	ToDate    pgtype.Date `json:"to_date"`
}

type StudentCalendarRecordsRow struct {
	Date   pgtype.Date `json:"date"`
	Type   string      `json:"type"`
	Status string      `json:"status"`
	Note   pgtype.Text `json:"note"`
}

// Dipakai GET /api/students/{id}/attendance/calendar (Fase 14 Gelombang D,
// docs/12-sion-parity.md) — SEMUA record (daily+subject) dalam rentang bulan,
// s.type disertakan supaya Service bisa memprioritaskan sesi daily &
// menghitung status "terburuk" dari subject records saat daily tidak ada
// (lihat internal/attendance/service.go resolveDayStatus).
func (q *Queries) StudentCalendarRecords(ctx context.Context, arg StudentCalendarRecordsParams) ([]StudentCalendarRecordsRow, error) {
	rows, err := q.db.Query(ctx, studentCalendarRecords,
		arg.StudentID,
		arg.SchoolID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentCalendarRecordsRow
	for rows.Next() {
		var i StudentCalendarRecordsRow
		if err := rows.Scan(
			&i.Date,
			&i.Type,
			&i.Status,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryByDate = `-- name: SummaryByDate :many
SELECT
    c.id AS class_id,
    c.name AS class_name,
    COUNT(DISTINCT e.student_id) AS total,
    COUNT(*) FILTER (WHERE r.status = 'hadir')     AS hadir,
    COUNT(*) FILTER (WHERE r.status = 'terlambat') AS terlambat,
    COUNT(*) FILTER (WHERE r.status = 'izin')      AS izin,
    COUNT(*) FILTER (WHERE r.status = 'sakit')     AS sakit,
    COUNT(*) FILTER (WHERE r.status = 'alpa')      AS alpa,
    COALESCE(s.status, '')::text AS session_status
FROM classes c
LEFT JOIN enrollments e ON e.class_id = c.id
LEFT JOIN attendance_sessions s
    ON s.class_id = c.id AND s.date = $1::date AND s.type = 'daily' AND s.school_id = $2::bigint
LEFT JOIN attendance_records r ON r.session_id = s.id AND r.student_id = e.student_id
WHERE c.school_id = $2::bigint AND c.academic_year_id = $3::bigint
  AND ($4::bigint IS NULL OR c.id = $4::bigint)
GROUP BY c.id, s.status
ORDER BY c.name
`

type SummaryByDateParams struct {
	Date           pgtype.Date `json:"date"`
	SchoolID       int64       `json:"school_id"`
	AcademicYearID int64       `json:"academic_year_id"`
	ClassID        pgtype.Int8 `json:"class_id"`
}

type SummaryByDateRow struct {
	ClassID       int64  `json:"class_id"`
	ClassName     string `json:"class_name"`
	Total         int64  `json:"total"`
	Hadir         int64  `json:"hadir"`
	Terlambat     int64  `json:"terlambat"`
	Izin          int64  `json:"izin"`
	Sakit         int64  `json:"sakit"`
	Alpa          int64  `json:"alpa"`
	SessionStatus string `json:"session_status"`
}

func (q *Queries) SummaryByDate(ctx context.Context, arg SummaryByDateParams) ([]SummaryByDateRow, error) {
	rows, err := q.db.Query(ctx, summaryByDate,
		arg.Date,
		arg.SchoolID,
		arg.AcademicYearID,
		arg.ClassID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryByDateRow
	for rows.Next() {
		var i SummaryByDateRow
		if err := rows.Scan(
			&i.ClassID,
			&i.ClassName,
			&i.Total,
			&i.Hadir,
			&i.Terlambat,
			&i.Izin,
			&i.Sakit,
			&i.Alpa,
			&i.SessionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRecord = `-- name: UpsertRecord :one
INSERT INTO attendance_records (school_id, session_id, student_id, status, method, marked_by, note)
VALUES ($1, $2, $3, $4, $5, $6, $7::text)
ON CONFLICT (session_id, student_id) DO UPDATE SET
    status     = EXCLUDED.status,
    method     = EXCLUDED.method,
    marked_by  = EXCLUDED.marked_by,
    marked_at  = now(),
    note       = EXCLUDED.note
RETURNING id, school_id, session_id, student_id, status, method, marked_by, marked_at, meta, note
`

type UpsertRecordParams struct {
	SchoolID  int64       `json:"school_id"`
	SessionID int64       `json:"session_id"`
	StudentID int64       `json:"student_id"`
	Status    string      `json:"status"`
	Method    string      `json:"method"`
	MarkedBy  int64       `json:"marked_by"`
	Note      pgtype.Text `json:"note"`
}

func (q *Queries) UpsertRecord(ctx context.Context, arg UpsertRecordParams) (AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, upsertRecord,
		arg.SchoolID,
		arg.SessionID,
		arg.StudentID,
		arg.Status,
		arg.Method,
		arg.MarkedBy,
		arg.Note,
	)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.SessionID,
		&i.StudentID,
		&i.Status,
		&i.Method,
		&i.MarkedBy,
		&i.MarkedAt,
		&i.Meta,
		&i.Note,
	)
	return i, err
}
