// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package teachingdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const endJournal = `-- name: EndJournal :one
UPDATE teaching_journals SET ended_at = $3 WHERE id = $1 AND school_id = $2 RETURNING id, school_id, teacher_id, schedule_slot_id, class_id, subject_id, room_id, date, started_at, ended_at, material, note, flags
`

type EndJournalParams struct {
	ID       int64              `json:"id"`
	SchoolID int64              `json:"school_id"`
	EndedAt  pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) EndJournal(ctx context.Context, arg EndJournalParams) (TeachingJournal, error) {
	row := q.db.QueryRow(ctx, endJournal, arg.ID, arg.SchoolID, arg.EndedAt)
	var i TeachingJournal
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.TeacherID,
		&i.ScheduleSlotID,
		&i.ClassID,
		&i.SubjectID,
		&i.RoomID,
		&i.Date,
		&i.StartedAt,
		&i.EndedAt,
		&i.Material,
		&i.Note,
		&i.Flags,
	)
	return i, err
}

const getJournalByID = `-- name: GetJournalByID :one
SELECT id, school_id, teacher_id, schedule_slot_id, class_id, subject_id, room_id, date, started_at, ended_at, material, note, flags FROM teaching_journals WHERE id = $1 AND school_id = $2
`

type GetJournalByIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) GetJournalByID(ctx context.Context, arg GetJournalByIDParams) (TeachingJournal, error) {
	row := q.db.QueryRow(ctx, getJournalByID, arg.ID, arg.SchoolID)
	var i TeachingJournal
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.TeacherID,
		&i.ScheduleSlotID,
		&i.ClassID,
		&i.SubjectID,
		&i.RoomID,
		&i.Date,
		&i.StartedAt,
		&i.EndedAt,
		&i.Material,
		&i.Note,
		&i.Flags,
	)
	return i, err
}

const getJournalBySlotDate = `-- name: GetJournalBySlotDate :one
SELECT id, school_id, teacher_id, schedule_slot_id, class_id, subject_id, room_id, date, started_at, ended_at, material, note, flags FROM teaching_journals WHERE school_id = $1 AND schedule_slot_id = $2 AND date = $3
`

type GetJournalBySlotDateParams struct {
	SchoolID       int64       `json:"school_id"`
	ScheduleSlotID pgtype.Int8 `json:"schedule_slot_id"`
	Date           pgtype.Date `json:"date"`
}

func (q *Queries) GetJournalBySlotDate(ctx context.Context, arg GetJournalBySlotDateParams) (TeachingJournal, error) {
	row := q.db.QueryRow(ctx, getJournalBySlotDate, arg.SchoolID, arg.ScheduleSlotID, arg.Date)
	var i TeachingJournal
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.TeacherID,
		&i.ScheduleSlotID,
		&i.ClassID,
		&i.SubjectID,
		&i.RoomID,
		&i.Date,
		&i.StartedAt,
		&i.EndedAt,
		&i.Material,
		&i.Note,
		&i.Flags,
	)
	return i, err
}

const getJournalRow = `-- name: GetJournalRow :one
SELECT
    j.id, j.school_id, j.teacher_id, j.schedule_slot_id, j.class_id, j.subject_id, j.room_id, j.date, j.started_at, j.ended_at, j.material, j.note, j.flags,
    t.user_id AS teacher_user_id,
    u.name AS teacher_name,
    c.name AS class_name,
    sub.code AS subject_code,
    sub.name AS subject_name,
    r.name AS room_name
FROM teaching_journals j
JOIN teachers t ON t.id = j.teacher_id
JOIN users u ON u.id = t.user_id
JOIN classes c ON c.id = j.class_id
LEFT JOIN subjects sub ON sub.id = j.subject_id
LEFT JOIN rooms r ON r.id = j.room_id
WHERE j.id = $1 AND j.school_id = $2
`

type GetJournalRowParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetJournalRowRow struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	TeacherID      int64              `json:"teacher_id"`
	ScheduleSlotID pgtype.Int8        `json:"schedule_slot_id"`
	ClassID        int64              `json:"class_id"`
	SubjectID      pgtype.Int8        `json:"subject_id"`
	RoomID         pgtype.Int8        `json:"room_id"`
	Date           pgtype.Date        `json:"date"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	EndedAt        pgtype.Timestamptz `json:"ended_at"`
	Material       pgtype.Text        `json:"material"`
	Note           pgtype.Text        `json:"note"`
	Flags          []string           `json:"flags"`
	TeacherUserID  int64              `json:"teacher_user_id"`
	TeacherName    string             `json:"teacher_name"`
	ClassName      string             `json:"class_name"`
	SubjectCode    pgtype.Text        `json:"subject_code"`
	SubjectName    pgtype.Text        `json:"subject_name"`
	RoomName       pgtype.Text        `json:"room_name"`
}

func (q *Queries) GetJournalRow(ctx context.Context, arg GetJournalRowParams) (GetJournalRowRow, error) {
	row := q.db.QueryRow(ctx, getJournalRow, arg.ID, arg.SchoolID)
	var i GetJournalRowRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.TeacherID,
		&i.ScheduleSlotID,
		&i.ClassID,
		&i.SubjectID,
		&i.RoomID,
		&i.Date,
		&i.StartedAt,
		&i.EndedAt,
		&i.Material,
		&i.Note,
		&i.Flags,
		&i.TeacherUserID,
		&i.TeacherName,
		&i.ClassName,
		&i.SubjectCode,
		&i.SubjectName,
		&i.RoomName,
	)
	return i, err
}

const getTeachingSettingsRaw = `-- name: GetTeachingSettingsRaw :one

SELECT settings FROM school_settings WHERE school_id = $1 AND module = 'teaching'
`

// -- settings (dibaca langsung dari school_settings module='teaching' —
// -- tabel & pola yang sama dipakai GET/PUT /api/settings/teaching lewat
// -- tenant.SettingsService; ini hanya baca untuk kebutuhan aturan bisnis
// -- internal, mis. not_started_after_min — lihat CLAUDE.md "satu pola settings").
func (q *Queries) GetTeachingSettingsRaw(ctx context.Context, schoolID int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getTeachingSettingsRaw, schoolID)
	var settings []byte
	err := row.Scan(&settings)
	return settings, err
}

const insertJournal = `-- name: InsertJournal :one

INSERT INTO teaching_journals (school_id, teacher_id, schedule_slot_id, class_id, subject_id, room_id, date, started_at, flags)
VALUES (
    $1::bigint,
    $2::bigint,
    $3::bigint,
    $4::bigint,
    $5::bigint,
    $6::bigint,
    $7::date,
    $8::timestamptz,
    $9::text[]
)
RETURNING id, school_id, teacher_id, schedule_slot_id, class_id, subject_id, room_id, date, started_at, ended_at, material, note, flags
`

type InsertJournalParams struct {
	SchoolID       int64              `json:"school_id"`
	TeacherID      int64              `json:"teacher_id"`
	ScheduleSlotID pgtype.Int8        `json:"schedule_slot_id"`
	ClassID        int64              `json:"class_id"`
	SubjectID      pgtype.Int8        `json:"subject_id"`
	RoomID         pgtype.Int8        `json:"room_id"`
	Date           pgtype.Date        `json:"date"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	Flags          []string           `json:"flags"`
}

// Query modul teaching (sqlc). Semua query tenant-scoped WAJIB filter
// school_id. Catatan: join read-only ke teachers/users (dimiliki modul
// identity/student), classes/subjects/rooms (dimiliki modul
// student/schedule) dipakai untuk menampilkan nama tanpa N+1 call lintas
// modul — pola yang sama dengan internal/attendance/queries.sql &
// internal/schedule/queries.sql. Semua TULIS ke tabel modul lain tetap TIDAK
// PERNAH dilakukan di sini.
func (q *Queries) InsertJournal(ctx context.Context, arg InsertJournalParams) (TeachingJournal, error) {
	row := q.db.QueryRow(ctx, insertJournal,
		arg.SchoolID,
		arg.TeacherID,
		arg.ScheduleSlotID,
		arg.ClassID,
		arg.SubjectID,
		arg.RoomID,
		arg.Date,
		arg.StartedAt,
		arg.Flags,
	)
	var i TeachingJournal
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.TeacherID,
		&i.ScheduleSlotID,
		&i.ClassID,
		&i.SubjectID,
		&i.RoomID,
		&i.Date,
		&i.StartedAt,
		&i.EndedAt,
		&i.Material,
		&i.Note,
		&i.Flags,
	)
	return i, err
}

const listJournalsRow = `-- name: ListJournalsRow :many
SELECT
    j.id, j.school_id, j.teacher_id, j.schedule_slot_id, j.class_id, j.subject_id, j.room_id, j.date, j.started_at, j.ended_at, j.material, j.note, j.flags,
    t.user_id AS teacher_user_id,
    u.name AS teacher_name,
    c.name AS class_name,
    sub.code AS subject_code,
    sub.name AS subject_name,
    r.name AS room_name
FROM teaching_journals j
JOIN teachers t ON t.id = j.teacher_id
JOIN users u ON u.id = t.user_id
JOIN classes c ON c.id = j.class_id
LEFT JOIN subjects sub ON sub.id = j.subject_id
LEFT JOIN rooms r ON r.id = j.room_id
WHERE j.school_id = $1::bigint
  AND ($2::bigint IS NULL OR j.teacher_id = $2::bigint)
  AND ($3::date IS NULL OR j.date = $3::date)
  AND ($4::date IS NULL OR (j.date >= $4::date AND j.date < $5::date))
ORDER BY j.started_at DESC
LIMIT 100
`

type ListJournalsRowParams struct {
	SchoolID   int64       `json:"school_id"`
	TeacherID  pgtype.Int8 `json:"teacher_id"`
	Date       pgtype.Date `json:"date"`
	MonthStart pgtype.Date `json:"month_start"`
	MonthEnd   pgtype.Date `json:"month_end"`
}

type ListJournalsRowRow struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	TeacherID      int64              `json:"teacher_id"`
	ScheduleSlotID pgtype.Int8        `json:"schedule_slot_id"`
	ClassID        int64              `json:"class_id"`
	SubjectID      pgtype.Int8        `json:"subject_id"`
	RoomID         pgtype.Int8        `json:"room_id"`
	Date           pgtype.Date        `json:"date"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	EndedAt        pgtype.Timestamptz `json:"ended_at"`
	Material       pgtype.Text        `json:"material"`
	Note           pgtype.Text        `json:"note"`
	Flags          []string           `json:"flags"`
	TeacherUserID  int64              `json:"teacher_user_id"`
	TeacherName    string             `json:"teacher_name"`
	ClassName      string             `json:"class_name"`
	SubjectCode    pgtype.Text        `json:"subject_code"`
	SubjectName    pgtype.Text        `json:"subject_name"`
	RoomName       pgtype.Text        `json:"room_name"`
}

func (q *Queries) ListJournalsRow(ctx context.Context, arg ListJournalsRowParams) ([]ListJournalsRowRow, error) {
	rows, err := q.db.Query(ctx, listJournalsRow,
		arg.SchoolID,
		arg.TeacherID,
		arg.Date,
		arg.MonthStart,
		arg.MonthEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJournalsRowRow
	for rows.Next() {
		var i ListJournalsRowRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.TeacherID,
			&i.ScheduleSlotID,
			&i.ClassID,
			&i.SubjectID,
			&i.RoomID,
			&i.Date,
			&i.StartedAt,
			&i.EndedAt,
			&i.Material,
			&i.Note,
			&i.Flags,
			&i.TeacherUserID,
			&i.TeacherName,
			&i.ClassName,
			&i.SubjectCode,
			&i.SubjectName,
			&i.RoomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupClassRef = `-- name: LookupClassRef :one
SELECT id, name FROM classes WHERE school_id = $1 AND id = $2
`

type LookupClassRefParams struct {
	SchoolID int64 `json:"school_id"`
	ID       int64 `json:"id"`
}

type LookupClassRefRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) LookupClassRef(ctx context.Context, arg LookupClassRefParams) (LookupClassRefRow, error) {
	row := q.db.QueryRow(ctx, lookupClassRef, arg.SchoolID, arg.ID)
	var i LookupClassRefRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const lookupRoomByID = `-- name: LookupRoomByID :one
SELECT id, name FROM rooms WHERE school_id = $1 AND id = $2
`

type LookupRoomByIDParams struct {
	SchoolID int64 `json:"school_id"`
	ID       int64 `json:"id"`
}

type LookupRoomByIDRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) LookupRoomByID(ctx context.Context, arg LookupRoomByIDParams) (LookupRoomByIDRow, error) {
	row := q.db.QueryRow(ctx, lookupRoomByID, arg.SchoolID, arg.ID)
	var i LookupRoomByIDRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const lookupRoomByToken = `-- name: LookupRoomByToken :one

SELECT id, name FROM rooms WHERE school_id = $1 AND qr_token = $2
`

type LookupRoomByTokenParams struct {
	SchoolID int64  `json:"school_id"`
	QrToken  string `json:"qr_token"`
}

type LookupRoomByTokenRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// -- referensi lintas modul (READ-ONLY — lihat catatan di atas berkas) --
func (q *Queries) LookupRoomByToken(ctx context.Context, arg LookupRoomByTokenParams) (LookupRoomByTokenRow, error) {
	row := q.db.QueryRow(ctx, lookupRoomByToken, arg.SchoolID, arg.QrToken)
	var i LookupRoomByTokenRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const lookupSubjectRef = `-- name: LookupSubjectRef :one
SELECT id, code, name FROM subjects WHERE school_id = $1 AND id = $2
`

type LookupSubjectRefParams struct {
	SchoolID int64 `json:"school_id"`
	ID       int64 `json:"id"`
}

type LookupSubjectRefRow struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) LookupSubjectRef(ctx context.Context, arg LookupSubjectRefParams) (LookupSubjectRefRow, error) {
	row := q.db.QueryRow(ctx, lookupSubjectRef, arg.SchoolID, arg.ID)
	var i LookupSubjectRefRow
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const lookupTeacherRef = `-- name: LookupTeacherRef :one
SELECT t.id, u.name FROM teachers t JOIN users u ON u.id = t.user_id WHERE t.id = $1 AND t.school_id = $2
`

type LookupTeacherRefParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type LookupTeacherRefRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) LookupTeacherRef(ctx context.Context, arg LookupTeacherRefParams) (LookupTeacherRefRow, error) {
	row := q.db.QueryRow(ctx, lookupTeacherRef, arg.ID, arg.SchoolID)
	var i LookupTeacherRefRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const lookupTeacherUserID = `-- name: LookupTeacherUserID :one
SELECT t.user_id FROM teachers t WHERE t.id = $1 AND t.school_id = $2
`

type LookupTeacherUserIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) LookupTeacherUserID(ctx context.Context, arg LookupTeacherUserIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, lookupTeacherUserID, arg.ID, arg.SchoolID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const updateJournalNote = `-- name: UpdateJournalNote :one
UPDATE teaching_journals SET material = $3, note = $4 WHERE id = $1 AND school_id = $2 RETURNING id, school_id, teacher_id, schedule_slot_id, class_id, subject_id, room_id, date, started_at, ended_at, material, note, flags
`

type UpdateJournalNoteParams struct {
	ID       int64       `json:"id"`
	SchoolID int64       `json:"school_id"`
	Material pgtype.Text `json:"material"`
	Note     pgtype.Text `json:"note"`
}

func (q *Queries) UpdateJournalNote(ctx context.Context, arg UpdateJournalNoteParams) (TeachingJournal, error) {
	row := q.db.QueryRow(ctx, updateJournalNote,
		arg.ID,
		arg.SchoolID,
		arg.Material,
		arg.Note,
	)
	var i TeachingJournal
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.TeacherID,
		&i.ScheduleSlotID,
		&i.ClassID,
		&i.SubjectID,
		&i.RoomID,
		&i.Date,
		&i.StartedAt,
		&i.EndedAt,
		&i.Material,
		&i.Note,
		&i.Flags,
	)
	return i, err
}
