// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package announcementdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAnnouncement = `-- name: DeleteAnnouncement :execrows
DELETE FROM announcements WHERE id = $1 AND school_id = $2
`

type DeleteAnnouncementParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) DeleteAnnouncement(ctx context.Context, arg DeleteAnnouncementParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnnouncement, arg.ID, arg.SchoolID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAnnouncementByID = `-- name: GetAnnouncementByID :one
SELECT id, school_id, title, body, starts_at, ends_at, created_by, created_at FROM announcements WHERE id = $1 AND school_id = $2
`

type GetAnnouncementByIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) GetAnnouncementByID(ctx context.Context, arg GetAnnouncementByIDParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, getAnnouncementByID, arg.ID, arg.SchoolID)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Title,
		&i.Body,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertAnnouncement = `-- name: InsertAnnouncement :one

INSERT INTO announcements (school_id, title, body, starts_at, ends_at, created_by)
VALUES (
    $1::bigint,
    $2::text,
    $3::text,
    $4::date,
    $5::date,
    $6::bigint
)
RETURNING id, school_id, title, body, starts_at, ends_at, created_by, created_at
`

type InsertAnnouncementParams struct {
	SchoolID  int64       `json:"school_id"`
	Title     string      `json:"title"`
	Body      string      `json:"body"`
	StartsAt  pgtype.Date `json:"starts_at"`
	EndsAt    pgtype.Date `json:"ends_at"`
	CreatedBy int64       `json:"created_by"`
}

// Query modul announcement (sqlc). Semua query tenant-scoped WAJIB filter
// school_id (lihat CLAUDE.md aturan multi-tenant).
func (q *Queries) InsertAnnouncement(ctx context.Context, arg InsertAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, insertAnnouncement,
		arg.SchoolID,
		arg.Title,
		arg.Body,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedBy,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Title,
		&i.Body,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveAnnouncements = `-- name: ListActiveAnnouncements :many
SELECT id, school_id, title, body, starts_at, ends_at, created_by, created_at FROM announcements
WHERE school_id = $1 AND starts_at <= $2 AND ends_at >= $2
ORDER BY starts_at DESC, id DESC
`

type ListActiveAnnouncementsParams struct {
	SchoolID int64       `json:"school_id"`
	StartsAt pgtype.Date `json:"starts_at"`
}

func (q *Queries) ListActiveAnnouncements(ctx context.Context, arg ListActiveAnnouncementsParams) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listActiveAnnouncements, arg.SchoolID, arg.StartsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Announcement
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Title,
			&i.Body,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT id, school_id, title, body, starts_at, ends_at, created_by, created_at FROM announcements WHERE school_id = $1 ORDER BY starts_at DESC, id DESC
`

func (q *Queries) ListAnnouncements(ctx context.Context, schoolID int64) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listAnnouncements, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Announcement
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Title,
			&i.Body,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnouncement = `-- name: UpdateAnnouncement :one
UPDATE announcements
SET title = $3, body = $4, starts_at = $5, ends_at = $6
WHERE id = $1 AND school_id = $2
RETURNING id, school_id, title, body, starts_at, ends_at, created_by, created_at
`

type UpdateAnnouncementParams struct {
	ID       int64       `json:"id"`
	SchoolID int64       `json:"school_id"`
	Title    string      `json:"title"`
	Body     string      `json:"body"`
	StartsAt pgtype.Date `json:"starts_at"`
	EndsAt   pgtype.Date `json:"ends_at"`
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, updateAnnouncement,
		arg.ID,
		arg.SchoolID,
		arg.Title,
		arg.Body,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Title,
		&i.Body,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
