// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package identitydb

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogForSchool = `-- name: CountAuditLogForSchool :one
SELECT COUNT(*) FROM audit_log a
WHERE a.school_id = $1::bigint
  AND ($2::text = '' OR a.action LIKE $2::text || '%')
`

type CountAuditLogForSchoolParams struct {
	SchoolID     int64  `json:"school_id"`
	ActionPrefix string `json:"action_prefix"`
}

func (q *Queries) CountAuditLogForSchool(ctx context.Context, arg CountAuditLogForSchoolParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogForSchool, arg.SchoolID, arg.ActionPrefix)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvitation = `-- name: CreateInvitation :one

INSERT INTO invitations (school_id, code, role, target_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, school_id, code, role, target_id, expires_at, used_at
`

type CreateInvitationParams struct {
	SchoolID  int64              `json:"school_id"`
	Code      string             `json:"code"`
	Role      string             `json:"role"`
	TargetID  pgtype.Int8        `json:"target_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// -- invitations --
func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.SchoolID,
		arg.Code,
		arg.Role,
		arg.TargetID,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Code,
		&i.Role,
		&i.TargetID,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (user_id, school_id, role, status)
VALUES ($1, $2, $3, 'active')
ON CONFLICT (user_id, school_id, role) DO UPDATE SET status = 'active'
RETURNING id, user_id, school_id, role, status
`

type CreateMembershipParams struct {
	UserID   int64  `json:"user_id"`
	SchoolID int64  `json:"school_id"`
	Role     string `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.UserID, arg.SchoolID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SchoolID,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, school_id, token_hash, role, expires_at, ip, user_agent, impersonator_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8::bigint)
RETURNING id, user_id, school_id, token_hash, role, expires_at, created_at, ip, user_agent, impersonator_user_id
`

type CreateSessionParams struct {
	UserID             int64              `json:"user_id"`
	SchoolID           pgtype.Int8        `json:"school_id"`
	TokenHash          []byte             `json:"token_hash"`
	Role               string             `json:"role"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	Ip                 *netip.Addr        `json:"ip"`
	UserAgent          pgtype.Text        `json:"user_agent"`
	ImpersonatorUserID pgtype.Int8        `json:"impersonator_user_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.SchoolID,
		arg.TokenHash,
		arg.Role,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
		arg.ImpersonatorUserID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SchoolID,
		&i.TokenHash,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Ip,
		&i.UserAgent,
		&i.ImpersonatorUserID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, password_hash, name, phone, is_super_admin)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, username, password_hash, name, phone, is_super_admin, created_at
`

type CreateUserParams struct {
	Email        pgtype.Text `json:"email"`
	Username     pgtype.Text `json:"username"`
	PasswordHash string      `json:"password_hash"`
	Name         string      `json:"name"`
	Phone        pgtype.Text `json:"phone"`
	IsSuperAdmin bool        `json:"is_super_admin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Name,
		arg.Phone,
		arg.IsSuperAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.IsSuperAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOtherSessionsByUserSchool = `-- name: DeleteOtherSessionsByUserSchool :exec

DELETE FROM sessions WHERE user_id = $1 AND school_id = $2 AND token_hash != $3
`

type DeleteOtherSessionsByUserSchoolParams struct {
	UserID    int64       `json:"user_id"`
	SchoolID  pgtype.Int8 `json:"school_id"`
	TokenHash []byte      `json:"token_hash"`
}

// -- Fase 15 Gap 4, docs/12-sion-parity.md "single-device login" — dipanggil
// Login (service.go) SETELAH sesi baru dibuat, keyed token_hash sesi baru
// itu sendiri (bukan ID — CreateSession tidak mengembalikan ID, lihat
// catatan desain di service.go) supaya sesi yang BARU dibuat TIDAK ikut
// terhapus.
func (q *Queries) DeleteOtherSessionsByUserSchool(ctx context.Context, arg DeleteOtherSessionsByUserSchoolParams) error {
	_, err := q.db.Exec(ctx, deleteOtherSessionsByUserSchool, arg.UserID, arg.SchoolID, arg.TokenHash)
	return err
}

const deleteRolePermissionOverride = `-- name: DeleteRolePermissionOverride :exec
DELETE FROM school_role_permissions WHERE school_id = $1 AND role = $2 AND permission = $3
`

type DeleteRolePermissionOverrideParams struct {
	SchoolID   int64  `json:"school_id"`
	Role       string `json:"role"`
	Permission string `json:"permission"`
}

func (q *Queries) DeleteRolePermissionOverride(ctx context.Context, arg DeleteRolePermissionOverrideParams) error {
	_, err := q.db.Exec(ctx, deleteRolePermissionOverride, arg.SchoolID, arg.Role, arg.Permission)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const deleteSessionsByUser = `-- name: DeleteSessionsByUser :exec

DELETE FROM sessions WHERE user_id = $1
`

// -- fase 13, docs/11-superadmin.md P4 "Operasional" --
// P4.1 (daftar anggota), P4.2 (reset password), P4.3 (audit log viewer) HANYA
// menyentuh tabel milik modul identity sendiri (users/memberships/sessions/
// audit_log) — makanya ditempatkan di sini (perluasan modul existing) alih-
// alih modul agregator baru (lihat catatan keputusan di internal/platformadmin).
// Dipakai AdminResetPassword — hapus SEMUA sesi user target supaya password
// lama langsung tidak berlaku lagi di device manapun.
func (q *Queries) DeleteSessionsByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUser, userID)
	return err
}

const deleteSessionsByUserSchool = `-- name: DeleteSessionsByUserSchool :exec
DELETE FROM sessions WHERE user_id = $1 AND school_id = $2
`

type DeleteSessionsByUserSchoolParams struct {
	UserID   int64       `json:"user_id"`
	SchoolID pgtype.Int8 `json:"school_id"`
}

// Dipakai SetMemberStatus saat menonaktifkan membership — beda dari
// DeleteSessionsByUser (dipakai AdminResetPassword) yang menghapus SEMUA
// sesi user LINTAS SEKOLAH; di sini HANYA sesi user itu DI SEKOLAH INI
// (user bisa punya membership aktif di sekolah lain yang tidak boleh ikut
// kena).
func (q *Queries) DeleteSessionsByUserSchool(ctx context.Context, arg DeleteSessionsByUserSchoolParams) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUserSchool, arg.UserID, arg.SchoolID)
	return err
}

const extendSession = `-- name: ExtendSession :exec
UPDATE sessions SET expires_at = $2 WHERE id = $1
`

type ExtendSessionParams struct {
	ID        int64              `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) error {
	_, err := q.db.Exec(ctx, extendSession, arg.ID, arg.ExpiresAt)
	return err
}

const getActiveInvitationByRoleTarget = `-- name: GetActiveInvitationByRoleTarget :one
SELECT id, school_id, code, role, target_id, expires_at, used_at FROM invitations
WHERE school_id = $1 AND role = $2 AND target_id = $3
  AND used_at IS NULL AND expires_at > $4
ORDER BY id DESC LIMIT 1
`

type GetActiveInvitationByRoleTargetParams struct {
	SchoolID  int64              `json:"school_id"`
	Role      string             `json:"role"`
	TargetID  pgtype.Int8        `json:"target_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Dipakai generator kode undangan supaya idempoten: kode lama yang belum
// terpakai & belum kedaluwarsa dipakai ulang, bukan dibuat baru.
func (q *Queries) GetActiveInvitationByRoleTarget(ctx context.Context, arg GetActiveInvitationByRoleTargetParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, getActiveInvitationByRoleTarget,
		arg.SchoolID,
		arg.Role,
		arg.TargetID,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Code,
		&i.Role,
		&i.TargetID,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getInvitationByCode = `-- name: GetInvitationByCode :one
SELECT id, school_id, code, role, target_id, expires_at, used_at FROM invitations WHERE code = $1
`

func (q *Queries) GetInvitationByCode(ctx context.Context, code string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByCode, code)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Code,
		&i.Role,
		&i.TargetID,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getMembershipByUserSchoolRole = `-- name: GetMembershipByUserSchoolRole :one

SELECT id, user_id, school_id, role, status FROM memberships WHERE user_id = $1 AND school_id = $2 AND role = $3
`

type GetMembershipByUserSchoolRoleParams struct {
	UserID   int64  `json:"user_id"`
	SchoolID int64  `json:"school_id"`
	Role     string `json:"role"`
}

// -- Fase 15 Gap 6, docs/12-sion-parity.md "nonaktifkan/aktifkan user" --
func (q *Queries) GetMembershipByUserSchoolRole(ctx context.Context, arg GetMembershipByUserSchoolRoleParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembershipByUserSchoolRole, arg.UserID, arg.SchoolID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SchoolID,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    s.id, s.user_id, s.school_id, s.token_hash, s.role, s.expires_at, s.created_at, s.ip, s.user_agent,
    s.impersonator_user_id,
    u.name AS user_name,
    u.is_super_admin AS user_is_super_admin
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
`

type GetSessionByTokenHashRow struct {
	ID                 int64              `json:"id"`
	UserID             int64              `json:"user_id"`
	SchoolID           pgtype.Int8        `json:"school_id"`
	TokenHash          []byte             `json:"token_hash"`
	Role               string             `json:"role"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	Ip                 *netip.Addr        `json:"ip"`
	UserAgent          pgtype.Text        `json:"user_agent"`
	ImpersonatorUserID pgtype.Int8        `json:"impersonator_user_id"`
	UserName           string             `json:"user_name"`
	UserIsSuperAdmin   bool               `json:"user_is_super_admin"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SchoolID,
		&i.TokenHash,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Ip,
		&i.UserAgent,
		&i.ImpersonatorUserID,
		&i.UserName,
		&i.UserIsSuperAdmin,
	)
	return i, err
}

const getStudentIDByUser = `-- name: GetStudentIDByUser :one
SELECT id FROM students WHERE user_id = $1 AND school_id = $2
`

type GetStudentIDByUserParams struct {
	UserID   pgtype.Int8 `json:"user_id"`
	SchoolID int64       `json:"school_id"`
}

// Read-only lookup ke tabel students (milik modul student) untuk mengisi
// student_id di /api/me & login response role siswa. Preseden: join read-only
// lintas tabel diperbolehkan (lihat student/queries.sql join ke users).
func (q *Queries) GetStudentIDByUser(ctx context.Context, arg GetStudentIDByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, getStudentIDByUser, arg.UserID, arg.SchoolID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserBasic = `-- name: GetUserBasic :one
SELECT id, name FROM users WHERE id = $1
`

type GetUserBasicRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// Dipakai render field impersonated_by pada GET /api/me (Fase 14 Gelombang D)
// — nama saja, TANPA data sensitif lain.
func (q *Queries) GetUserBasic(ctx context.Context, id int64) (GetUserBasicRow, error) {
	row := q.db.QueryRow(ctx, getUserBasic, id)
	var i GetUserBasicRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, email, username, password_hash, name, phone, is_super_admin, created_at FROM users WHERE email = $1
`

// Query modul identity (sqlc).
func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.IsSuperAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, password_hash, name, phone, is_super_admin, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.IsSuperAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password_hash, name, phone, is_super_admin, created_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.IsSuperAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (school_id, user_id, action, entity, entity_id, old_value, new_value)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditLogParams struct {
	SchoolID pgtype.Int8 `json:"school_id"`
	UserID   pgtype.Int8 `json:"user_id"`
	Action   string      `json:"action"`
	Entity   string      `json:"entity"`
	EntityID pgtype.Int8 `json:"entity_id"`
	OldValue []byte      `json:"old_value"`
	NewValue []byte      `json:"new_value"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.SchoolID,
		arg.UserID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.OldValue,
		arg.NewValue,
	)
	return err
}

const listActiveMembershipsByUserSchool = `-- name: ListActiveMembershipsByUserSchool :many
SELECT id, user_id, school_id, role, status FROM memberships WHERE user_id = $1 AND school_id = $2 AND status = 'active'
`

type ListActiveMembershipsByUserSchoolParams struct {
	UserID   int64 `json:"user_id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) ListActiveMembershipsByUserSchool(ctx context.Context, arg ListActiveMembershipsByUserSchoolParams) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listActiveMembershipsByUserSchool, arg.UserID, arg.SchoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Membership
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SchoolID,
			&i.Role,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogForSchool = `-- name: ListAuditLogForSchool :many
SELECT a.id, u.name AS user_name, a.action, a.entity, a.entity_id, a.at
FROM audit_log a
LEFT JOIN users u ON u.id = a.user_id
WHERE a.school_id = $1::bigint
  AND ($2::text = '' OR a.action LIKE $2::text || '%')
ORDER BY a.at DESC
LIMIT $4::int OFFSET $3::int
`

type ListAuditLogForSchoolParams struct {
	SchoolID     int64  `json:"school_id"`
	ActionPrefix string `json:"action_prefix"`
	OffsetCount  int32  `json:"offset_count"`
	LimitCount   int32  `json:"limit_count"`
}

type ListAuditLogForSchoolRow struct {
	ID       int64              `json:"id"`
	UserName pgtype.Text        `json:"user_name"`
	Action   string             `json:"action"`
	Entity   string             `json:"entity"`
	EntityID pgtype.Int8        `json:"entity_id"`
	At       pgtype.Timestamptz `json:"at"`
}

// action_prefix kosong ("") berarti tanpa filter aksi.
func (q *Queries) ListAuditLogForSchool(ctx context.Context, arg ListAuditLogForSchoolParams) ([]ListAuditLogForSchoolRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogForSchool,
		arg.SchoolID,
		arg.ActionPrefix,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogForSchoolRow
	for rows.Next() {
		var i ListAuditLogForSchoolRow
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersForSchool = `-- name: ListMembersForSchool :many
SELECT
    m.user_id, u.name, u.email, u.username, m.role, m.status,
    (SELECT MAX(sess.created_at) FROM sessions sess WHERE sess.user_id = m.user_id AND sess.school_id = m.school_id)::timestamptz AS last_login
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.school_id = $1
ORDER BY u.name, m.role
`

type ListMembersForSchoolRow struct {
	UserID    int64              `json:"user_id"`
	Name      string             `json:"name"`
	Email     pgtype.Text        `json:"email"`
	Username  pgtype.Text        `json:"username"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	LastLogin pgtype.Timestamptz `json:"last_login"`
}

// Satu baris per membership (user muncul >1 kali bila punya >1 role, mis.
// guru + orang_tua) — last_login = sesi TERAKHIR user itu DI SEKOLAH ini
// (lintas role).
func (q *Queries) ListMembersForSchool(ctx context.Context, schoolID int64) ([]ListMembersForSchoolRow, error) {
	rows, err := q.db.Query(ctx, listMembersForSchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersForSchoolRow
	for rows.Next() {
		var i ListMembersForSchoolRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.Username,
			&i.Role,
			&i.Status,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissionOverrides = `-- name: ListRolePermissionOverrides :many

SELECT school_id, role, permission, allowed FROM school_role_permissions WHERE school_id = $1
`

// -- Fase 15 Gap 2, docs/12-sion-parity.md "matrix permission per role per
// sekolah" — pengecualian dari rolePermissions statis (rbac.go), lihat
// migrasi 00022_role_perms_gap.sql & internal/identity/permoverride.go.
func (q *Queries) ListRolePermissionOverrides(ctx context.Context, schoolID int64) ([]SchoolRolePermission, error) {
	rows, err := q.db.Query(ctx, listRolePermissionOverrides, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchoolRolePermission
	for rows.Next() {
		var i SchoolRolePermission
		if err := rows.Scan(
			&i.SchoolID,
			&i.Role,
			&i.Permission,
			&i.Allowed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIDsByRole = `-- name: ListUserIDsByRole :many
SELECT DISTINCT user_id FROM memberships
WHERE school_id = $1::bigint AND role = $2::text AND status = 'active'
`

type ListUserIDsByRoleParams struct {
	SchoolID int64  `json:"school_id"`
	Role     string `json:"role"`
}

// Dipakai interface publik Service.UsersWithRole (fase 9, docs/08-notification.md)
// — resolusi penerima notifikasi utk step approval leave dengan role-only
// (approver_user_id NULL: "siapa pun yang sedang memegang role ini").
func (q *Queries) ListUserIDsByRole(ctx context.Context, arg ListUserIDsByRoleParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUserIDsByRole, arg.SchoolID, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitationUsed = `-- name: MarkInvitationUsed :exec
UPDATE invitations SET used_at = $2 WHERE code = $1
`

type MarkInvitationUsedParams struct {
	Code   string             `json:"code"`
	UsedAt pgtype.Timestamptz `json:"used_at"`
}

func (q *Queries) MarkInvitationUsed(ctx context.Context, arg MarkInvitationUsedParams) error {
	_, err := q.db.Exec(ctx, markInvitationUsed, arg.Code, arg.UsedAt)
	return err
}

const setMembershipStatus = `-- name: SetMembershipStatus :exec
UPDATE memberships SET status = $4 WHERE user_id = $1 AND school_id = $2 AND role = $3
`

type SetMembershipStatusParams struct {
	UserID   int64  `json:"user_id"`
	SchoolID int64  `json:"school_id"`
	Role     string `json:"role"`
	Status   string `json:"status"`
}

func (q *Queries) SetMembershipStatus(ctx context.Context, arg SetMembershipStatusParams) error {
	_, err := q.db.Exec(ctx, setMembershipStatus,
		arg.UserID,
		arg.SchoolID,
		arg.Role,
		arg.Status,
	)
	return err
}

const setSuperAdmin = `-- name: SetSuperAdmin :exec
UPDATE users SET is_super_admin = $2 WHERE id = $1
`

type SetSuperAdminParams struct {
	ID           int64 `json:"id"`
	IsSuperAdmin bool  `json:"is_super_admin"`
}

func (q *Queries) SetSuperAdmin(ctx context.Context, arg SetSuperAdminParams) error {
	_, err := q.db.Exec(ctx, setSuperAdmin, arg.ID, arg.IsSuperAdmin)
	return err
}

const setUserName = `-- name: SetUserName :exec
UPDATE users SET name = $2 WHERE id = $1
`

type SetUserNameParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) SetUserName(ctx context.Context, arg SetUserNameParams) error {
	_, err := q.db.Exec(ctx, setUserName, arg.ID, arg.Name)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const upsertRolePermissionOverride = `-- name: UpsertRolePermissionOverride :exec
INSERT INTO school_role_permissions (school_id, role, permission, allowed)
VALUES ($1, $2, $3, $4)
ON CONFLICT (school_id, role, permission) DO UPDATE SET allowed = $4
`

type UpsertRolePermissionOverrideParams struct {
	SchoolID   int64  `json:"school_id"`
	Role       string `json:"role"`
	Permission string `json:"permission"`
	Allowed    bool   `json:"allowed"`
}

func (q *Queries) UpsertRolePermissionOverride(ctx context.Context, arg UpsertRolePermissionOverrideParams) error {
	_, err := q.db.Exec(ctx, upsertRolePermissionOverride,
		arg.SchoolID,
		arg.Role,
		arg.Permission,
		arg.Allowed,
	)
	return err
}
