// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package identitydb

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (user_id, school_id, role, status)
VALUES ($1, $2, $3, 'active')
ON CONFLICT (user_id, school_id, role) DO UPDATE SET status = 'active'
RETURNING id, user_id, school_id, role, status
`

type CreateMembershipParams struct {
	UserID   int64  `json:"user_id"`
	SchoolID int64  `json:"school_id"`
	Role     string `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.UserID, arg.SchoolID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SchoolID,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, school_id, token_hash, role, expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, school_id, token_hash, role, expires_at, created_at, ip, user_agent
`

type CreateSessionParams struct {
	UserID    int64              `json:"user_id"`
	SchoolID  pgtype.Int8        `json:"school_id"`
	TokenHash []byte             `json:"token_hash"`
	Role      string             `json:"role"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Ip        *netip.Addr        `json:"ip"`
	UserAgent pgtype.Text        `json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.SchoolID,
		arg.TokenHash,
		arg.Role,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SchoolID,
		&i.TokenHash,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, password_hash, name, phone, is_super_admin)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, username, password_hash, name, phone, is_super_admin, created_at
`

type CreateUserParams struct {
	Email        pgtype.Text `json:"email"`
	Username     pgtype.Text `json:"username"`
	PasswordHash string      `json:"password_hash"`
	Name         string      `json:"name"`
	Phone        pgtype.Text `json:"phone"`
	IsSuperAdmin bool        `json:"is_super_admin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Name,
		arg.Phone,
		arg.IsSuperAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.IsSuperAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const extendSession = `-- name: ExtendSession :exec
UPDATE sessions SET expires_at = $2 WHERE id = $1
`

type ExtendSessionParams struct {
	ID        int64              `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) error {
	_, err := q.db.Exec(ctx, extendSession, arg.ID, arg.ExpiresAt)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    s.id, s.user_id, s.school_id, s.token_hash, s.role, s.expires_at, s.created_at, s.ip, s.user_agent,
    u.name AS user_name,
    u.is_super_admin AS user_is_super_admin
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
`

type GetSessionByTokenHashRow struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	SchoolID         pgtype.Int8        `json:"school_id"`
	TokenHash        []byte             `json:"token_hash"`
	Role             string             `json:"role"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Ip               *netip.Addr        `json:"ip"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	UserName         string             `json:"user_name"`
	UserIsSuperAdmin bool               `json:"user_is_super_admin"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SchoolID,
		&i.TokenHash,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Ip,
		&i.UserAgent,
		&i.UserName,
		&i.UserIsSuperAdmin,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, email, username, password_hash, name, phone, is_super_admin, created_at FROM users WHERE email = $1
`

// Query modul identity (sqlc).
func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.IsSuperAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, password_hash, name, phone, is_super_admin, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.IsSuperAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password_hash, name, phone, is_super_admin, created_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Name,
		&i.Phone,
		&i.IsSuperAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (school_id, user_id, action, entity, entity_id, old_value, new_value)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditLogParams struct {
	SchoolID pgtype.Int8 `json:"school_id"`
	UserID   pgtype.Int8 `json:"user_id"`
	Action   string      `json:"action"`
	Entity   string      `json:"entity"`
	EntityID pgtype.Int8 `json:"entity_id"`
	OldValue []byte      `json:"old_value"`
	NewValue []byte      `json:"new_value"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.SchoolID,
		arg.UserID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.OldValue,
		arg.NewValue,
	)
	return err
}

const listActiveMembershipsByUserSchool = `-- name: ListActiveMembershipsByUserSchool :many
SELECT id, user_id, school_id, role, status FROM memberships WHERE user_id = $1 AND school_id = $2 AND status = 'active'
`

type ListActiveMembershipsByUserSchoolParams struct {
	UserID   int64 `json:"user_id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) ListActiveMembershipsByUserSchool(ctx context.Context, arg ListActiveMembershipsByUserSchoolParams) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listActiveMembershipsByUserSchool, arg.UserID, arg.SchoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Membership
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SchoolID,
			&i.Role,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSuperAdmin = `-- name: SetSuperAdmin :exec
UPDATE users SET is_super_admin = $2 WHERE id = $1
`

type SetSuperAdminParams struct {
	ID           int64 `json:"id"`
	IsSuperAdmin bool  `json:"is_super_admin"`
}

func (q *Queries) SetSuperAdmin(ctx context.Context, arg SetSuperAdminParams) error {
	_, err := q.db.Exec(ctx, setSuperAdmin, arg.ID, arg.IsSuperAdmin)
	return err
}

const setUserName = `-- name: SetUserName :exec
UPDATE users SET name = $2 WHERE id = $1
`

type SetUserNameParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) SetUserName(ctx context.Context, arg SetUserNameParams) error {
	_, err := q.db.Exec(ctx, setUserName, arg.ID, arg.Name)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
