// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package gradingdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComponent = `-- name: CreateComponent :one
INSERT INTO assessment_components (school_id, academic_year_id, class_id, subject_id, name, type, weight, kktp, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, school_id, academic_year_id, class_id, subject_id, name, type, weight, kktp, created_by, created_at
`

type CreateComponentParams struct {
	SchoolID       int64       `json:"school_id"`
	AcademicYearID int64       `json:"academic_year_id"`
	ClassID        int64       `json:"class_id"`
	SubjectID      int64       `json:"subject_id"`
	Name           string      `json:"name"`
	Type           string      `json:"type"`
	Weight         int32       `json:"weight"`
	Kktp           int32       `json:"kktp"`
	CreatedBy      pgtype.Int8 `json:"created_by"`
}

func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) (AssessmentComponent, error) {
	row := q.db.QueryRow(ctx, createComponent,
		arg.SchoolID,
		arg.AcademicYearID,
		arg.ClassID,
		arg.SubjectID,
		arg.Name,
		arg.Type,
		arg.Weight,
		arg.Kktp,
		arg.CreatedBy,
	)
	var i AssessmentComponent
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.ClassID,
		&i.SubjectID,
		&i.Name,
		&i.Type,
		&i.Weight,
		&i.Kktp,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createStar = `-- name: CreateStar :one
INSERT INTO classroom_star_events (school_id, academic_year_id, student_id, given_by, delta, note, visibility)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, school_id, academic_year_id, student_id, given_by, delta, note, visibility, created_at
`

type CreateStarParams struct {
	SchoolID       int64  `json:"school_id"`
	AcademicYearID int64  `json:"academic_year_id"`
	StudentID      int64  `json:"student_id"`
	GivenBy        int64  `json:"given_by"`
	Delta          int32  `json:"delta"`
	Note           string `json:"note"`
	Visibility     string `json:"visibility"`
}

func (q *Queries) CreateStar(ctx context.Context, arg CreateStarParams) (ClassroomStarEvent, error) {
	row := q.db.QueryRow(ctx, createStar,
		arg.SchoolID,
		arg.AcademicYearID,
		arg.StudentID,
		arg.GivenBy,
		arg.Delta,
		arg.Note,
		arg.Visibility,
	)
	var i ClassroomStarEvent
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.StudentID,
		&i.GivenBy,
		&i.Delta,
		&i.Note,
		&i.Visibility,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComponent = `-- name: DeleteComponent :execrows
DELETE FROM assessment_components WHERE id = $1 AND school_id = $2
`

type DeleteComponentParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) DeleteComponent(ctx context.Context, arg DeleteComponentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteComponent, arg.ID, arg.SchoolID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGrade = `-- name: DeleteGrade :exec
DELETE FROM student_grades WHERE component_id = $1 AND student_id = $2
`

type DeleteGradeParams struct {
	ComponentID int64 `json:"component_id"`
	StudentID   int64 `json:"student_id"`
}

func (q *Queries) DeleteGrade(ctx context.Context, arg DeleteGradeParams) error {
	_, err := q.db.Exec(ctx, deleteGrade, arg.ComponentID, arg.StudentID)
	return err
}

const deletePublication = `-- name: DeletePublication :exec
DELETE FROM grade_publications WHERE school_id = $1 AND academic_year_id = $2 AND class_id = $3 AND subject_id = $4
`

type DeletePublicationParams struct {
	SchoolID       int64 `json:"school_id"`
	AcademicYearID int64 `json:"academic_year_id"`
	ClassID        int64 `json:"class_id"`
	SubjectID      int64 `json:"subject_id"`
}

func (q *Queries) DeletePublication(ctx context.Context, arg DeletePublicationParams) error {
	_, err := q.db.Exec(ctx, deletePublication,
		arg.SchoolID,
		arg.AcademicYearID,
		arg.ClassID,
		arg.SubjectID,
	)
	return err
}

const deleteStar = `-- name: DeleteStar :execrows
DELETE FROM classroom_star_events WHERE id = $1 AND school_id = $2
`

type DeleteStarParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) DeleteStar(ctx context.Context, arg DeleteStarParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStar, arg.ID, arg.SchoolID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getClassByID = `-- name: GetClassByID :one

SELECT id, name, academic_year_id FROM classes WHERE id = $1 AND school_id = $2
`

type GetClassByIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetClassByIDRow struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	AcademicYearID int64  `json:"academic_year_id"`
}

// -- lookup & validasi lintas modul (join read-only) --
func (q *Queries) GetClassByID(ctx context.Context, arg GetClassByIDParams) (GetClassByIDRow, error) {
	row := q.db.QueryRow(ctx, getClassByID, arg.ID, arg.SchoolID)
	var i GetClassByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.AcademicYearID)
	return i, err
}

const getComponentByID = `-- name: GetComponentByID :one
SELECT id, school_id, academic_year_id, class_id, subject_id, name, type, weight, kktp, created_by, created_at FROM assessment_components WHERE id = $1 AND school_id = $2
`

type GetComponentByIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) GetComponentByID(ctx context.Context, arg GetComponentByIDParams) (AssessmentComponent, error) {
	row := q.db.QueryRow(ctx, getComponentByID, arg.ID, arg.SchoolID)
	var i AssessmentComponent
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.ClassID,
		&i.SubjectID,
		&i.Name,
		&i.Type,
		&i.Weight,
		&i.Kktp,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPublication = `-- name: GetPublication :one
SELECT school_id, academic_year_id, class_id, subject_id, published_at, published_by FROM grade_publications WHERE school_id = $1 AND academic_year_id = $2 AND class_id = $3 AND subject_id = $4
`

type GetPublicationParams struct {
	SchoolID       int64 `json:"school_id"`
	AcademicYearID int64 `json:"academic_year_id"`
	ClassID        int64 `json:"class_id"`
	SubjectID      int64 `json:"subject_id"`
}

func (q *Queries) GetPublication(ctx context.Context, arg GetPublicationParams) (GradePublication, error) {
	row := q.db.QueryRow(ctx, getPublication,
		arg.SchoolID,
		arg.AcademicYearID,
		arg.ClassID,
		arg.SubjectID,
	)
	var i GradePublication
	err := row.Scan(
		&i.SchoolID,
		&i.AcademicYearID,
		&i.ClassID,
		&i.SubjectID,
		&i.PublishedAt,
		&i.PublishedBy,
	)
	return i, err
}

const getStarByID = `-- name: GetStarByID :one
SELECT id, school_id, academic_year_id, student_id, given_by, delta, note, visibility, created_at FROM classroom_star_events WHERE id = $1 AND school_id = $2
`

type GetStarByIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) GetStarByID(ctx context.Context, arg GetStarByIDParams) (ClassroomStarEvent, error) {
	row := q.db.QueryRow(ctx, getStarByID, arg.ID, arg.SchoolID)
	var i ClassroomStarEvent
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.StudentID,
		&i.GivenBy,
		&i.Delta,
		&i.Note,
		&i.Visibility,
		&i.CreatedAt,
	)
	return i, err
}

const getStudentBasic = `-- name: GetStudentBasic :one
SELECT name, nis FROM students WHERE id = $1 AND school_id = $2
`

type GetStudentBasicParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetStudentBasicRow struct {
	Name string `json:"name"`
	Nis  string `json:"nis"`
}

func (q *Queries) GetStudentBasic(ctx context.Context, arg GetStudentBasicParams) (GetStudentBasicRow, error) {
	row := q.db.QueryRow(ctx, getStudentBasic, arg.ID, arg.SchoolID)
	var i GetStudentBasicRow
	err := row.Scan(&i.Name, &i.Nis)
	return i, err
}

const getSubjectByID = `-- name: GetSubjectByID :one
SELECT id, code, name FROM subjects WHERE id = $1 AND school_id = $2
`

type GetSubjectByIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetSubjectByIDRow struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) GetSubjectByID(ctx context.Context, arg GetSubjectByIDParams) (GetSubjectByIDRow, error) {
	row := q.db.QueryRow(ctx, getSubjectByID, arg.ID, arg.SchoolID)
	var i GetSubjectByIDRow
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const listClassRoster = `-- name: ListClassRoster :many
SELECT s.id, s.name, s.nis, COALESCE(s.user_id, 0)::bigint AS user_id
FROM students s
JOIN enrollments e ON e.student_id = s.id
WHERE e.class_id = $1 AND s.school_id = $2
ORDER BY s.name
`

type ListClassRosterParams struct {
	ClassID  int64 `json:"class_id"`
	SchoolID int64 `json:"school_id"`
}

type ListClassRosterRow struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Nis    string `json:"nis"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) ListClassRoster(ctx context.Context, arg ListClassRosterParams) ([]ListClassRosterRow, error) {
	rows, err := q.db.Query(ctx, listClassRoster, arg.ClassID, arg.SchoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassRosterRow
	for rows.Next() {
		var i ListClassRosterRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Nis,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentsByClassSubject = `-- name: ListComponentsByClassSubject :many
SELECT c.id, c.school_id, c.academic_year_id, c.class_id, c.subject_id, c.name, c.type, c.weight, c.kktp, c.created_by, c.created_at,
    (SELECT COUNT(*) FROM student_grades sg WHERE sg.component_id = c.id) AS graded_count,
    (SELECT COUNT(*) FROM enrollments e WHERE e.class_id = c.class_id) AS student_count
FROM assessment_components c
WHERE c.school_id = $1 AND c.class_id = $2 AND c.subject_id = $3
ORDER BY c.id
`

type ListComponentsByClassSubjectParams struct {
	SchoolID  int64 `json:"school_id"`
	ClassID   int64 `json:"class_id"`
	SubjectID int64 `json:"subject_id"`
}

type ListComponentsByClassSubjectRow struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	AcademicYearID int64              `json:"academic_year_id"`
	ClassID        int64              `json:"class_id"`
	SubjectID      int64              `json:"subject_id"`
	Name           string             `json:"name"`
	Type           string             `json:"type"`
	Weight         int32              `json:"weight"`
	Kktp           int32              `json:"kktp"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	GradedCount    int64              `json:"graded_count"`
	StudentCount   int64              `json:"student_count"`
}

func (q *Queries) ListComponentsByClassSubject(ctx context.Context, arg ListComponentsByClassSubjectParams) ([]ListComponentsByClassSubjectRow, error) {
	rows, err := q.db.Query(ctx, listComponentsByClassSubject, arg.SchoolID, arg.ClassID, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListComponentsByClassSubjectRow
	for rows.Next() {
		var i ListComponentsByClassSubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.AcademicYearID,
			&i.ClassID,
			&i.SubjectID,
			&i.Name,
			&i.Type,
			&i.Weight,
			&i.Kktp,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.GradedCount,
			&i.StudentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentsRawByClassSubject = `-- name: ListComponentsRawByClassSubject :many
SELECT id, school_id, academic_year_id, class_id, subject_id, name, type, weight, kktp, created_by, created_at FROM assessment_components
WHERE school_id = $1 AND class_id = $2 AND subject_id = $3
ORDER BY id
`

type ListComponentsRawByClassSubjectParams struct {
	SchoolID  int64 `json:"school_id"`
	ClassID   int64 `json:"class_id"`
	SubjectID int64 `json:"subject_id"`
}

func (q *Queries) ListComponentsRawByClassSubject(ctx context.Context, arg ListComponentsRawByClassSubjectParams) ([]AssessmentComponent, error) {
	rows, err := q.db.Query(ctx, listComponentsRawByClassSubject, arg.SchoolID, arg.ClassID, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssessmentComponent
	for rows.Next() {
		var i AssessmentComponent
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.AcademicYearID,
			&i.ClassID,
			&i.SubjectID,
			&i.Name,
			&i.Type,
			&i.Weight,
			&i.Kktp,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGradesForComponent = `-- name: ListGradesForComponent :many
SELECT student_id, score::float8 AS score FROM student_grades WHERE component_id = $1
`

type ListGradesForComponentRow struct {
	StudentID int64   `json:"student_id"`
	Score     float64 `json:"score"`
}

func (q *Queries) ListGradesForComponent(ctx context.Context, componentID int64) ([]ListGradesForComponentRow, error) {
	rows, err := q.db.Query(ctx, listGradesForComponent, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGradesForComponentRow
	for rows.Next() {
		var i ListGradesForComponentRow
		if err := rows.Scan(&i.StudentID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGradesForComponents = `-- name: ListGradesForComponents :many
SELECT component_id, student_id, score::float8 AS score FROM student_grades
WHERE component_id = ANY($1::bigint[])
`

type ListGradesForComponentsRow struct {
	ComponentID int64   `json:"component_id"`
	StudentID   int64   `json:"student_id"`
	Score       float64 `json:"score"`
}

func (q *Queries) ListGradesForComponents(ctx context.Context, componentIds []int64) ([]ListGradesForComponentsRow, error) {
	rows, err := q.db.Query(ctx, listGradesForComponents, componentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGradesForComponentsRow
	for rows.Next() {
		var i ListGradesForComponentsRow
		if err := rows.Scan(&i.ComponentID, &i.StudentID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedSubjectsForClass = `-- name: ListPublishedSubjectsForClass :many
SELECT subject_id FROM grade_publications WHERE school_id = $1 AND academic_year_id = $2 AND class_id = $3
`

type ListPublishedSubjectsForClassParams struct {
	SchoolID       int64 `json:"school_id"`
	AcademicYearID int64 `json:"academic_year_id"`
	ClassID        int64 `json:"class_id"`
}

func (q *Queries) ListPublishedSubjectsForClass(ctx context.Context, arg ListPublishedSubjectsForClassParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listPublishedSubjectsForClass, arg.SchoolID, arg.AcademicYearID, arg.ClassID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var subject_id int64
		if err := rows.Scan(&subject_id); err != nil {
			return nil, err
		}
		items = append(items, subject_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStarTotalsForClass = `-- name: ListStarTotalsForClass :many
SELECT s.id AS student_id, s.name AS student_name, s.nis AS student_nis,
    COALESCE((SELECT SUM(e.delta) FROM classroom_star_events e WHERE e.student_id = s.id AND e.school_id = $1), 0)::int AS total
FROM students s
JOIN enrollments en ON en.student_id = s.id
WHERE en.class_id = $2 AND s.school_id = $1
ORDER BY s.name
`

type ListStarTotalsForClassParams struct {
	SchoolID int64 `json:"school_id"`
	ClassID  int64 `json:"class_id"`
}

type ListStarTotalsForClassRow struct {
	StudentID   int64  `json:"student_id"`
	StudentName string `json:"student_name"`
	StudentNis  string `json:"student_nis"`
	Total       int32  `json:"total"`
}

func (q *Queries) ListStarTotalsForClass(ctx context.Context, arg ListStarTotalsForClassParams) ([]ListStarTotalsForClassRow, error) {
	rows, err := q.db.Query(ctx, listStarTotalsForClass, arg.SchoolID, arg.ClassID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStarTotalsForClassRow
	for rows.Next() {
		var i ListStarTotalsForClassRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentName,
			&i.StudentNis,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStarsForStudent = `-- name: ListStarsForStudent :many
SELECT e.id, e.delta, e.note, e.visibility, e.created_at, u.name AS given_by_name
FROM classroom_star_events e
JOIN users u ON u.id = e.given_by
WHERE e.school_id = $1 AND e.student_id = $2
ORDER BY e.created_at DESC
`

type ListStarsForStudentParams struct {
	SchoolID  int64 `json:"school_id"`
	StudentID int64 `json:"student_id"`
}

type ListStarsForStudentRow struct {
	ID          int64              `json:"id"`
	Delta       int32              `json:"delta"`
	Note        string             `json:"note"`
	Visibility  string             `json:"visibility"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	GivenByName string             `json:"given_by_name"`
}

func (q *Queries) ListStarsForStudent(ctx context.Context, arg ListStarsForStudentParams) ([]ListStarsForStudentRow, error) {
	rows, err := q.db.Query(ctx, listStarsForStudent, arg.SchoolID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStarsForStudentRow
	for rows.Next() {
		var i ListStarsForStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.Delta,
			&i.Note,
			&i.Visibility,
			&i.CreatedAt,
			&i.GivenByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStarsForStudentVisible = `-- name: ListStarsForStudentVisible :many
SELECT e.id, e.delta, e.note, e.visibility, e.created_at, u.name AS given_by_name
FROM classroom_star_events e
JOIN users u ON u.id = e.given_by
WHERE e.school_id = $1 AND e.student_id = $2 AND e.visibility = 'student'
ORDER BY e.created_at DESC
`

type ListStarsForStudentVisibleParams struct {
	SchoolID  int64 `json:"school_id"`
	StudentID int64 `json:"student_id"`
}

type ListStarsForStudentVisibleRow struct {
	ID          int64              `json:"id"`
	Delta       int32              `json:"delta"`
	Note        string             `json:"note"`
	Visibility  string             `json:"visibility"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	GivenByName string             `json:"given_by_name"`
}

func (q *Queries) ListStarsForStudentVisible(ctx context.Context, arg ListStarsForStudentVisibleParams) ([]ListStarsForStudentVisibleRow, error) {
	rows, err := q.db.Query(ctx, listStarsForStudentVisible, arg.SchoolID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStarsForStudentVisibleRow
	for rows.Next() {
		var i ListStarsForStudentVisibleRow
		if err := rows.Scan(
			&i.ID,
			&i.Delta,
			&i.Note,
			&i.Visibility,
			&i.CreatedAt,
			&i.GivenByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const studentClassID = `-- name: StudentClassID :one
SELECT e.class_id FROM enrollments e
JOIN classes c ON c.id = e.class_id
WHERE e.student_id = $1 AND c.school_id = $2 AND c.academic_year_id = $3
`

type StudentClassIDParams struct {
	StudentID      int64 `json:"student_id"`
	SchoolID       int64 `json:"school_id"`
	AcademicYearID int64 `json:"academic_year_id"`
}

func (q *Queries) StudentClassID(ctx context.Context, arg StudentClassIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, studentClassID, arg.StudentID, arg.SchoolID, arg.AcademicYearID)
	var class_id int64
	err := row.Scan(&class_id)
	return class_id, err
}

const updateComponent = `-- name: UpdateComponent :one
UPDATE assessment_components SET
    name   = COALESCE($1, name),
    type   = COALESCE($2, type),
    weight = COALESCE($3, weight),
    kktp   = COALESCE($4, kktp)
WHERE id = $5 AND school_id = $6
RETURNING id, school_id, academic_year_id, class_id, subject_id, name, type, weight, kktp, created_by, created_at
`

type UpdateComponentParams struct {
	Name     pgtype.Text `json:"name"`
	Type     pgtype.Text `json:"type"`
	Weight   pgtype.Int4 `json:"weight"`
	Kktp     pgtype.Int4 `json:"kktp"`
	ID       int64       `json:"id"`
	SchoolID int64       `json:"school_id"`
}

func (q *Queries) UpdateComponent(ctx context.Context, arg UpdateComponentParams) (AssessmentComponent, error) {
	row := q.db.QueryRow(ctx, updateComponent,
		arg.Name,
		arg.Type,
		arg.Weight,
		arg.Kktp,
		arg.ID,
		arg.SchoolID,
	)
	var i AssessmentComponent
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.ClassID,
		&i.SubjectID,
		&i.Name,
		&i.Type,
		&i.Weight,
		&i.Kktp,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const upsertGrade = `-- name: UpsertGrade :one
INSERT INTO student_grades (school_id, component_id, student_id, score, graded_by)
VALUES ($1, $2, $3, $5::float8, $4)
ON CONFLICT (component_id, student_id) DO UPDATE SET
    score = EXCLUDED.score, graded_by = EXCLUDED.graded_by, updated_at = now()
RETURNING id, school_id, component_id, student_id, score::float8 AS score, graded_by, updated_at
`

type UpsertGradeParams struct {
	SchoolID    int64       `json:"school_id"`
	ComponentID int64       `json:"component_id"`
	StudentID   int64       `json:"student_id"`
	GradedBy    pgtype.Int8 `json:"graded_by"`
	Score       float64     `json:"score"`
}

type UpsertGradeRow struct {
	ID          int64              `json:"id"`
	SchoolID    int64              `json:"school_id"`
	ComponentID int64              `json:"component_id"`
	StudentID   int64              `json:"student_id"`
	Score       float64            `json:"score"`
	GradedBy    pgtype.Int8        `json:"graded_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertGrade(ctx context.Context, arg UpsertGradeParams) (UpsertGradeRow, error) {
	row := q.db.QueryRow(ctx, upsertGrade,
		arg.SchoolID,
		arg.ComponentID,
		arg.StudentID,
		arg.GradedBy,
		arg.Score,
	)
	var i UpsertGradeRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.ComponentID,
		&i.StudentID,
		&i.Score,
		&i.GradedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPublication = `-- name: UpsertPublication :exec
INSERT INTO grade_publications (school_id, academic_year_id, class_id, subject_id, published_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (school_id, academic_year_id, class_id, subject_id) DO UPDATE SET
    published_at = now(), published_by = EXCLUDED.published_by
`

type UpsertPublicationParams struct {
	SchoolID       int64       `json:"school_id"`
	AcademicYearID int64       `json:"academic_year_id"`
	ClassID        int64       `json:"class_id"`
	SubjectID      int64       `json:"subject_id"`
	PublishedBy    pgtype.Int8 `json:"published_by"`
}

func (q *Queries) UpsertPublication(ctx context.Context, arg UpsertPublicationParams) error {
	_, err := q.db.Exec(ctx, upsertPublication,
		arg.SchoolID,
		arg.AcademicYearID,
		arg.ClassID,
		arg.SubjectID,
		arg.PublishedBy,
	)
	return err
}
