// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package platformadmindb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveStudentsForSchool = `-- name: CountActiveStudentsForSchool :one
SELECT COUNT(*) FROM students WHERE school_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveStudentsForSchool(ctx context.Context, schoolID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveStudentsForSchool, schoolID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAttendanceSessionsSince = `-- name: CountAttendanceSessionsSince :one
SELECT COUNT(*) FROM attendance_sessions
WHERE school_id = $1::bigint AND date >= $2::date
`

type CountAttendanceSessionsSinceParams struct {
	SchoolID  int64       `json:"school_id"`
	SinceDate pgtype.Date `json:"since_date"`
}

func (q *Queries) CountAttendanceSessionsSince(ctx context.Context, arg CountAttendanceSessionsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAttendanceSessionsSince, arg.SchoolID, arg.SinceDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countClassesForSchool = `-- name: CountClassesForSchool :one
SELECT COUNT(*) FROM classes WHERE school_id = $1
`

func (q *Queries) CountClassesForSchool(ctx context.Context, schoolID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countClassesForSchool, schoolID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJournalsSince = `-- name: CountJournalsSince :one
SELECT COUNT(*) FROM teaching_journals
WHERE school_id = $1::bigint AND date >= $2::date
`

type CountJournalsSinceParams struct {
	SchoolID  int64       `json:"school_id"`
	SinceDate pgtype.Date `json:"since_date"`
}

func (q *Queries) CountJournalsSince(ctx context.Context, arg CountJournalsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJournalsSince, arg.SchoolID, arg.SinceDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLeadsSince = `-- name: CountLeadsSince :one
SELECT COUNT(*) FROM interest_leads WHERE created_at >= $1::timestamptz
`

func (q *Queries) CountLeadsSince(ctx context.Context, since pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countLeadsSince, since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOutboxAdmin = `-- name: CountOutboxAdmin :one
SELECT COUNT(*) FROM notification_outbox o
WHERE ($1::text = '' OR o.status = $1::text)
  AND ($2::bigint = 0 OR o.school_id = $2::bigint)
`

type CountOutboxAdminParams struct {
	Status   string `json:"status"`
	SchoolID int64  `json:"school_id"`
}

func (q *Queries) CountOutboxAdmin(ctx context.Context, arg CountOutboxAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOutboxAdmin, arg.Status, arg.SchoolID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOutboxByStatusSince = `-- name: CountOutboxByStatusSince :many
SELECT status, COUNT(*) AS n FROM notification_outbox
WHERE school_id = $1::bigint AND created_at >= $2::timestamptz
GROUP BY status
`

type CountOutboxByStatusSinceParams struct {
	SchoolID int64              `json:"school_id"`
	Since    pgtype.Timestamptz `json:"since"`
}

type CountOutboxByStatusSinceRow struct {
	Status string `json:"status"`
	N      int64  `json:"n"`
}

func (q *Queries) CountOutboxByStatusSince(ctx context.Context, arg CountOutboxByStatusSinceParams) ([]CountOutboxByStatusSinceRow, error) {
	rows, err := q.db.Query(ctx, countOutboxByStatusSince, arg.SchoolID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOutboxByStatusSinceRow
	for rows.Next() {
		var i CountOutboxByStatusSinceRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTeachersForSchool = `-- name: CountTeachersForSchool :one

SELECT COUNT(*) FROM teachers WHERE school_id = $1
`

// -- P3: GET /api/admin/schools/{id}/stats --
func (q *Queries) CountTeachersForSchool(ctx context.Context, schoolID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTeachersForSchool, schoolID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalActiveStudents = `-- name: CountTotalActiveStudents :one
SELECT COUNT(*) FROM students WHERE status = 'active'
`

// Lintas SEMUA sekolah (agregat platform, bukan data per-siswa — docs/11
// aturan #3).
func (q *Queries) CountTotalActiveStudents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalActiveStudents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePlatformAnnouncement = `-- name: DeletePlatformAnnouncement :execrows
DELETE FROM platform_announcements WHERE id = $1::bigint
`

func (q *Queries) DeletePlatformAnnouncement(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlatformAnnouncement, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOutboxByID = `-- name: GetOutboxByID :one
SELECT id, school_id, event, user_id, channel, payload, status, attempts, next_retry_at, created_at, sent_at FROM notification_outbox WHERE id = $1
`

func (q *Queries) GetOutboxByID(ctx context.Context, id int64) (NotificationOutbox, error) {
	row := q.db.QueryRow(ctx, getOutboxByID, id)
	var i NotificationOutbox
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Event,
		&i.UserID,
		&i.Channel,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const insertPlatformAnnouncement = `-- name: InsertPlatformAnnouncement :one

INSERT INTO platform_announcements (title, body, starts_at, ends_at, created_by)
VALUES ($1::text, $2::text, $3::date, $4::date, $5::bigint)
RETURNING id, title, body, starts_at, ends_at, created_by, created_at
`

type InsertPlatformAnnouncementParams struct {
	Title     string      `json:"title"`
	Body      string      `json:"body"`
	StartsAt  pgtype.Date `json:"starts_at"`
	EndsAt    pgtype.Date `json:"ends_at"`
	CreatedBy int64       `json:"created_by"`
}

// -- P5 (fase 13 Gelombang 2): platform_announcements, docs/11-superadmin.md
// "Pengumuman platform" — TIDAK tenant-scoped (satu baris = tampil di SEMUA
// sekolah), jadi TIDAK ada filter school_id (beda dari announcements
// per-sekolah di internal/announcement).
func (q *Queries) InsertPlatformAnnouncement(ctx context.Context, arg InsertPlatformAnnouncementParams) (PlatformAnnouncement, error) {
	row := q.db.QueryRow(ctx, insertPlatformAnnouncement,
		arg.Title,
		arg.Body,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedBy,
	)
	var i PlatformAnnouncement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listActivePlatformAnnouncements = `-- name: ListActivePlatformAnnouncements :many
SELECT id, title, body, starts_at, ends_at, created_by, created_at FROM platform_announcements WHERE starts_at <= $1::date AND ends_at >= $1::date
ORDER BY starts_at DESC, id DESC
`

func (q *Queries) ListActivePlatformAnnouncements(ctx context.Context, onDate pgtype.Date) ([]PlatformAnnouncement, error) {
	rows, err := q.db.Query(ctx, listActivePlatformAnnouncements, onDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformAnnouncement
	for rows.Next() {
		var i PlatformAnnouncement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesAwaitingVerification = `-- name: ListInvoicesAwaitingVerification :many
SELECT i.id AS invoice_id, i.number, i.school_id, s.name AS school_name, i.amount
FROM invoices i
JOIN schools s ON s.id = i.school_id
WHERE i.status = 'awaiting_verification'
ORDER BY i.created_at
`

type ListInvoicesAwaitingVerificationRow struct {
	InvoiceID  int64  `json:"invoice_id"`
	Number     string `json:"number"`
	SchoolID   int64  `json:"school_id"`
	SchoolName string `json:"school_name"`
	Amount     int64  `json:"amount"`
}

func (q *Queries) ListInvoicesAwaitingVerification(ctx context.Context) ([]ListInvoicesAwaitingVerificationRow, error) {
	rows, err := q.db.Query(ctx, listInvoicesAwaitingVerification)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesAwaitingVerificationRow
	for rows.Next() {
		var i ListInvoicesAwaitingVerificationRow
		if err := rows.Scan(
			&i.InvoiceID,
			&i.Number,
			&i.SchoolID,
			&i.SchoolName,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLastLoginsByRole = `-- name: ListLastLoginsByRole :many
SELECT role, MAX(created_at)::timestamptz AS last_login
FROM sessions
WHERE school_id = $1::bigint
GROUP BY role
ORDER BY role
`

type ListLastLoginsByRoleRow struct {
	Role      string             `json:"role"`
	LastLogin pgtype.Timestamptz `json:"last_login"`
}

func (q *Queries) ListLastLoginsByRole(ctx context.Context, schoolID int64) ([]ListLastLoginsByRoleRow, error) {
	rows, err := q.db.Query(ctx, listLastLoginsByRole, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLastLoginsByRoleRow
	for rows.Next() {
		var i ListLastLoginsByRoleRow
		if err := rows.Scan(&i.Role, &i.LastLogin); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutboxAdmin = `-- name: ListOutboxAdmin :many

SELECT o.id, o.school_id, s.name AS school_name, o.event, o.channel, u.name AS user_name,
       o.status, o.attempts, o.next_retry_at, o.created_at
FROM notification_outbox o
JOIN schools s ON s.id = o.school_id
JOIN users u ON u.id = o.user_id
WHERE ($1::text = '' OR o.status = $1::text)
  AND ($2::bigint = 0 OR o.school_id = $2::bigint)
ORDER BY o.created_at DESC
LIMIT $4::int OFFSET $3::int
`

type ListOutboxAdminParams struct {
	Status      string `json:"status"`
	SchoolID    int64  `json:"school_id"`
	OffsetCount int32  `json:"offset_count"`
	LimitCount  int32  `json:"limit_count"`
}

type ListOutboxAdminRow struct {
	ID          int64              `json:"id"`
	SchoolID    int64              `json:"school_id"`
	SchoolName  string             `json:"school_name"`
	Event       string             `json:"event"`
	Channel     string             `json:"channel"`
	UserName    string             `json:"user_name"`
	Status      string             `json:"status"`
	Attempts    int32              `json:"attempts"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// -- P4.4: outbox global --
// status kosong ("") = semua status; school_id 0 = semua sekolah.
func (q *Queries) ListOutboxAdmin(ctx context.Context, arg ListOutboxAdminParams) ([]ListOutboxAdminRow, error) {
	rows, err := q.db.Query(ctx, listOutboxAdmin,
		arg.Status,
		arg.SchoolID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutboxAdminRow
	for rows.Next() {
		var i ListOutboxAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.SchoolName,
			&i.Event,
			&i.Channel,
			&i.UserName,
			&i.Status,
			&i.Attempts,
			&i.NextRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformAnnouncements = `-- name: ListPlatformAnnouncements :many
SELECT id, title, body, starts_at, ends_at, created_by, created_at FROM platform_announcements ORDER BY starts_at DESC, id DESC
`

func (q *Queries) ListPlatformAnnouncements(ctx context.Context) ([]PlatformAnnouncement, error) {
	rows, err := q.db.Query(ctx, listPlatformAnnouncements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformAnnouncement
	for rows.Next() {
		var i PlatformAnnouncement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchoolLastActivity = `-- name: ListSchoolLastActivity :many
SELECT
    s.id AS school_id, s.name,
    (SELECT MAX(sess.created_at) FROM sessions sess WHERE sess.school_id = s.id)::timestamptz AS last_login,
    (SELECT MAX(a.created_at) FROM attendance_sessions a WHERE a.school_id = s.id)::timestamptz AS last_attendance_session
FROM schools s
ORDER BY last_login ASC NULLS FIRST
LIMIT $1::int
`

type ListSchoolLastActivityRow struct {
	SchoolID              int64              `json:"school_id"`
	Name                  string             `json:"name"`
	LastLogin             pgtype.Timestamptz `json:"last_login"`
	LastAttendanceSession pgtype.Timestamptz `json:"last_attendance_session"`
}

// Urut last_login ASC NULLS FIRST (paling tidak aktif dulu, docs P1).
func (q *Queries) ListSchoolLastActivity(ctx context.Context, limitCount int32) ([]ListSchoolLastActivityRow, error) {
	rows, err := q.db.Query(ctx, listSchoolLastActivity, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchoolLastActivityRow
	for rows.Next() {
		var i ListSchoolLastActivityRow
		if err := rows.Scan(
			&i.SchoolID,
			&i.Name,
			&i.LastLogin,
			&i.LastAttendanceSession,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchoolsOverview = `-- name: ListSchoolsOverview :many


SELECT
    s.id AS school_id, s.name, s.status AS school_status,
    sub.status AS sub_status, sub.ends_on AS sub_ends_on
FROM schools s
LEFT JOIN subscriptions sub ON sub.school_id = s.id
ORDER BY s.name
`

type ListSchoolsOverviewRow struct {
	SchoolID     int64       `json:"school_id"`
	Name         string      `json:"name"`
	SchoolStatus string      `json:"school_status"`
	SubStatus    pgtype.Text `json:"sub_status"`
	SubEndsOn    pgtype.Date `json:"sub_ends_on"`
}

// Query modul platformadmin (sqlc). SEMUA query di sini adalah agregasi
// READ-ONLY lintas modul (schools/subscriptions/invoices/students/
// interest_leads/notification_outbox/sessions/attendance_sessions/
// teaching_journals) untuk panel super admin (fase 13, docs/11-superadmin.md
// P1/P3/P4) — DIPERBOLEHKAN secara eksplisit oleh instruksi tugas untuk modul
// agregator (preseden dashboard/tv-board), lihat catatan desain lengkap di
// package doc (service.go). Mutasi HANYA menyentuh notification_outbox
// (status flag sederhana, TIDAK menduplikasi logika worker) — lihat
// RetryOutboxRow/RetryAllOutbox di bawah.
// -- P1: GET /api/admin/overview --
// Dipakai Service.Overview membangun bucket schools_active/grace/readonly/
// suspended (fallback readonly bila tanpa subscription, suspended dari
// schools.status) DAN daftar perlu-perhatian grace/readonly — lihat
// effectiveStatus di service.go.
func (q *Queries) ListSchoolsOverview(ctx context.Context) ([]ListSchoolsOverviewRow, error) {
	rows, err := q.db.Query(ctx, listSchoolsOverview)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchoolsOverviewRow
	for rows.Next() {
		var i ListSchoolsOverviewRow
		if err := rows.Scan(
			&i.SchoolID,
			&i.Name,
			&i.SchoolStatus,
			&i.SubStatus,
			&i.SubEndsOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchoolsWithDeadOutbox = `-- name: ListSchoolsWithDeadOutbox :many
SELECT o.school_id, s.name AS school_name, COUNT(*) AS dead_count
FROM notification_outbox o
JOIN schools s ON s.id = o.school_id
WHERE o.status = 'dead'
GROUP BY o.school_id, s.name
ORDER BY COUNT(*) DESC
`

type ListSchoolsWithDeadOutboxRow struct {
	SchoolID   int64  `json:"school_id"`
	SchoolName string `json:"school_name"`
	DeadCount  int64  `json:"dead_count"`
}

func (q *Queries) ListSchoolsWithDeadOutbox(ctx context.Context) ([]ListSchoolsWithDeadOutboxRow, error) {
	rows, err := q.db.Query(ctx, listSchoolsWithDeadOutbox)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchoolsWithDeadOutboxRow
	for rows.Next() {
		var i ListSchoolsWithDeadOutboxRow
		if err := rows.Scan(&i.SchoolID, &i.SchoolName, &i.DeadCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchoolsWithoutActiveYear = `-- name: ListSchoolsWithoutActiveYear :many
SELECT s.id AS school_id, s.name
FROM schools s
WHERE NOT EXISTS (
    SELECT 1 FROM academic_years ay WHERE ay.school_id = s.id AND ay.is_active
)
ORDER BY s.name
`

type ListSchoolsWithoutActiveYearRow struct {
	SchoolID int64  `json:"school_id"`
	Name     string `json:"name"`
}

func (q *Queries) ListSchoolsWithoutActiveYear(ctx context.Context) ([]ListSchoolsWithoutActiveYearRow, error) {
	rows, err := q.db.Query(ctx, listSchoolsWithoutActiveYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchoolsWithoutActiveYearRow
	for rows.Next() {
		var i ListSchoolsWithoutActiveYearRow
		if err := rows.Scan(&i.SchoolID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryAllOutbox = `-- name: RetryAllOutbox :execrows
UPDATE notification_outbox SET status = 'pending', next_retry_at = $1::timestamptz
WHERE status = $2::text
  AND ($3::bigint = 0 OR school_id = $3::bigint)
`

type RetryAllOutboxParams struct {
	Now      pgtype.Timestamptz `json:"now"`
	Status   string             `json:"status"`
	SchoolID int64              `json:"school_id"`
}

func (q *Queries) RetryAllOutbox(ctx context.Context, arg RetryAllOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryAllOutbox, arg.Now, arg.Status, arg.SchoolID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryOutboxRow = `-- name: RetryOutboxRow :exec
UPDATE notification_outbox SET status = 'pending', next_retry_at = $1::timestamptz
WHERE id = $2::bigint
`

type RetryOutboxRowParams struct {
	Now pgtype.Timestamptz `json:"now"`
	ID  int64              `json:"id"`
}

// attempts SENGAJA tidak diubah (task: "attempts tetap") — next_retry_at=now
// supaya ListDueOutbox (worker existing, internal/notification) langsung
// mengambilnya di poll berikutnya (status IN ('pending','failed') DAN
// next_retry_at <= now()).
func (q *Queries) RetryOutboxRow(ctx context.Context, arg RetryOutboxRowParams) error {
	_, err := q.db.Exec(ctx, retryOutboxRow, arg.Now, arg.ID)
	return err
}

const schoolExistsByID = `-- name: SchoolExistsByID :one

SELECT EXISTS(SELECT 1 FROM schools WHERE id = $1::bigint)
`

// -- P2.2 (fase 13 Gelombang 2): GET /api/admin/schools/{id}/onboarding --
func (q *Queries) SchoolExistsByID(ctx context.Context, schoolID int64) (bool, error) {
	row := q.db.QueryRow(ctx, schoolExistsByID, schoolID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const schoolOnboardingStatus = `-- name: SchoolOnboardingStatus :one
SELECT
    EXISTS(SELECT 1 FROM academic_years WHERE school_id = $1::bigint AND is_active) AS has_active_year,
    EXISTS(SELECT 1 FROM memberships WHERE school_id = $1::bigint AND role = 'admin_sekolah' AND status = 'active') AS has_admin,
    EXISTS(SELECT 1 FROM subscriptions WHERE school_id = $1::bigint AND status = 'active') AS has_subscription_active,
    EXISTS(SELECT 1 FROM students WHERE school_id = $1::bigint AND status = 'active') AS has_students,
    EXISTS(SELECT 1 FROM schedule_slots WHERE school_id = $1::bigint) AS has_schedule
`

type SchoolOnboardingStatusRow struct {
	HasActiveYear         bool `json:"has_active_year"`
	HasAdmin              bool `json:"has_admin"`
	HasSubscriptionActive bool `json:"has_subscription_active"`
	HasStudents           bool `json:"has_students"`
	HasSchedule           bool `json:"has_schedule"`
}

// Satu baris agregasi lintas modul (tenant/identity/billing/student/schedule)
// — DIPERBOLEHKAN eksplisit utk modul agregator (lihat catatan desain
// package doc), sama pola dengan ListSchoolsOverview di atas.
func (q *Queries) SchoolOnboardingStatus(ctx context.Context, schoolID int64) (SchoolOnboardingStatusRow, error) {
	row := q.db.QueryRow(ctx, schoolOnboardingStatus, schoolID)
	var i SchoolOnboardingStatusRow
	err := row.Scan(
		&i.HasActiveYear,
		&i.HasAdmin,
		&i.HasSubscriptionActive,
		&i.HasStudents,
		&i.HasSchedule,
	)
	return i, err
}

const sumRevenueInRange = `-- name: SumRevenueInRange :one
SELECT COALESCE(SUM(amount), 0)::bigint FROM invoices
WHERE status = 'paid' AND paid_at >= $1::timestamptz AND paid_at < $2::timestamptz
`

type SumRevenueInRangeParams struct {
	FromAt pgtype.Timestamptz `json:"from_at"`
	ToAt   pgtype.Timestamptz `json:"to_at"`
}

func (q *Queries) SumRevenueInRange(ctx context.Context, arg SumRevenueInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumRevenueInRange, arg.FromAt, arg.ToAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updatePlatformAnnouncement = `-- name: UpdatePlatformAnnouncement :one
UPDATE platform_announcements
SET title = $1::text, body = $2::text, starts_at = $3::date, ends_at = $4::date
WHERE id = $5::bigint
RETURNING id, title, body, starts_at, ends_at, created_by, created_at
`

type UpdatePlatformAnnouncementParams struct {
	Title    string      `json:"title"`
	Body     string      `json:"body"`
	StartsAt pgtype.Date `json:"starts_at"`
	EndsAt   pgtype.Date `json:"ends_at"`
	ID       int64       `json:"id"`
}

func (q *Queries) UpdatePlatformAnnouncement(ctx context.Context, arg UpdatePlatformAnnouncementParams) (PlatformAnnouncement, error) {
	row := q.db.QueryRow(ctx, updatePlatformAnnouncement,
		arg.Title,
		arg.Body,
		arg.StartsAt,
		arg.EndsAt,
		arg.ID,
	)
	var i PlatformAnnouncement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
