// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package billingdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveStudentsForSchool = `-- name: CountActiveStudentsForSchool :one

SELECT COUNT(*) FROM students WHERE school_id = $1 AND status = 'active'
`

// -- lookup lintas-modul read-only --
func (q *Queries) CountActiveStudentsForSchool(ctx context.Context, schoolID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveStudentsForSchool, schoolID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGatewayPayment = `-- name: CreateGatewayPayment :one
INSERT INTO payments (invoice_id, method, amount, provider, provider_ref)
VALUES ($1, 'gateway', $2, $3, $4)
RETURNING id, invoice_id, method, amount, proof_url, verified_by, verified_at, provider, provider_ref, raw_webhook, created_at
`

type CreateGatewayPaymentParams struct {
	InvoiceID   int64       `json:"invoice_id"`
	Amount      int64       `json:"amount"`
	Provider    pgtype.Text `json:"provider"`
	ProviderRef pgtype.Text `json:"provider_ref"`
}

func (q *Queries) CreateGatewayPayment(ctx context.Context, arg CreateGatewayPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createGatewayPayment,
		arg.InvoiceID,
		arg.Amount,
		arg.Provider,
		arg.ProviderRef,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Method,
		&i.Amount,
		&i.ProofUrl,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.Provider,
		&i.ProviderRef,
		&i.RawWebhook,
		&i.CreatedAt,
	)
	return i, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (school_id, number, subscription_id, amount, status, due_at, plan_code, max_students, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, school_id, number, subscription_id, amount, status, due_at, paid_at, plan_code, max_students, created_by, created_at
`

type CreateInvoiceParams struct {
	SchoolID       int64              `json:"school_id"`
	Number         string             `json:"number"`
	SubscriptionID pgtype.Int8        `json:"subscription_id"`
	Amount         int64              `json:"amount"`
	Status         string             `json:"status"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	PlanCode       string             `json:"plan_code"`
	MaxStudents    int32              `json:"max_students"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.SchoolID,
		arg.Number,
		arg.SubscriptionID,
		arg.Amount,
		arg.Status,
		arg.DueAt,
		arg.PlanCode,
		arg.MaxStudents,
		arg.CreatedBy,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Number,
		&i.SubscriptionID,
		&i.Amount,
		&i.Status,
		&i.DueAt,
		&i.PaidAt,
		&i.PlanCode,
		&i.MaxStudents,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createManualPayment = `-- name: CreateManualPayment :one

INSERT INTO payments (invoice_id, method, amount, proof_url)
VALUES ($1, 'manual_transfer', $2, $3)
RETURNING id, invoice_id, method, amount, proof_url, verified_by, verified_at, provider, provider_ref, raw_webhook, created_at
`

type CreateManualPaymentParams struct {
	InvoiceID int64       `json:"invoice_id"`
	Amount    int64       `json:"amount"`
	ProofUrl  pgtype.Text `json:"proof_url"`
}

// -- payments --
func (q *Queries) CreateManualPayment(ctx context.Context, arg CreateManualPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createManualPayment, arg.InvoiceID, arg.Amount, arg.ProofUrl)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Method,
		&i.Amount,
		&i.ProofUrl,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.Provider,
		&i.ProviderRef,
		&i.RawWebhook,
		&i.CreatedAt,
	)
	return i, err
}

const deletePlanPricesNotIn = `-- name: DeletePlanPricesNotIn :exec
DELETE FROM plan_prices WHERE plan_id = $1 AND max_students != ALL($2::int[])
`

type DeletePlanPricesNotInParams struct {
	PlanID int64   `json:"plan_id"`
	Keep   []int32 `json:"keep"`
}

func (q *Queries) DeletePlanPricesNotIn(ctx context.Context, arg DeletePlanPricesNotInParams) error {
	_, err := q.db.Exec(ctx, deletePlanPricesNotIn, arg.PlanID, arg.Keep)
	return err
}

const extendSubscription = `-- name: ExtendSubscription :exec
UPDATE subscriptions SET ends_on = ends_on + make_interval(days => $1::int), status = 'active'
WHERE school_id = $2::bigint
`

type ExtendSubscriptionParams struct {
	Days     int32 `json:"days"`
	SchoolID int64 `json:"school_id"`
}

// Goodwill (super admin) — memperpanjang ends_on tanpa mengubah plan/harga.
func (q *Queries) ExtendSubscription(ctx context.Context, arg ExtendSubscriptionParams) error {
	_, err := q.db.Exec(ctx, extendSubscription, arg.Days, arg.SchoolID)
	return err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, school_id, number, subscription_id, amount, status, due_at, paid_at, plan_code, max_students, created_by, created_at FROM invoices WHERE id = $1
`

func (q *Queries) GetInvoiceByID(ctx context.Context, id int64) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Number,
		&i.SubscriptionID,
		&i.Amount,
		&i.Status,
		&i.DueAt,
		&i.PaidAt,
		&i.PlanCode,
		&i.MaxStudents,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoiceByIDForSchool = `-- name: GetInvoiceByIDForSchool :one
SELECT id, school_id, number, subscription_id, amount, status, due_at, paid_at, plan_code, max_students, created_by, created_at FROM invoices WHERE id = $1 AND school_id = $2
`

type GetInvoiceByIDForSchoolParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) GetInvoiceByIDForSchool(ctx context.Context, arg GetInvoiceByIDForSchoolParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByIDForSchool, arg.ID, arg.SchoolID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Number,
		&i.SubscriptionID,
		&i.Amount,
		&i.Status,
		&i.DueAt,
		&i.PaidAt,
		&i.PlanCode,
		&i.MaxStudents,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestPaymentForInvoice = `-- name: GetLatestPaymentForInvoice :one
SELECT id, invoice_id, method, amount, proof_url, verified_by, verified_at, provider, provider_ref, raw_webhook, created_at FROM payments WHERE invoice_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestPaymentForInvoice(ctx context.Context, invoiceID int64) (Payment, error) {
	row := q.db.QueryRow(ctx, getLatestPaymentForInvoice, invoiceID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Method,
		&i.Amount,
		&i.ProofUrl,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.Provider,
		&i.ProviderRef,
		&i.RawWebhook,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByProviderRef = `-- name: GetPaymentByProviderRef :one
SELECT id, invoice_id, method, amount, proof_url, verified_by, verified_at, provider, provider_ref, raw_webhook, created_at FROM payments WHERE provider_ref = $1
`

func (q *Queries) GetPaymentByProviderRef(ctx context.Context, providerRef pgtype.Text) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderRef, providerRef)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Method,
		&i.Amount,
		&i.ProofUrl,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.Provider,
		&i.ProviderRef,
		&i.RawWebhook,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanByCode = `-- name: GetPlanByCode :one
SELECT id, code, name, features, active FROM plans WHERE code = $1
`

func (q *Queries) GetPlanByCode(ctx context.Context, code string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByCode, code)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Features,
		&i.Active,
	)
	return i, err
}

const getSubscriptionBySchool = `-- name: GetSubscriptionBySchool :one

SELECT id, school_id, plan_code, features, max_students, price, starts_on, ends_on, status FROM subscriptions WHERE school_id = $1
`

// -- subscriptions --
func (q *Queries) GetSubscriptionBySchool(ctx context.Context, schoolID int64) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionBySchool, schoolID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.PlanCode,
		&i.Features,
		&i.MaxStudents,
		&i.Price,
		&i.StartsOn,
		&i.EndsOn,
		&i.Status,
	)
	return i, err
}

const listInvoicesForSchool = `-- name: ListInvoicesForSchool :many
SELECT id, school_id, number, subscription_id, amount, status, due_at, paid_at, plan_code, max_students, created_by, created_at FROM invoices WHERE school_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInvoicesForSchool(ctx context.Context, schoolID int64) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesForSchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Number,
			&i.SubscriptionID,
			&i.Amount,
			&i.Status,
			&i.DueAt,
			&i.PaidAt,
			&i.PlanCode,
			&i.MaxStudents,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsForInvoice = `-- name: ListPaymentsForInvoice :many
SELECT id, invoice_id, method, amount, proof_url, verified_by, verified_at, provider, provider_ref, raw_webhook, created_at FROM payments WHERE invoice_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPaymentsForInvoice(ctx context.Context, invoiceID int64) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsForInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Method,
			&i.Amount,
			&i.ProofUrl,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.Provider,
			&i.ProviderRef,
			&i.RawWebhook,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanPrices = `-- name: ListPlanPrices :many
SELECT id, plan_id, max_students, price_yearly FROM plan_prices WHERE plan_id = $1 ORDER BY max_students
`

func (q *Queries) ListPlanPrices(ctx context.Context, planID int64) ([]PlanPrice, error) {
	rows, err := q.db.Query(ctx, listPlanPrices, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanPrice
	for rows.Next() {
		var i PlanPrice
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.MaxStudents,
			&i.PriceYearly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many

SELECT id, code, name, features, active FROM plans ORDER BY id
`

// Query modul billing (sqlc). Semua query tenant-scoped WAJIB filter school_id
// (kecuali query lintas-sekolah utk panel super admin, ditandai eksplisit).
func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Features,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsForAdmin = `-- name: ListSubscriptionsForAdmin :many
SELECT s.id, s.school_id, s.plan_code, s.features, s.max_students, s.price, s.starts_on, s.ends_on, s.status, sc.name AS school_name, sc.slug AS school_slug
FROM subscriptions s
JOIN schools sc ON sc.id = s.school_id
ORDER BY sc.name
`

type ListSubscriptionsForAdminRow struct {
	ID          int64       `json:"id"`
	SchoolID    int64       `json:"school_id"`
	PlanCode    string      `json:"plan_code"`
	Features    []byte      `json:"features"`
	MaxStudents int32       `json:"max_students"`
	Price       int64       `json:"price"`
	StartsOn    pgtype.Date `json:"starts_on"`
	EndsOn      pgtype.Date `json:"ends_on"`
	Status      string      `json:"status"`
	SchoolName  string      `json:"school_name"`
	SchoolSlug  string      `json:"school_slug"`
}

// Lintas-sekolah (panel super admin): daftar status semua sekolah.
func (q *Queries) ListSubscriptionsForAdmin(ctx context.Context) ([]ListSubscriptionsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionsForAdminRow
	for rows.Next() {
		var i ListSubscriptionsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.PlanCode,
			&i.Features,
			&i.MaxStudents,
			&i.Price,
			&i.StartsOn,
			&i.EndsOn,
			&i.Status,
			&i.SchoolName,
			&i.SchoolSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextInvoiceSeq = `-- name: NextInvoiceSeq :one

INSERT INTO invoice_number_counters (year, seq) VALUES ($1, 1)
ON CONFLICT (year) DO UPDATE SET seq = invoice_number_counters.seq + 1
RETURNING seq
`

// -- invoices --
func (q *Queries) NextInvoiceSeq(ctx context.Context, year string) (int32, error) {
	row := q.db.QueryRow(ctx, nextInvoiceSeq, year)
	var seq int32
	err := row.Scan(&seq)
	return seq, err
}

const setInvoicePaid = `-- name: SetInvoicePaid :exec
UPDATE invoices SET status = 'paid', paid_at = $2 WHERE id = $1
`

type SetInvoicePaidParams struct {
	ID     int64              `json:"id"`
	PaidAt pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) SetInvoicePaid(ctx context.Context, arg SetInvoicePaidParams) error {
	_, err := q.db.Exec(ctx, setInvoicePaid, arg.ID, arg.PaidAt)
	return err
}

const setInvoiceStatus = `-- name: SetInvoiceStatus :exec
UPDATE invoices SET status = $2 WHERE id = $1
`

type SetInvoiceStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetInvoiceStatus(ctx context.Context, arg SetInvoiceStatusParams) error {
	_, err := q.db.Exec(ctx, setInvoiceStatus, arg.ID, arg.Status)
	return err
}

const setInvoiceSubscriptionID = `-- name: SetInvoiceSubscriptionID :exec
UPDATE invoices SET subscription_id = $2 WHERE id = $1
`

type SetInvoiceSubscriptionIDParams struct {
	ID             int64       `json:"id"`
	SubscriptionID pgtype.Int8 `json:"subscription_id"`
}

func (q *Queries) SetInvoiceSubscriptionID(ctx context.Context, arg SetInvoiceSubscriptionIDParams) error {
	_, err := q.db.Exec(ctx, setInvoiceSubscriptionID, arg.ID, arg.SubscriptionID)
	return err
}

const setPaymentRawWebhook = `-- name: SetPaymentRawWebhook :exec
UPDATE payments SET raw_webhook = $2 WHERE id = $1
`

type SetPaymentRawWebhookParams struct {
	ID         int64  `json:"id"`
	RawWebhook []byte `json:"raw_webhook"`
}

func (q *Queries) SetPaymentRawWebhook(ctx context.Context, arg SetPaymentRawWebhookParams) error {
	_, err := q.db.Exec(ctx, setPaymentRawWebhook, arg.ID, arg.RawWebhook)
	return err
}

const transitionActiveToGrace = `-- name: TransitionActiveToGrace :many
UPDATE subscriptions SET status = 'grace' WHERE status = 'active' AND ends_on < $1::date
RETURNING school_id
`

// RETURNING school_id (bukan :execrows) — Fase 12 (realtime): TickOnce perlu
// tahu SEKOLAH MANA yang baru transisi supaya event "billing" bisa
// ditargetkan per sekolah (Hub per sekolah, lihat internal/realtime), bukan
// disiarkan ke semua sekolah sekaligus.
func (q *Queries) TransitionActiveToGrace(ctx context.Context, today pgtype.Date) ([]int64, error) {
	rows, err := q.db.Query(ctx, transitionActiveToGrace, today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var school_id int64
		if err := rows.Scan(&school_id); err != nil {
			return nil, err
		}
		items = append(items, school_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionGraceToReadonly = `-- name: TransitionGraceToReadonly :many
UPDATE subscriptions SET status = 'readonly' WHERE status = 'grace' AND (ends_on + make_interval(days => $1::int)) < $2::date
RETURNING school_id
`

type TransitionGraceToReadonlyParams struct {
	GraceDays int32       `json:"grace_days"`
	Today     pgtype.Date `json:"today"`
}

// RETURNING school_id — lihat catatan TransitionActiveToGrace di atas.
func (q *Queries) TransitionGraceToReadonly(ctx context.Context, arg TransitionGraceToReadonlyParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, transitionGraceToReadonly, arg.GraceDays, arg.Today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var school_id int64
		if err := rows.Scan(&school_id); err != nil {
			return nil, err
		}
		items = append(items, school_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlanFeatures = `-- name: UpdatePlanFeatures :exec
UPDATE plans SET features = $2 WHERE code = $1
`

type UpdatePlanFeaturesParams struct {
	Code     string `json:"code"`
	Features []byte `json:"features"`
}

func (q *Queries) UpdatePlanFeatures(ctx context.Context, arg UpdatePlanFeaturesParams) error {
	_, err := q.db.Exec(ctx, updatePlanFeatures, arg.Code, arg.Features)
	return err
}

const updatePlanName = `-- name: UpdatePlanName :exec
UPDATE plans SET name = $2 WHERE code = $1
`

type UpdatePlanNameParams struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) UpdatePlanName(ctx context.Context, arg UpdatePlanNameParams) error {
	_, err := q.db.Exec(ctx, updatePlanName, arg.Code, arg.Name)
	return err
}

const upsertPlanPrice = `-- name: UpsertPlanPrice :exec
INSERT INTO plan_prices (plan_id, max_students, price_yearly)
VALUES ($1, $2, $3)
ON CONFLICT (plan_id, max_students) DO UPDATE SET price_yearly = EXCLUDED.price_yearly
`

type UpsertPlanPriceParams struct {
	PlanID      int64 `json:"plan_id"`
	MaxStudents int32 `json:"max_students"`
	PriceYearly int64 `json:"price_yearly"`
}

func (q *Queries) UpsertPlanPrice(ctx context.Context, arg UpsertPlanPriceParams) error {
	_, err := q.db.Exec(ctx, upsertPlanPrice, arg.PlanID, arg.MaxStudents, arg.PriceYearly)
	return err
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO subscriptions (school_id, plan_code, features, max_students, price, starts_on, ends_on, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (school_id) DO UPDATE SET
    plan_code = EXCLUDED.plan_code,
    features = EXCLUDED.features,
    max_students = EXCLUDED.max_students,
    price = EXCLUDED.price,
    starts_on = EXCLUDED.starts_on,
    ends_on = EXCLUDED.ends_on,
    status = EXCLUDED.status
RETURNING id, school_id, plan_code, features, max_students, price, starts_on, ends_on, status
`

type UpsertSubscriptionParams struct {
	SchoolID    int64       `json:"school_id"`
	PlanCode    string      `json:"plan_code"`
	Features    []byte      `json:"features"`
	MaxStudents int32       `json:"max_students"`
	Price       int64       `json:"price"`
	StartsOn    pgtype.Date `json:"starts_on"`
	EndsOn      pgtype.Date `json:"ends_on"`
	Status      string      `json:"status"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.SchoolID,
		arg.PlanCode,
		arg.Features,
		arg.MaxStudents,
		arg.Price,
		arg.StartsOn,
		arg.EndsOn,
		arg.Status,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.PlanCode,
		&i.Features,
		&i.MaxStudents,
		&i.Price,
		&i.StartsOn,
		&i.EndsOn,
		&i.Status,
	)
	return i, err
}

const verifyManualPayment = `-- name: VerifyManualPayment :exec
UPDATE payments SET verified_by = $2, verified_at = $3 WHERE id = $1
`

type VerifyManualPaymentParams struct {
	ID         int64              `json:"id"`
	VerifiedBy pgtype.Int8        `json:"verified_by"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) VerifyManualPayment(ctx context.Context, arg VerifyManualPaymentParams) error {
	_, err := q.db.Exec(ctx, verifyManualPayment, arg.ID, arg.VerifiedBy, arg.VerifiedAt)
	return err
}
