// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package notificationdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOutboxByChannel = `-- name: CountOutboxByChannel :one
SELECT COUNT(*) FROM notification_outbox WHERE school_id = $1 AND event = $2 AND channel = $3
`

type CountOutboxByChannelParams struct {
	SchoolID int64  `json:"school_id"`
	Event    string `json:"event"`
	Channel  string `json:"channel"`
}

// Dipakai verifikasi e2e/test: jumlah baris outbox utk (school,event,channel).
func (q *Queries) CountOutboxByChannel(ctx context.Context, arg CountOutboxByChannelParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOutboxByChannel, arg.SchoolID, arg.Event, arg.Channel)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE school_id = $1 AND user_id = $2 AND read_at IS NULL
`

type CountUnreadNotificationsParams struct {
	SchoolID int64 `json:"school_id"`
	UserID   int64 `json:"user_id"`
}

func (q *Queries) CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, arg.SchoolID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePushSubscriptionByEndpoint = `-- name: DeletePushSubscriptionByEndpoint :exec
DELETE FROM push_subscriptions WHERE endpoint = $1
`

func (q *Queries) DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error {
	_, err := q.db.Exec(ctx, deletePushSubscriptionByEndpoint, endpoint)
	return err
}

const deletePushSubscriptionByUserEndpoint = `-- name: DeletePushSubscriptionByUserEndpoint :execrows
DELETE FROM push_subscriptions WHERE school_id = $1::bigint AND user_id = $2::bigint AND endpoint = $3::text
`

type DeletePushSubscriptionByUserEndpointParams struct {
	SchoolID int64  `json:"school_id"`
	UserID   int64  `json:"user_id"`
	Endpoint string `json:"endpoint"`
}

func (q *Queries) DeletePushSubscriptionByUserEndpoint(ctx context.Context, arg DeletePushSubscriptionByUserEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushSubscriptionByUserEndpoint, arg.SchoolID, arg.UserID, arg.Endpoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNotificationSettingsRaw = `-- name: GetNotificationSettingsRaw :one

SELECT settings FROM school_settings WHERE school_id = $1 AND module = 'notification'
`

// Query modul notification (sqlc). Semua query tenant-scoped WAJIB filter
// school_id. Join read-only ke users (dimiliki modul identity) dipakai untuk
// resolusi kontak (phone/email) provider — pola yang sama dengan
// internal/leave/queries.sql & internal/attendance/queries.sql.
func (q *Queries) GetNotificationSettingsRaw(ctx context.Context, schoolID int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getNotificationSettingsRaw, schoolID)
	var settings []byte
	err := row.Scan(&settings)
	return settings, err
}

const getPlatformConfig = `-- name: GetPlatformConfig :one

SELECT value FROM platform_config WHERE key = $1
`

// -- platform_config (VAPID keys — lihat internal/notification/webpush.go) --
func (q *Queries) GetPlatformConfig(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getPlatformConfig, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getUserContact = `-- name: GetUserContact :one

SELECT id, phone, email FROM users WHERE id = $1
`

type GetUserContactRow struct {
	ID    int64       `json:"id"`
	Phone pgtype.Text `json:"phone"`
	Email pgtype.Text `json:"email"`
}

// -- kontak (join read-only ke users, dimiliki modul identity) --
func (q *Queries) GetUserContact(ctx context.Context, id int64) (GetUserContactRow, error) {
	row := q.db.QueryRow(ctx, getUserContact, id)
	var i GetUserContactRow
	err := row.Scan(&i.ID, &i.Phone, &i.Email)
	return i, err
}

const insertNotification = `-- name: InsertNotification :one

INSERT INTO notifications (school_id, user_id, event, title, body, link)
VALUES ($1, $2, $3, $4, $5, $6::text)
RETURNING id, school_id, user_id, event, title, body, link, read_at, created_at
`

type InsertNotificationParams struct {
	SchoolID int64       `json:"school_id"`
	UserID   int64       `json:"user_id"`
	Event    string      `json:"event"`
	Title    string      `json:"title"`
	Body     string      `json:"body"`
	Link     pgtype.Text `json:"link"`
}

// -- inbox in-app --
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.SchoolID,
		arg.UserID,
		arg.Event,
		arg.Title,
		arg.Body,
		arg.Link,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.UserID,
		&i.Event,
		&i.Title,
		&i.Body,
		&i.Link,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertOutboxRow = `-- name: InsertOutboxRow :one

INSERT INTO notification_outbox (school_id, event, user_id, channel, payload, status)
VALUES ($1, $2, $3, $4, $5, 'pending')
RETURNING id, school_id, event, user_id, channel, payload, status, attempts, next_retry_at, created_at, sent_at
`

type InsertOutboxRowParams struct {
	SchoolID int64  `json:"school_id"`
	Event    string `json:"event"`
	UserID   int64  `json:"user_id"`
	Channel  string `json:"channel"`
	Payload  []byte `json:"payload"`
}

// -- outbox --
func (q *Queries) InsertOutboxRow(ctx context.Context, arg InsertOutboxRowParams) (NotificationOutbox, error) {
	row := q.db.QueryRow(ctx, insertOutboxRow,
		arg.SchoolID,
		arg.Event,
		arg.UserID,
		arg.Channel,
		arg.Payload,
	)
	var i NotificationOutbox
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Event,
		&i.UserID,
		&i.Channel,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const listDueOutbox = `-- name: ListDueOutbox :many
SELECT id, school_id, event, user_id, channel, payload, status, attempts, next_retry_at, created_at, sent_at FROM notification_outbox
WHERE status IN ('pending', 'failed') AND (next_retry_at IS NULL OR next_retry_at <= now())
ORDER BY created_at
LIMIT $1::int
`

// Baris pending (belum pernah dicoba) ATAU failed (menunggu retry) yang
// sudah jatuh tempo (next_retry_at NULL atau <= now()) — lihat backoff di
// internal/notification/worker.go.
func (q *Queries) ListDueOutbox(ctx context.Context, limitCount int32) ([]NotificationOutbox, error) {
	rows, err := q.db.Query(ctx, listDueOutbox, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationOutbox
	for rows.Next() {
		var i NotificationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Event,
			&i.UserID,
			&i.Channel,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, school_id, user_id, event, title, body, link, read_at, created_at FROM notifications
WHERE school_id = $1::bigint AND user_id = $2::bigint
ORDER BY created_at DESC
LIMIT $4::int OFFSET $3::int
`

type ListNotificationsParams struct {
	SchoolID    int64 `json:"school_id"`
	UserID      int64 `json:"user_id"`
	OffsetCount int32 `json:"offset_count"`
	LimitCount  int32 `json:"limit_count"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.SchoolID,
		arg.UserID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.UserID,
			&i.Event,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushSubscriptionsForUser = `-- name: ListPushSubscriptionsForUser :many
SELECT id, school_id, user_id, endpoint, p256dh, auth, created_at FROM push_subscriptions WHERE school_id = $1 AND user_id = $2
`

type ListPushSubscriptionsForUserParams struct {
	SchoolID int64 `json:"school_id"`
	UserID   int64 `json:"user_id"`
}

func (q *Queries) ListPushSubscriptionsForUser(ctx context.Context, arg ListPushSubscriptionsForUserParams) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptionsForUser, arg.SchoolID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications SET read_at = now()
WHERE school_id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkAllNotificationsReadParams struct {
	SchoolID int64 `json:"school_id"`
	UserID   int64 `json:"user_id"`
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, arg.SchoolID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationsReadByIDs = `-- name: MarkNotificationsReadByIDs :execrows
UPDATE notifications SET read_at = now()
WHERE school_id = $1::bigint AND user_id = $2::bigint
  AND id = ANY($3::bigint[]) AND read_at IS NULL
`

type MarkNotificationsReadByIDsParams struct {
	SchoolID int64   `json:"school_id"`
	UserID   int64   `json:"user_id"`
	Ids      []int64 `json:"ids"`
}

func (q *Queries) MarkNotificationsReadByIDs(ctx context.Context, arg MarkNotificationsReadByIDsParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationsReadByIDs, arg.SchoolID, arg.UserID, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxDead = `-- name: MarkOutboxDead :exec
UPDATE notification_outbox SET status = 'dead', attempts = $1::int WHERE id = $2::bigint
`

type MarkOutboxDeadParams struct {
	Attempts int32 `json:"attempts"`
	ID       int64 `json:"id"`
}

func (q *Queries) MarkOutboxDead(ctx context.Context, arg MarkOutboxDeadParams) error {
	_, err := q.db.Exec(ctx, markOutboxDead, arg.Attempts, arg.ID)
	return err
}

const markOutboxRetry = `-- name: MarkOutboxRetry :exec
UPDATE notification_outbox
SET status = 'failed', attempts = $1::int, next_retry_at = $2::timestamptz
WHERE id = $3::bigint
`

type MarkOutboxRetryParams struct {
	Attempts    int32              `json:"attempts"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	ID          int64              `json:"id"`
}

func (q *Queries) MarkOutboxRetry(ctx context.Context, arg MarkOutboxRetryParams) error {
	_, err := q.db.Exec(ctx, markOutboxRetry, arg.Attempts, arg.NextRetryAt, arg.ID)
	return err
}

const markOutboxSent = `-- name: MarkOutboxSent :exec
UPDATE notification_outbox SET status = 'sent', sent_at = $1::timestamptz WHERE id = $2::bigint
`

type MarkOutboxSentParams struct {
	SentAt pgtype.Timestamptz `json:"sent_at"`
	ID     int64              `json:"id"`
}

func (q *Queries) MarkOutboxSent(ctx context.Context, arg MarkOutboxSentParams) error {
	_, err := q.db.Exec(ctx, markOutboxSent, arg.SentAt, arg.ID)
	return err
}

const upsertPlatformConfig = `-- name: UpsertPlatformConfig :exec
INSERT INTO platform_config (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
`

type UpsertPlatformConfigParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertPlatformConfig(ctx context.Context, arg UpsertPlatformConfigParams) error {
	_, err := q.db.Exec(ctx, upsertPlatformConfig, arg.Key, arg.Value)
	return err
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :one

INSERT INTO push_subscriptions (school_id, user_id, endpoint, p256dh, auth)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (endpoint) DO UPDATE SET
    school_id = EXCLUDED.school_id, user_id = EXCLUDED.user_id,
    p256dh = EXCLUDED.p256dh, auth = EXCLUDED.auth
RETURNING id, school_id, user_id, endpoint, p256dh, auth, created_at
`

type UpsertPushSubscriptionParams struct {
	SchoolID int64  `json:"school_id"`
	UserID   int64  `json:"user_id"`
	Endpoint string `json:"endpoint"`
	P256dh   string `json:"p256dh"`
	Auth     string `json:"auth"`
}

// -- push subscriptions --
func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRow(ctx, upsertPushSubscription,
		arg.SchoolID,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.CreatedAt,
	)
	return i, err
}
