// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package latearrivaldb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLateArrivalsForStudentYear = `-- name: CountLateArrivalsForStudentYear :one
SELECT count(*) FROM student_late_arrivals
WHERE school_id = $1 AND academic_year_id = $2 AND student_id = $3
`

type CountLateArrivalsForStudentYearParams struct {
	SchoolID       int64 `json:"school_id"`
	AcademicYearID int64 `json:"academic_year_id"`
	StudentID      int64 `json:"student_id"`
}

func (q *Queries) CountLateArrivalsForStudentYear(ctx context.Context, arg CountLateArrivalsForStudentYearParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLateArrivalsForStudentYear, arg.SchoolID, arg.AcademicYearID, arg.StudentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLateArrival = `-- name: CreateLateArrival :one
INSERT INTO student_late_arrivals (
    school_id, academic_year_id, student_id, arrived_at, late_count, action, status, duty_by, duty_at
) VALUES (
    $1, $2, $3, $7::timestamptz, $4, $5, 'pending_leadership', $6, $7::timestamptz
)
RETURNING id
`

type CreateLateArrivalParams struct {
	SchoolID       int64              `json:"school_id"`
	AcademicYearID int64              `json:"academic_year_id"`
	StudentID      int64              `json:"student_id"`
	LateCount      int32              `json:"late_count"`
	Action         string             `json:"action"`
	DutyBy         pgtype.Int8        `json:"duty_by"`
	ArrivedAt      pgtype.Timestamptz `json:"arrived_at"`
}

// Scan PERTAMA hari itu (docs tugas): create LANGSUNG status
// 'pending_leadership' dengan duty_by/duty_at terisi (tahap piket sudah
// lunas saat baris dibuat, TIDAK ADA baris berstatus pending_duty_teacher
// yang benar-benar tersimpan).
func (q *Queries) CreateLateArrival(ctx context.Context, arg CreateLateArrivalParams) (int64, error) {
	row := q.db.QueryRow(ctx, createLateArrival,
		arg.SchoolID,
		arg.AcademicYearID,
		arg.StudentID,
		arg.LateCount,
		arg.Action,
		arg.DutyBy,
		arg.ArrivedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getLateArrivalDetail = `-- name: GetLateArrivalDetail :one
SELECT
    la.id, la.school_id, la.academic_year_id, la.student_id, la.arrived_at, la.late_count, la.action, la.status,
    la.duty_by, la.duty_at, la.leadership_by, la.leadership_at, la.class_by, la.class_at, la.created_at,
    s.name AS student_name, s.nis AS student_nis, COALESCE(c.name, '') AS class_name,
    du.name AS duty_by_name, lu.name AS leadership_by_name, cu.name AS class_by_name
FROM student_late_arrivals la
JOIN students s ON s.id = la.student_id
LEFT JOIN enrollments en ON en.student_id = la.student_id
LEFT JOIN classes c ON c.id = en.class_id AND c.academic_year_id = la.academic_year_id
LEFT JOIN users du ON du.id = la.duty_by
LEFT JOIN users lu ON lu.id = la.leadership_by
LEFT JOIN users cu ON cu.id = la.class_by
WHERE la.id = $1 AND la.school_id = $2
LIMIT 1
`

type GetLateArrivalDetailParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetLateArrivalDetailRow struct {
	ID               int64              `json:"id"`
	SchoolID         int64              `json:"school_id"`
	AcademicYearID   int64              `json:"academic_year_id"`
	StudentID        int64              `json:"student_id"`
	ArrivedAt        pgtype.Timestamptz `json:"arrived_at"`
	LateCount        int32              `json:"late_count"`
	Action           string             `json:"action"`
	Status           string             `json:"status"`
	DutyBy           pgtype.Int8        `json:"duty_by"`
	DutyAt           pgtype.Timestamptz `json:"duty_at"`
	LeadershipBy     pgtype.Int8        `json:"leadership_by"`
	LeadershipAt     pgtype.Timestamptz `json:"leadership_at"`
	ClassBy          pgtype.Int8        `json:"class_by"`
	ClassAt          pgtype.Timestamptz `json:"class_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	StudentName      string             `json:"student_name"`
	StudentNis       string             `json:"student_nis"`
	ClassName        string             `json:"class_name"`
	DutyByName       pgtype.Text        `json:"duty_by_name"`
	LeadershipByName pgtype.Text        `json:"leadership_by_name"`
	ClassByName      pgtype.Text        `json:"class_by_name"`
}

func (q *Queries) GetLateArrivalDetail(ctx context.Context, arg GetLateArrivalDetailParams) (GetLateArrivalDetailRow, error) {
	row := q.db.QueryRow(ctx, getLateArrivalDetail, arg.ID, arg.SchoolID)
	var i GetLateArrivalDetailRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.StudentID,
		&i.ArrivedAt,
		&i.LateCount,
		&i.Action,
		&i.Status,
		&i.DutyBy,
		&i.DutyAt,
		&i.LeadershipBy,
		&i.LeadershipAt,
		&i.ClassBy,
		&i.ClassAt,
		&i.CreatedAt,
		&i.StudentName,
		&i.StudentNis,
		&i.ClassName,
		&i.DutyByName,
		&i.LeadershipByName,
		&i.ClassByName,
	)
	return i, err
}

const getTodayLateArrivalForStudent = `-- name: GetTodayLateArrivalForStudent :one
SELECT
    la.id, la.school_id, la.academic_year_id, la.student_id, la.arrived_at, la.late_count, la.action, la.status,
    la.duty_by, la.duty_at, la.leadership_by, la.leadership_at, la.class_by, la.class_at, la.created_at,
    s.name AS student_name, s.nis AS student_nis, COALESCE(c.name, '') AS class_name,
    du.name AS duty_by_name, lu.name AS leadership_by_name, cu.name AS class_by_name
FROM student_late_arrivals la
JOIN students s ON s.id = la.student_id
LEFT JOIN enrollments en ON en.student_id = la.student_id
LEFT JOIN classes c ON c.id = en.class_id AND c.academic_year_id = la.academic_year_id
LEFT JOIN users du ON du.id = la.duty_by
LEFT JOIN users lu ON lu.id = la.leadership_by
LEFT JOIN users cu ON cu.id = la.class_by
WHERE la.school_id = $1 AND la.student_id = $2
  AND la.arrived_at >= $3::timestamptz AND la.arrived_at < $4::timestamptz
ORDER BY la.arrived_at DESC
LIMIT 1
`

type GetTodayLateArrivalForStudentParams struct {
	SchoolID  int64              `json:"school_id"`
	StudentID int64              `json:"student_id"`
	FromAt    pgtype.Timestamptz `json:"from_at"`
	ToAt      pgtype.Timestamptz `json:"to_at"`
}

type GetTodayLateArrivalForStudentRow struct {
	ID               int64              `json:"id"`
	SchoolID         int64              `json:"school_id"`
	AcademicYearID   int64              `json:"academic_year_id"`
	StudentID        int64              `json:"student_id"`
	ArrivedAt        pgtype.Timestamptz `json:"arrived_at"`
	LateCount        int32              `json:"late_count"`
	Action           string             `json:"action"`
	Status           string             `json:"status"`
	DutyBy           pgtype.Int8        `json:"duty_by"`
	DutyAt           pgtype.Timestamptz `json:"duty_at"`
	LeadershipBy     pgtype.Int8        `json:"leadership_by"`
	LeadershipAt     pgtype.Timestamptz `json:"leadership_at"`
	ClassBy          pgtype.Int8        `json:"class_by"`
	ClassAt          pgtype.Timestamptz `json:"class_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	StudentName      string             `json:"student_name"`
	StudentNis       string             `json:"student_nis"`
	ClassName        string             `json:"class_name"`
	DutyByName       pgtype.Text        `json:"duty_by_name"`
	LeadershipByName pgtype.Text        `json:"leadership_by_name"`
	ClassByName      pgtype.Text        `json:"class_by_name"`
}

// Rentang UTC "hari ini lokal sekolah" diteruskan service (docs tugas: maks
// 1 record per siswa per hari).
func (q *Queries) GetTodayLateArrivalForStudent(ctx context.Context, arg GetTodayLateArrivalForStudentParams) (GetTodayLateArrivalForStudentRow, error) {
	row := q.db.QueryRow(ctx, getTodayLateArrivalForStudent,
		arg.SchoolID,
		arg.StudentID,
		arg.FromAt,
		arg.ToAt,
	)
	var i GetTodayLateArrivalForStudentRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.StudentID,
		&i.ArrivedAt,
		&i.LateCount,
		&i.Action,
		&i.Status,
		&i.DutyBy,
		&i.DutyAt,
		&i.LeadershipBy,
		&i.LeadershipAt,
		&i.ClassBy,
		&i.ClassAt,
		&i.CreatedAt,
		&i.StudentName,
		&i.StudentNis,
		&i.ClassName,
		&i.DutyByName,
		&i.LeadershipByName,
		&i.ClassByName,
	)
	return i, err
}

const listLateArrivalsAll = `-- name: ListLateArrivalsAll :many
SELECT
    la.id, la.school_id, la.academic_year_id, la.student_id, la.arrived_at, la.late_count, la.action, la.status,
    la.duty_by, la.duty_at, la.leadership_by, la.leadership_at, la.class_by, la.class_at, la.created_at,
    s.name AS student_name, s.nis AS student_nis, COALESCE(c.name, '') AS class_name,
    du.name AS duty_by_name, lu.name AS leadership_by_name, cu.name AS class_by_name
FROM student_late_arrivals la
JOIN students s ON s.id = la.student_id
LEFT JOIN enrollments en ON en.student_id = la.student_id
LEFT JOIN classes c ON c.id = en.class_id AND c.academic_year_id = la.academic_year_id
LEFT JOIN users du ON du.id = la.duty_by
LEFT JOIN users lu ON lu.id = la.leadership_by
LEFT JOIN users cu ON cu.id = la.class_by
WHERE la.school_id = $1
  AND ($2::timestamptz IS NULL OR la.arrived_at >= $2)
  AND ($3::timestamptz IS NULL OR la.arrived_at < $3)
ORDER BY la.arrived_at DESC
`

type ListLateArrivalsAllParams struct {
	SchoolID int64              `json:"school_id"`
	FromAt   pgtype.Timestamptz `json:"from_at"`
	ToAt     pgtype.Timestamptz `json:"to_at"`
}

type ListLateArrivalsAllRow struct {
	ID               int64              `json:"id"`
	SchoolID         int64              `json:"school_id"`
	AcademicYearID   int64              `json:"academic_year_id"`
	StudentID        int64              `json:"student_id"`
	ArrivedAt        pgtype.Timestamptz `json:"arrived_at"`
	LateCount        int32              `json:"late_count"`
	Action           string             `json:"action"`
	Status           string             `json:"status"`
	DutyBy           pgtype.Int8        `json:"duty_by"`
	DutyAt           pgtype.Timestamptz `json:"duty_at"`
	LeadershipBy     pgtype.Int8        `json:"leadership_by"`
	LeadershipAt     pgtype.Timestamptz `json:"leadership_at"`
	ClassBy          pgtype.Int8        `json:"class_by"`
	ClassAt          pgtype.Timestamptz `json:"class_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	StudentName      string             `json:"student_name"`
	StudentNis       string             `json:"student_nis"`
	ClassName        string             `json:"class_name"`
	DutyByName       pgtype.Text        `json:"duty_by_name"`
	LeadershipByName pgtype.Text        `json:"leadership_by_name"`
	ClassByName      pgtype.Text        `json:"class_by_name"`
}

func (q *Queries) ListLateArrivalsAll(ctx context.Context, arg ListLateArrivalsAllParams) ([]ListLateArrivalsAllRow, error) {
	rows, err := q.db.Query(ctx, listLateArrivalsAll, arg.SchoolID, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLateArrivalsAllRow
	for rows.Next() {
		var i ListLateArrivalsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.AcademicYearID,
			&i.StudentID,
			&i.ArrivedAt,
			&i.LateCount,
			&i.Action,
			&i.Status,
			&i.DutyBy,
			&i.DutyAt,
			&i.LeadershipBy,
			&i.LeadershipAt,
			&i.ClassBy,
			&i.ClassAt,
			&i.CreatedAt,
			&i.StudentName,
			&i.StudentNis,
			&i.ClassName,
			&i.DutyByName,
			&i.LeadershipByName,
			&i.ClassByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLateArrivalsForStudents = `-- name: ListLateArrivalsForStudents :many
SELECT
    la.id, la.school_id, la.academic_year_id, la.student_id, la.arrived_at, la.late_count, la.action, la.status,
    la.duty_by, la.duty_at, la.leadership_by, la.leadership_at, la.class_by, la.class_at, la.created_at,
    s.name AS student_name, s.nis AS student_nis, COALESCE(c.name, '') AS class_name,
    du.name AS duty_by_name, lu.name AS leadership_by_name, cu.name AS class_by_name
FROM student_late_arrivals la
JOIN students s ON s.id = la.student_id
LEFT JOIN enrollments en ON en.student_id = la.student_id
LEFT JOIN classes c ON c.id = en.class_id AND c.academic_year_id = la.academic_year_id
LEFT JOIN users du ON du.id = la.duty_by
LEFT JOIN users lu ON lu.id = la.leadership_by
LEFT JOIN users cu ON cu.id = la.class_by
WHERE la.school_id = $1 AND la.student_id = ANY($2::bigint[])
  AND ($3::timestamptz IS NULL OR la.arrived_at >= $3)
  AND ($4::timestamptz IS NULL OR la.arrived_at < $4)
ORDER BY la.arrived_at DESC
`

type ListLateArrivalsForStudentsParams struct {
	SchoolID   int64              `json:"school_id"`
	StudentIds []int64            `json:"student_ids"`
	FromAt     pgtype.Timestamptz `json:"from_at"`
	ToAt       pgtype.Timestamptz `json:"to_at"`
}

type ListLateArrivalsForStudentsRow struct {
	ID               int64              `json:"id"`
	SchoolID         int64              `json:"school_id"`
	AcademicYearID   int64              `json:"academic_year_id"`
	StudentID        int64              `json:"student_id"`
	ArrivedAt        pgtype.Timestamptz `json:"arrived_at"`
	LateCount        int32              `json:"late_count"`
	Action           string             `json:"action"`
	Status           string             `json:"status"`
	DutyBy           pgtype.Int8        `json:"duty_by"`
	DutyAt           pgtype.Timestamptz `json:"duty_at"`
	LeadershipBy     pgtype.Int8        `json:"leadership_by"`
	LeadershipAt     pgtype.Timestamptz `json:"leadership_at"`
	ClassBy          pgtype.Int8        `json:"class_by"`
	ClassAt          pgtype.Timestamptz `json:"class_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	StudentName      string             `json:"student_name"`
	StudentNis       string             `json:"student_nis"`
	ClassName        string             `json:"class_name"`
	DutyByName       pgtype.Text        `json:"duty_by_name"`
	LeadershipByName pgtype.Text        `json:"leadership_by_name"`
	ClassByName      pgtype.Text        `json:"class_by_name"`
}

func (q *Queries) ListLateArrivalsForStudents(ctx context.Context, arg ListLateArrivalsForStudentsParams) ([]ListLateArrivalsForStudentsRow, error) {
	rows, err := q.db.Query(ctx, listLateArrivalsForStudents,
		arg.SchoolID,
		arg.StudentIds,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLateArrivalsForStudentsRow
	for rows.Next() {
		var i ListLateArrivalsForStudentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.AcademicYearID,
			&i.StudentID,
			&i.ArrivedAt,
			&i.LateCount,
			&i.Action,
			&i.Status,
			&i.DutyBy,
			&i.DutyAt,
			&i.LeadershipBy,
			&i.LeadershipAt,
			&i.ClassBy,
			&i.ClassAt,
			&i.CreatedAt,
			&i.StudentName,
			&i.StudentNis,
			&i.ClassName,
			&i.DutyByName,
			&i.LeadershipByName,
			&i.ClassByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLateArrivalsToday = `-- name: ListLateArrivalsToday :many
SELECT
    la.id, la.school_id, la.academic_year_id, la.student_id, la.arrived_at, la.late_count, la.action, la.status,
    la.duty_by, la.duty_at, la.leadership_by, la.leadership_at, la.class_by, la.class_at, la.created_at,
    s.name AS student_name, s.nis AS student_nis, COALESCE(c.name, '') AS class_name,
    du.name AS duty_by_name, lu.name AS leadership_by_name, cu.name AS class_by_name
FROM student_late_arrivals la
JOIN students s ON s.id = la.student_id
LEFT JOIN enrollments en ON en.student_id = la.student_id
LEFT JOIN classes c ON c.id = en.class_id AND c.academic_year_id = la.academic_year_id
LEFT JOIN users du ON du.id = la.duty_by
LEFT JOIN users lu ON lu.id = la.leadership_by
LEFT JOIN users cu ON cu.id = la.class_by
WHERE la.school_id = $1 AND la.arrived_at >= $2::timestamptz AND la.arrived_at < $3::timestamptz
ORDER BY la.arrived_at DESC
`

type ListLateArrivalsTodayParams struct {
	SchoolID int64              `json:"school_id"`
	FromAt   pgtype.Timestamptz `json:"from_at"`
	ToAt     pgtype.Timestamptz `json:"to_at"`
}

type ListLateArrivalsTodayRow struct {
	ID               int64              `json:"id"`
	SchoolID         int64              `json:"school_id"`
	AcademicYearID   int64              `json:"academic_year_id"`
	StudentID        int64              `json:"student_id"`
	ArrivedAt        pgtype.Timestamptz `json:"arrived_at"`
	LateCount        int32              `json:"late_count"`
	Action           string             `json:"action"`
	Status           string             `json:"status"`
	DutyBy           pgtype.Int8        `json:"duty_by"`
	DutyAt           pgtype.Timestamptz `json:"duty_at"`
	LeadershipBy     pgtype.Int8        `json:"leadership_by"`
	LeadershipAt     pgtype.Timestamptz `json:"leadership_at"`
	ClassBy          pgtype.Int8        `json:"class_by"`
	ClassAt          pgtype.Timestamptz `json:"class_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	StudentName      string             `json:"student_name"`
	StudentNis       string             `json:"student_nis"`
	ClassName        string             `json:"class_name"`
	DutyByName       pgtype.Text        `json:"duty_by_name"`
	LeadershipByName pgtype.Text        `json:"leadership_by_name"`
	ClassByName      pgtype.Text        `json:"class_by_name"`
}

func (q *Queries) ListLateArrivalsToday(ctx context.Context, arg ListLateArrivalsTodayParams) ([]ListLateArrivalsTodayRow, error) {
	rows, err := q.db.Query(ctx, listLateArrivalsToday, arg.SchoolID, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLateArrivalsTodayRow
	for rows.Next() {
		var i ListLateArrivalsTodayRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.AcademicYearID,
			&i.StudentID,
			&i.ArrivedAt,
			&i.LateCount,
			&i.Action,
			&i.Status,
			&i.DutyBy,
			&i.DutyAt,
			&i.LeadershipBy,
			&i.LeadershipAt,
			&i.ClassBy,
			&i.ClassAt,
			&i.CreatedAt,
			&i.StudentName,
			&i.StudentNis,
			&i.ClassName,
			&i.DutyByName,
			&i.LeadershipByName,
			&i.ClassByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryLateArrivalsByMonth = `-- name: SummaryLateArrivalsByMonth :many
SELECT s.id AS student_id, s.name AS student_name, s.nis AS student_nis, COALESCE(c.name, '') AS class_name,
       count(la.id) AS cnt
FROM student_late_arrivals la
JOIN students s ON s.id = la.student_id
LEFT JOIN enrollments en ON en.student_id = la.student_id
LEFT JOIN classes c ON c.id = en.class_id AND c.academic_year_id = la.academic_year_id
WHERE la.school_id = $1 AND la.arrived_at >= $2::timestamptz AND la.arrived_at < $3::timestamptz
GROUP BY s.id, s.name, s.nis, c.name
ORDER BY cnt DESC, s.name ASC
`

type SummaryLateArrivalsByMonthParams struct {
	SchoolID int64              `json:"school_id"`
	FromAt   pgtype.Timestamptz `json:"from_at"`
	ToAt     pgtype.Timestamptz `json:"to_at"`
}

type SummaryLateArrivalsByMonthRow struct {
	StudentID   int64  `json:"student_id"`
	StudentName string `json:"student_name"`
	StudentNis  string `json:"student_nis"`
	ClassName   string `json:"class_name"`
	Cnt         int64  `json:"cnt"`
}

func (q *Queries) SummaryLateArrivalsByMonth(ctx context.Context, arg SummaryLateArrivalsByMonthParams) ([]SummaryLateArrivalsByMonthRow, error) {
	rows, err := q.db.Query(ctx, summaryLateArrivalsByMonth, arg.SchoolID, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummaryLateArrivalsByMonthRow
	for rows.Next() {
		var i SummaryLateArrivalsByMonthRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentName,
			&i.StudentNis,
			&i.ClassName,
			&i.Cnt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLateArrivalClassStage = `-- name: UpdateLateArrivalClassStage :execrows
UPDATE student_late_arrivals SET status = 'completed', class_by = $3, class_at = now()
WHERE id = $1 AND school_id = $2 AND status = 'pending_class_teacher'
`

type UpdateLateArrivalClassStageParams struct {
	ID       int64       `json:"id"`
	SchoolID int64       `json:"school_id"`
	ClassBy  pgtype.Int8 `json:"class_by"`
}

func (q *Queries) UpdateLateArrivalClassStage(ctx context.Context, arg UpdateLateArrivalClassStageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLateArrivalClassStage, arg.ID, arg.SchoolID, arg.ClassBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLateArrivalLeadershipStage = `-- name: UpdateLateArrivalLeadershipStage :execrows
UPDATE student_late_arrivals SET status = 'pending_class_teacher', leadership_by = $3, leadership_at = now()
WHERE id = $1 AND school_id = $2 AND status = 'pending_leadership'
`

type UpdateLateArrivalLeadershipStageParams struct {
	ID           int64       `json:"id"`
	SchoolID     int64       `json:"school_id"`
	LeadershipBy pgtype.Int8 `json:"leadership_by"`
}

func (q *Queries) UpdateLateArrivalLeadershipStage(ctx context.Context, arg UpdateLateArrivalLeadershipStageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLateArrivalLeadershipStage, arg.ID, arg.SchoolID, arg.LeadershipBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
