// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dutydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAssignmentsForDuty = `-- name: CountAssignmentsForDuty :one
SELECT COUNT(*) FROM duty_assignments WHERE duty_id = $1 AND school_id = $2
`

type CountAssignmentsForDutyParams struct {
	DutyID   int64 `json:"duty_id"`
	SchoolID int64 `json:"school_id"`
}

// Dipakai DeleteDuty (409 bila SUDAH punya assignment di TA MANA PUN).
func (q *Queries) CountAssignmentsForDuty(ctx context.Context, arg CountAssignmentsForDutyParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssignmentsForDuty, arg.DutyID, arg.SchoolID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO duty_assignments (school_id, duty_id, user_id, academic_year_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateAssignmentParams struct {
	SchoolID       int64 `json:"school_id"`
	DutyID         int64 `json:"duty_id"`
	UserID         int64 `json:"user_id"`
	AcademicYearID int64 `json:"academic_year_id"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAssignment,
		arg.SchoolID,
		arg.DutyID,
		arg.UserID,
		arg.AcademicYearID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createDuty = `-- name: CreateDuty :one
INSERT INTO duties (school_id, name, for_role, flags, active)
VALUES ($1, $2, $3, $4, true)
RETURNING id, school_id, name, for_role, flags, active
`

type CreateDutyParams struct {
	SchoolID int64    `json:"school_id"`
	Name     string   `json:"name"`
	ForRole  string   `json:"for_role"`
	Flags    []string `json:"flags"`
}

func (q *Queries) CreateDuty(ctx context.Context, arg CreateDutyParams) (Duty, error) {
	row := q.db.QueryRow(ctx, createDuty,
		arg.SchoolID,
		arg.Name,
		arg.ForRole,
		arg.Flags,
	)
	var i Duty
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.ForRole,
		&i.Flags,
		&i.Active,
	)
	return i, err
}

const deleteAssignmentsForDutyYear = `-- name: DeleteAssignmentsForDutyYear :exec
DELETE FROM duty_assignments WHERE duty_id = $1 AND school_id = $2 AND academic_year_id = $3
`

type DeleteAssignmentsForDutyYearParams struct {
	DutyID         int64 `json:"duty_id"`
	SchoolID       int64 `json:"school_id"`
	AcademicYearID int64 `json:"academic_year_id"`
}

func (q *Queries) DeleteAssignmentsForDutyYear(ctx context.Context, arg DeleteAssignmentsForDutyYearParams) error {
	_, err := q.db.Exec(ctx, deleteAssignmentsForDutyYear, arg.DutyID, arg.SchoolID, arg.AcademicYearID)
	return err
}

const deleteDuty = `-- name: DeleteDuty :execrows
DELETE FROM duties WHERE id = $1 AND school_id = $2
`

type DeleteDutyParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) DeleteDuty(ctx context.Context, arg DeleteDutyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDuty, arg.ID, arg.SchoolID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDutyByID = `-- name: GetDutyByID :one
SELECT id, school_id, name, for_role, flags, active FROM duties WHERE id = $1 AND school_id = $2
`

type GetDutyByIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) GetDutyByID(ctx context.Context, arg GetDutyByIDParams) (Duty, error) {
	row := q.db.QueryRow(ctx, getDutyByID, arg.ID, arg.SchoolID)
	var i Duty
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.ForRole,
		&i.Flags,
		&i.Active,
	)
	return i, err
}

const listAssignmentsForDutyYear = `-- name: ListAssignmentsForDutyYear :many
SELECT u.id AS user_id, u.name
FROM duty_assignments a
JOIN users u ON u.id = a.user_id
WHERE a.duty_id = $1 AND a.school_id = $2 AND a.academic_year_id = $3
ORDER BY u.name
`

type ListAssignmentsForDutyYearParams struct {
	DutyID         int64 `json:"duty_id"`
	SchoolID       int64 `json:"school_id"`
	AcademicYearID int64 `json:"academic_year_id"`
}

type ListAssignmentsForDutyYearRow struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) ListAssignmentsForDutyYear(ctx context.Context, arg ListAssignmentsForDutyYearParams) ([]ListAssignmentsForDutyYearRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentsForDutyYear, arg.DutyID, arg.SchoolID, arg.AcademicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignmentsForDutyYearRow
	for rows.Next() {
		var i ListAssignmentsForDutyYearRow
		if err := rows.Scan(&i.UserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDutiesWithAssigneeCount = `-- name: ListDutiesWithAssigneeCount :many
SELECT d.id, d.school_id, d.name, d.for_role, d.flags, d.active,
       COUNT(a.id) AS assignee_count
FROM duties d
LEFT JOIN duty_assignments a ON a.duty_id = d.id AND a.academic_year_id = $2
WHERE d.school_id = $1
GROUP BY d.id
ORDER BY d.name
`

type ListDutiesWithAssigneeCountParams struct {
	SchoolID       int64 `json:"school_id"`
	AcademicYearID int64 `json:"academic_year_id"`
}

type ListDutiesWithAssigneeCountRow struct {
	ID            int64    `json:"id"`
	SchoolID      int64    `json:"school_id"`
	Name          string   `json:"name"`
	ForRole       string   `json:"for_role"`
	Flags         []string `json:"flags"`
	Active        bool     `json:"active"`
	AssigneeCount int64    `json:"assignee_count"`
}

// assignee_count = jumlah pemegang tugas pada TA AKTIF (academic_year_id
// parameter, 0 bila sekolah belum punya TA aktif -> tidak match apa pun).
func (q *Queries) ListDutiesWithAssigneeCount(ctx context.Context, arg ListDutiesWithAssigneeCountParams) ([]ListDutiesWithAssigneeCountRow, error) {
	rows, err := q.db.Query(ctx, listDutiesWithAssigneeCount, arg.SchoolID, arg.AcademicYearID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDutiesWithAssigneeCountRow
	for rows.Next() {
		var i ListDutiesWithAssigneeCountRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Name,
			&i.ForRole,
			&i.Flags,
			&i.Active,
			&i.AssigneeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIDsWithFlag = `-- name: ListUserIDsWithFlag :many
SELECT DISTINCT a.user_id
FROM duty_assignments a
JOIN duties d ON d.id = a.duty_id
WHERE a.school_id = $1 AND a.academic_year_id = $2
  AND d.active AND $3::text = ANY (d.flags)
`

type ListUserIDsWithFlagParams struct {
	SchoolID       int64  `json:"school_id"`
	AcademicYearID int64  `json:"academic_year_id"`
	Column3        string `json:"column_3"`
}

// Dipakai Service.UserIDsWithFlag (interface publik, mis. resolusi target
// notifikasi/antrian): distinct user_id pemegang tugas AKTIF pada TA yang
// diberikan yang membawa flag tsb.
func (q *Queries) ListUserIDsWithFlag(ctx context.Context, arg ListUserIDsWithFlagParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUserIDsWithFlag, arg.SchoolID, arg.AcademicYearID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDuty = `-- name: UpdateDuty :one
UPDATE duties SET
    name     = COALESCE($3, name),
    for_role = COALESCE($4, for_role),
    flags    = COALESCE($5, flags),
    active   = COALESCE($6, active)
WHERE id = $1 AND school_id = $2
RETURNING id, school_id, name, for_role, flags, active
`

type UpdateDutyParams struct {
	ID       int64       `json:"id"`
	SchoolID int64       `json:"school_id"`
	Name     pgtype.Text `json:"name"`
	ForRole  pgtype.Text `json:"for_role"`
	Flags    []string    `json:"flags"`
	Active   pgtype.Bool `json:"active"`
}

// PATCH semantics: sqlc.narg NULL berarti field tidak diubah (pola sama
// internal/discipline UpdateViolationType).
func (q *Queries) UpdateDuty(ctx context.Context, arg UpdateDutyParams) (Duty, error) {
	row := q.db.QueryRow(ctx, updateDuty,
		arg.ID,
		arg.SchoolID,
		arg.Name,
		arg.ForRole,
		arg.Flags,
		arg.Active,
	)
	var i Duty
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.ForRole,
		&i.Flags,
		&i.Active,
	)
	return i, err
}

const userHasFlag = `-- name: UserHasFlag :one
SELECT EXISTS (
    SELECT 1 FROM duty_assignments a
    JOIN duties d ON d.id = a.duty_id
    WHERE a.school_id = $1 AND a.user_id = $2 AND a.academic_year_id = $3
      AND d.active AND $4::text = ANY (d.flags)
) AS has_flag
`

type UserHasFlagParams struct {
	SchoolID       int64  `json:"school_id"`
	UserID         int64  `json:"user_id"`
	AcademicYearID int64  `json:"academic_year_id"`
	Column4        string `json:"column_4"`
}

// Dipakai Service.UserHasFlag (interface publik konsumsi modul lain, mis.
// studentleave): true bila user memegang SETIDAKNYA SATU tugas AKTIF pada TA
// yang diberikan yang membawa flag tsb.
func (q *Queries) UserHasFlag(ctx context.Context, arg UserHasFlagParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasFlag,
		arg.SchoolID,
		arg.UserID,
		arg.AcademicYearID,
		arg.Column4,
	)
	var has_flag bool
	err := row.Scan(&has_flag)
	return has_flag, err
}
