// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package disciplinedb

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AcademicYear struct {
	ID       int64       `json:"id"`
	SchoolID int64       `json:"school_id"`
	Name     string      `json:"name"`
	StartsOn pgtype.Date `json:"starts_on"`
	EndsOn   pgtype.Date `json:"ends_on"`
	IsActive bool        `json:"is_active"`
}

type Announcement struct {
	ID        int64              `json:"id"`
	SchoolID  int64              `json:"school_id"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	StartsAt  pgtype.Date        `json:"starts_at"`
	EndsAt    pgtype.Date        `json:"ends_at"`
	CreatedBy int64              `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AssessmentComponent struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	AcademicYearID int64              `json:"academic_year_id"`
	ClassID        int64              `json:"class_id"`
	SubjectID      int64              `json:"subject_id"`
	Name           string             `json:"name"`
	Type           string             `json:"type"`
	Weight         int32              `json:"weight"`
	Kktp           int32              `json:"kktp"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AttendanceRecord struct {
	ID        int64              `json:"id"`
	SchoolID  int64              `json:"school_id"`
	SessionID int64              `json:"session_id"`
	StudentID int64              `json:"student_id"`
	Status    string             `json:"status"`
	Method    string             `json:"method"`
	MarkedBy  int64              `json:"marked_by"`
	MarkedAt  pgtype.Timestamptz `json:"marked_at"`
	Meta      []byte             `json:"meta"`
	Note      pgtype.Text        `json:"note"`
}

type AttendanceSession struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	AcademicYearID int64              `json:"academic_year_id"`
	ClassID        int64              `json:"class_id"`
	Date           pgtype.Date        `json:"date"`
	Type           string             `json:"type"`
	ScheduleSlotID pgtype.Int8        `json:"schedule_slot_id"`
	OpenedBy       int64              `json:"opened_by"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID       int64              `json:"id"`
	SchoolID pgtype.Int8        `json:"school_id"`
	UserID   pgtype.Int8        `json:"user_id"`
	Action   string             `json:"action"`
	Entity   string             `json:"entity"`
	EntityID pgtype.Int8        `json:"entity_id"`
	OldValue []byte             `json:"old_value"`
	NewValue []byte             `json:"new_value"`
	At       pgtype.Timestamptz `json:"at"`
}

type Class struct {
	ID                int64       `json:"id"`
	SchoolID          int64       `json:"school_id"`
	AcademicYearID    int64       `json:"academic_year_id"`
	Name              string      `json:"name"`
	Grade             string      `json:"grade"`
	Major             pgtype.Text `json:"major"`
	HomeroomTeacherID pgtype.Int8 `json:"homeroom_teacher_id"`
}

type ClassroomStarEvent struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	AcademicYearID int64              `json:"academic_year_id"`
	StudentID      int64              `json:"student_id"`
	GivenBy        int64              `json:"given_by"`
	Delta          int32              `json:"delta"`
	Note           string             `json:"note"`
	Visibility     string             `json:"visibility"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Counseling struct {
	ID                 int64              `json:"id"`
	SchoolID           int64              `json:"school_id"`
	AcademicYearID     int64              `json:"academic_year_id"`
	StudentID          int64              `json:"student_id"`
	CounselorID        int64              `json:"counselor_id"`
	CareerGoals        string             `json:"career_goals"`
	ProblemDescription string             `json:"problem_description"`
	FollowUpPlan       string             `json:"follow_up_plan"`
	Evidence           pgtype.Text        `json:"evidence"`
	EvidenceName       pgtype.Text        `json:"evidence_name"`
	EvidenceMime       pgtype.Text        `json:"evidence_mime"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type DisciplineLetterNumberCounter struct {
	SchoolID int64  `json:"school_id"`
	Year     string `json:"year"`
	Seq      int32  `json:"seq"`
}

type DisciplineSpSetting struct {
	SchoolID       int64 `json:"school_id"`
	AcademicYearID int64 `json:"academic_year_id"`
	Sp1            int32 `json:"sp1"`
	Sp2            int32 `json:"sp2"`
	Sp3            int32 `json:"sp3"`
}

type DisciplineWarningLetter struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	AcademicYearID int64              `json:"academic_year_id"`
	StudentID      int64              `json:"student_id"`
	Level          int32              `json:"level"`
	Number         string             `json:"number"`
	PointsSnapshot int32              `json:"points_snapshot"`
	Snapshot       []byte             `json:"snapshot"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Duty struct {
	ID       int64    `json:"id"`
	SchoolID int64    `json:"school_id"`
	Name     string   `json:"name"`
	ForRole  string   `json:"for_role"`
	Flags    []string `json:"flags"`
	Active   bool     `json:"active"`
}

type DutyAssignment struct {
	ID             int64 `json:"id"`
	SchoolID       int64 `json:"school_id"`
	DutyID         int64 `json:"duty_id"`
	UserID         int64 `json:"user_id"`
	AcademicYearID int64 `json:"academic_year_id"`
}

type Employee struct {
	ID       int64  `json:"id"`
	SchoolID int64  `json:"school_id"`
	UserID   int64  `json:"user_id"`
	Nip      string `json:"nip"`
}

type Enrollment struct {
	ID        int64              `json:"id"`
	SchoolID  int64              `json:"school_id"`
	StudentID int64              `json:"student_id"`
	ClassID   int64              `json:"class_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GradePublication struct {
	SchoolID       int64              `json:"school_id"`
	AcademicYearID int64              `json:"academic_year_id"`
	ClassID        int64              `json:"class_id"`
	SubjectID      int64              `json:"subject_id"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	PublishedBy    pgtype.Int8        `json:"published_by"`
}

type Guardian struct {
	ID        int64  `json:"id"`
	SchoolID  int64  `json:"school_id"`
	UserID    int64  `json:"user_id"`
	StudentID int64  `json:"student_id"`
	Relation  string `json:"relation"`
}

type InterestLead struct {
	ID          int64              `json:"id"`
	SchoolName  string             `json:"school_name"`
	ContactName string             `json:"contact_name"`
	Phone       string             `json:"phone"`
	Email       pgtype.Text        `json:"email"`
	Note        pgtype.Text        `json:"note"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Invitation struct {
	ID        int64              `json:"id"`
	SchoolID  int64              `json:"school_id"`
	Code      string             `json:"code"`
	Role      string             `json:"role"`
	TargetID  pgtype.Int8        `json:"target_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

type Invoice struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	Number         string             `json:"number"`
	SubscriptionID pgtype.Int8        `json:"subscription_id"`
	Amount         int64              `json:"amount"`
	Status         string             `json:"status"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	PlanCode       string             `json:"plan_code"`
	MaxStudents    int32              `json:"max_students"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type InvoiceNumberCounter struct {
	Year string `json:"year"`
	Seq  int32  `json:"seq"`
}

type LeaveApprovalStep struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	LeaveRequestID int64              `json:"leave_request_id"`
	StepOrder      int32              `json:"step_order"`
	ApproverRole   string             `json:"approver_role"`
	ApproverUserID pgtype.Int8        `json:"approver_user_id"`
	DecidedBy      pgtype.Int8        `json:"decided_by"`
	Decision       pgtype.Text        `json:"decision"`
	DecidedAt      pgtype.Timestamptz `json:"decided_at"`
	Comment        pgtype.Text        `json:"comment"`
}

type LeaveRequest struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	TeacherID      int64              `json:"teacher_id"`
	Type           string             `json:"type"`
	DateStart      pgtype.Date        `json:"date_start"`
	DateEnd        pgtype.Date        `json:"date_end"`
	Reason         string             `json:"reason"`
	Attachment     pgtype.Text        `json:"attachment"`
	AttachmentName pgtype.Text        `json:"attachment_name"`
	AttachmentMime pgtype.Text        `json:"attachment_mime"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Membership struct {
	ID       int64  `json:"id"`
	UserID   int64  `json:"user_id"`
	SchoolID int64  `json:"school_id"`
	Role     string `json:"role"`
	Status   string `json:"status"`
}

type Notification struct {
	ID        int64              `json:"id"`
	SchoolID  int64              `json:"school_id"`
	UserID    int64              `json:"user_id"`
	Event     string             `json:"event"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Link      pgtype.Text        `json:"link"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type NotificationOutbox struct {
	ID          int64              `json:"id"`
	SchoolID    int64              `json:"school_id"`
	Event       string             `json:"event"`
	UserID      int64              `json:"user_id"`
	Channel     string             `json:"channel"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	Attempts    int32              `json:"attempts"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	SentAt      pgtype.Timestamptz `json:"sent_at"`
}

type Payment struct {
	ID          int64              `json:"id"`
	InvoiceID   int64              `json:"invoice_id"`
	Method      string             `json:"method"`
	Amount      int64              `json:"amount"`
	ProofUrl    pgtype.Text        `json:"proof_url"`
	VerifiedBy  pgtype.Int8        `json:"verified_by"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
	Provider    pgtype.Text        `json:"provider"`
	ProviderRef pgtype.Text        `json:"provider_ref"`
	RawWebhook  []byte             `json:"raw_webhook"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Period struct {
	ID       int64       `json:"id"`
	SchoolID int64       `json:"school_id"`
	Number   int32       `json:"number"`
	StartsAt pgtype.Time `json:"starts_at"`
	EndsAt   pgtype.Time `json:"ends_at"`
	Label    pgtype.Text `json:"label"`
}

type PeriodDayOverride struct {
	ID        int64       `json:"id"`
	SchoolID  int64       `json:"school_id"`
	DayOfWeek int32       `json:"day_of_week"`
	Number    int32       `json:"number"`
	StartsAt  pgtype.Time `json:"starts_at"`
	EndsAt    pgtype.Time `json:"ends_at"`
	Label     string      `json:"label"`
}

type Plan struct {
	ID       int64  `json:"id"`
	Code     string `json:"code"`
	Name     string `json:"name"`
	Features []byte `json:"features"`
	Active   bool   `json:"active"`
}

type PlanPrice struct {
	ID          int64 `json:"id"`
	PlanID      int64 `json:"plan_id"`
	MaxStudents int32 `json:"max_students"`
	PriceYearly int64 `json:"price_yearly"`
}

type PlatformAnnouncement struct {
	ID        int64              `json:"id"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	StartsAt  pgtype.Date        `json:"starts_at"`
	EndsAt    pgtype.Date        `json:"ends_at"`
	CreatedBy pgtype.Int8        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PlatformConfig struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type PushSubscription struct {
	ID        int64              `json:"id"`
	SchoolID  int64              `json:"school_id"`
	UserID    int64              `json:"user_id"`
	Endpoint  string             `json:"endpoint"`
	P256dh    string             `json:"p256dh"`
	Auth      string             `json:"auth"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ReportManualScore struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	AcademicYearID int64              `json:"academic_year_id"`
	ClassID        int64              `json:"class_id"`
	SubjectID      int64              `json:"subject_id"`
	StudentID      int64              `json:"student_id"`
	Kind           string             `json:"kind"`
	Score          pgtype.Numeric     `json:"score"`
	Note           string             `json:"note"`
	SetBy          pgtype.Int8        `json:"set_by"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ReportTpMapping struct {
	ID             int64  `json:"id"`
	SchoolID       int64  `json:"school_id"`
	AcademicYearID int64  `json:"academic_year_id"`
	ClassID        int64  `json:"class_id"`
	SubjectID      int64  `json:"subject_id"`
	ComponentID    int64  `json:"component_id"`
	TpCode         string `json:"tp_code"`
	Description    string `json:"description"`
}

type Room struct {
	ID       int64  `json:"id"`
	SchoolID int64  `json:"school_id"`
	Name     string `json:"name"`
	QrToken  string `json:"qr_token"`
}

type ScheduleSlot struct {
	ID             int64       `json:"id"`
	SchoolID       int64       `json:"school_id"`
	AcademicYearID int64       `json:"academic_year_id"`
	ClassID        int64       `json:"class_id"`
	SubjectID      int64       `json:"subject_id"`
	TeacherID      int64       `json:"teacher_id"`
	RoomID         pgtype.Int8 `json:"room_id"`
	DayOfWeek      int32       `json:"day_of_week"`
	PeriodStart    int32       `json:"period_start"`
	PeriodEnd      int32       `json:"period_end"`
}

type School struct {
	ID            int64              `json:"id"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	CustomDomain  pgtype.Text        `json:"custom_domain"`
	Timezone      string             `json:"timezone"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PendingDomain pgtype.Text        `json:"pending_domain"`
}

type SchoolRolePermission struct {
	SchoolID   int64  `json:"school_id"`
	Role       string `json:"role"`
	Permission string `json:"permission"`
	Allowed    bool   `json:"allowed"`
}

type SchoolSetting struct {
	SchoolID  int64              `json:"school_id"`
	Module    string             `json:"module"`
	Settings  []byte             `json:"settings"`
	UpdatedBy pgtype.Int8        `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID                 int64              `json:"id"`
	UserID             int64              `json:"user_id"`
	SchoolID           pgtype.Int8        `json:"school_id"`
	TokenHash          []byte             `json:"token_hash"`
	Role               string             `json:"role"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	Ip                 *netip.Addr        `json:"ip"`
	UserAgent          pgtype.Text        `json:"user_agent"`
	ImpersonatorUserID pgtype.Int8        `json:"impersonator_user_id"`
}

type Student struct {
	ID        int64              `json:"id"`
	SchoolID  int64              `json:"school_id"`
	Nis       string             `json:"nis"`
	Nisn      pgtype.Text        `json:"nisn"`
	Name      string             `json:"name"`
	Gender    pgtype.Text        `json:"gender"`
	BirthDate pgtype.Date        `json:"birth_date"`
	UserID    pgtype.Int8        `json:"user_id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type StudentExitPermit struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	AcademicYearID int64              `json:"academic_year_id"`
	StudentID      int64              `json:"student_id"`
	Reason         string             `json:"reason"`
	Status         string             `json:"status"`
	DutyBy         pgtype.Int8        `json:"duty_by"`
	DutyAt         pgtype.Timestamptz `json:"duty_at"`
	ClassBy        pgtype.Int8        `json:"class_by"`
	ClassAt        pgtype.Timestamptz `json:"class_at"`
	BkBy           pgtype.Int8        `json:"bk_by"`
	BkAt           pgtype.Timestamptz `json:"bk_at"`
	LeadershipBy   pgtype.Int8        `json:"leadership_by"`
	LeadershipAt   pgtype.Timestamptz `json:"leadership_at"`
	RejectedBy     pgtype.Int8        `json:"rejected_by"`
	RejectedAt     pgtype.Timestamptz `json:"rejected_at"`
	RejectComment  string             `json:"reject_comment"`
	GateToken      pgtype.Text        `json:"gate_token"`
	GateExpiresAt  pgtype.Timestamptz `json:"gate_expires_at"`
	ExitedBy       pgtype.Int8        `json:"exited_by"`
	ExitedAt       pgtype.Timestamptz `json:"exited_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type StudentGrade struct {
	ID          int64              `json:"id"`
	SchoolID    int64              `json:"school_id"`
	ComponentID int64              `json:"component_id"`
	StudentID   int64              `json:"student_id"`
	Score       pgtype.Numeric     `json:"score"`
	GradedBy    pgtype.Int8        `json:"graded_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type StudentLateArrival struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	AcademicYearID int64              `json:"academic_year_id"`
	StudentID      int64              `json:"student_id"`
	ArrivedAt      pgtype.Timestamptz `json:"arrived_at"`
	LateCount      int32              `json:"late_count"`
	Action         string             `json:"action"`
	Status         string             `json:"status"`
	DutyBy         pgtype.Int8        `json:"duty_by"`
	DutyAt         pgtype.Timestamptz `json:"duty_at"`
	LeadershipBy   pgtype.Int8        `json:"leadership_by"`
	LeadershipAt   pgtype.Timestamptz `json:"leadership_at"`
	ClassBy        pgtype.Int8        `json:"class_by"`
	ClassAt        pgtype.Timestamptz `json:"class_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type StudentLeaveNumberCounter struct {
	SchoolID int64  `json:"school_id"`
	Year     string `json:"year"`
	Seq      int32  `json:"seq"`
}

type StudentLeaveRequest struct {
	ID                int64              `json:"id"`
	SchoolID          int64              `json:"school_id"`
	AcademicYearID    int64              `json:"academic_year_id"`
	StudentID         int64              `json:"student_id"`
	SubmittedBy       int64              `json:"submitted_by"`
	Type              string             `json:"type"`
	DateStart         pgtype.Date        `json:"date_start"`
	DateEnd           pgtype.Date        `json:"date_end"`
	Reason            string             `json:"reason"`
	Attachment        string             `json:"attachment"`
	AttachmentName    string             `json:"attachment_name"`
	AttachmentMime    string             `json:"attachment_mime"`
	Status            string             `json:"status"`
	LetterNumber      pgtype.Text        `json:"letter_number"`
	VerifyToken       pgtype.Text        `json:"verify_token"`
	HomeroomDecidedBy pgtype.Int8        `json:"homeroom_decided_by"`
	HomeroomDecidedAt pgtype.Timestamptz `json:"homeroom_decided_at"`
	HomeroomComment   string             `json:"homeroom_comment"`
	BkDecidedBy       pgtype.Int8        `json:"bk_decided_by"`
	BkDecidedAt       pgtype.Timestamptz `json:"bk_decided_at"`
	BkComment         string             `json:"bk_comment"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type StudentQrToken struct {
	ID        int64              `json:"id"`
	SchoolID  int64              `json:"school_id"`
	StudentID int64              `json:"student_id"`
	Token     string             `json:"token"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type StudentViolation struct {
	ID                  int64              `json:"id"`
	SchoolID            int64              `json:"school_id"`
	AcademicYearID      int64              `json:"academic_year_id"`
	StudentID           int64              `json:"student_id"`
	ViolationTypeID     int64              `json:"violation_type_id"`
	AttendanceSessionID pgtype.Int8        `json:"attendance_session_id"`
	NotedBy             int64              `json:"noted_by"`
	Note                string             `json:"note"`
	OccurredOn          pgtype.Date        `json:"occurred_on"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type Subject struct {
	ID       int64  `json:"id"`
	SchoolID int64  `json:"school_id"`
	Code     string `json:"code"`
	Name     string `json:"name"`
}

type Subscription struct {
	ID               int64       `json:"id"`
	SchoolID         int64       `json:"school_id"`
	PlanCode         string      `json:"plan_code"`
	Features         []byte      `json:"features"`
	MaxStudents      int32       `json:"max_students"`
	Price            int64       `json:"price"`
	StartsOn         pgtype.Date `json:"starts_on"`
	EndsOn           pgtype.Date `json:"ends_on"`
	Status           string      `json:"status"`
	FeatureOverrides []byte      `json:"feature_overrides"`
}

type Teacher struct {
	ID       int64       `json:"id"`
	SchoolID int64       `json:"school_id"`
	UserID   int64       `json:"user_id"`
	Nip      pgtype.Text `json:"nip"`
}

type TeacherQrToken struct {
	ID         int64              `json:"id"`
	SchoolID   int64              `json:"school_id"`
	UserID     int64              `json:"user_id"`
	Token      string             `json:"token"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type TeacherSubstitutionRequest struct {
	ID               int64              `json:"id"`
	SchoolID         int64              `json:"school_id"`
	ScheduleSlotID   int64              `json:"schedule_slot_id"`
	Date             pgtype.Date        `json:"date"`
	RequestedBy      int64              `json:"requested_by"`
	SubstituteUserID int64              `json:"substitute_user_id"`
	Reason           string             `json:"reason"`
	Status           string             `json:"status"`
	DecidedAt        pgtype.Timestamptz `json:"decided_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type TeachingJournal struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	TeacherID      int64              `json:"teacher_id"`
	ScheduleSlotID pgtype.Int8        `json:"schedule_slot_id"`
	ClassID        int64              `json:"class_id"`
	SubjectID      pgtype.Int8        `json:"subject_id"`
	RoomID         pgtype.Int8        `json:"room_id"`
	Date           pgtype.Date        `json:"date"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	EndedAt        pgtype.Timestamptz `json:"ended_at"`
	Material       pgtype.Text        `json:"material"`
	Note           pgtype.Text        `json:"note"`
	Flags          []string           `json:"flags"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        pgtype.Text        `json:"email"`
	Username     pgtype.Text        `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Phone        pgtype.Text        `json:"phone"`
	IsSuperAdmin bool               `json:"is_super_admin"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ViolationType struct {
	ID       int64  `json:"id"`
	SchoolID int64  `json:"school_id"`
	Name     string `json:"name"`
	Points   int32  `json:"points"`
	Category string `json:"category"`
	Active   bool   `json:"active"`
}
