// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package disciplinedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attendanceSessionExists = `-- name: AttendanceSessionExists :one
SELECT id FROM attendance_sessions WHERE id = $1 AND school_id = $2
`

type AttendanceSessionExistsParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) AttendanceSessionExists(ctx context.Context, arg AttendanceSessionExistsParams) (int64, error) {
	row := q.db.QueryRow(ctx, attendanceSessionExists, arg.ID, arg.SchoolID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const countStudentViolations = `-- name: CountStudentViolations :one
SELECT COUNT(*) FROM student_violations sv
LEFT JOIN enrollments e ON e.student_id = sv.student_id
LEFT JOIN classes c ON c.id = e.class_id AND c.academic_year_id = $1::bigint
WHERE sv.school_id = $2::bigint
  AND ($3::bigint IS NULL OR sv.student_id = $3::bigint)
  AND ($4::bigint IS NULL OR c.id = $4::bigint)
  AND ($5::date IS NULL OR sv.occurred_on >= $5::date)
  AND ($6::date IS NULL OR sv.occurred_on <= $6::date)
`

type CountStudentViolationsParams struct {
	AcademicYearID int64       `json:"academic_year_id"`
	SchoolID       int64       `json:"school_id"`
	StudentID      pgtype.Int8 `json:"student_id"`
	ClassID        pgtype.Int8 `json:"class_id"`
	FromDate       pgtype.Date `json:"from_date"`
	ToDate         pgtype.Date `json:"to_date"`
}

func (q *Queries) CountStudentViolations(ctx context.Context, arg CountStudentViolationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentViolations,
		arg.AcademicYearID,
		arg.SchoolID,
		arg.StudentID,
		arg.ClassID,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countViolationsByType = `-- name: CountViolationsByType :one
SELECT COUNT(*) FROM student_violations WHERE school_id = $1 AND violation_type_id = $2
`

type CountViolationsByTypeParams struct {
	SchoolID        int64 `json:"school_id"`
	ViolationTypeID int64 `json:"violation_type_id"`
}

// Dipakai guard DELETE /api/discipline/types/{id} (409 bila sudah dipakai
// record — sarankan nonaktifkan active=false, bukan hapus).
func (q *Queries) CountViolationsByType(ctx context.Context, arg CountViolationsByTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countViolationsByType, arg.SchoolID, arg.ViolationTypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWarningLetters = `-- name: CountWarningLetters :one
SELECT COUNT(*) FROM discipline_warning_letters
WHERE school_id = $1::bigint
  AND ($2::int IS NULL OR level = $2::int)
`

type CountWarningLettersParams struct {
	SchoolID int64       `json:"school_id"`
	Level    pgtype.Int4 `json:"level"`
}

func (q *Queries) CountWarningLetters(ctx context.Context, arg CountWarningLettersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWarningLetters, arg.SchoolID, arg.Level)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStudentViolation = `-- name: CreateStudentViolation :one

INSERT INTO student_violations (school_id, academic_year_id, student_id, violation_type_id, attendance_session_id, noted_by, note, occurred_on)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, school_id, academic_year_id, student_id, violation_type_id, attendance_session_id, noted_by, note, occurred_on, created_at
`

type CreateStudentViolationParams struct {
	SchoolID            int64       `json:"school_id"`
	AcademicYearID      int64       `json:"academic_year_id"`
	StudentID           int64       `json:"student_id"`
	ViolationTypeID     int64       `json:"violation_type_id"`
	AttendanceSessionID pgtype.Int8 `json:"attendance_session_id"`
	NotedBy             int64       `json:"noted_by"`
	Note                string      `json:"note"`
	OccurredOn          pgtype.Date `json:"occurred_on"`
}

// -- student_violations --
func (q *Queries) CreateStudentViolation(ctx context.Context, arg CreateStudentViolationParams) (StudentViolation, error) {
	row := q.db.QueryRow(ctx, createStudentViolation,
		arg.SchoolID,
		arg.AcademicYearID,
		arg.StudentID,
		arg.ViolationTypeID,
		arg.AttendanceSessionID,
		arg.NotedBy,
		arg.Note,
		arg.OccurredOn,
	)
	var i StudentViolation
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.StudentID,
		&i.ViolationTypeID,
		&i.AttendanceSessionID,
		&i.NotedBy,
		&i.Note,
		&i.OccurredOn,
		&i.CreatedAt,
	)
	return i, err
}

const createViolationType = `-- name: CreateViolationType :one


INSERT INTO violation_types (school_id, name, points, category, active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, school_id, name, points, category, active
`

type CreateViolationTypeParams struct {
	SchoolID int64  `json:"school_id"`
	Name     string `json:"name"`
	Points   int32  `json:"points"`
	Category string `json:"category"`
	Active   bool   `json:"active"`
}

// Query modul discipline (sqlc). Semua query tenant-scoped WAJIB filter
// school_id. Join read-only ke students/classes/enrollments/violation_types/
// users (dimiliki modul lain) dipakai untuk menampilkan nama tanpa N+1 call
// lintas modul — pola yang sama dengan internal/leave/queries.sql (join ke
// users) & internal/attendance/queries.sql (join ke classes/students).
//
// Catatan lingkungan (lihat internal/discipline/disciplinedb/*.go): sqlc CLI
// TIDAK tersedia di lingkungan build/dev/container ini (dikonfirmasi ulang
// sesi ini, sama seperti dicatat Fase 12/13) — file *.sql.go di
// internal/discipline/disciplinedb/ ditulis TANGAN mengikuti idiom PERSIS
// sqlc v1.31.1 (lihat internal/leave/leavedb, internal/billing/billingdb
// sebagai acuan), BUKAN hasil generate otomatis. sqlc.yaml tetap didaftarkan
// supaya `make sqlc` regenerate identik begitu sqlc CLI tersedia.
// -- violation_types --
func (q *Queries) CreateViolationType(ctx context.Context, arg CreateViolationTypeParams) (ViolationType, error) {
	row := q.db.QueryRow(ctx, createViolationType,
		arg.SchoolID,
		arg.Name,
		arg.Points,
		arg.Category,
		arg.Active,
	)
	var i ViolationType
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.Points,
		&i.Category,
		&i.Active,
	)
	return i, err
}

const createWarningLetter = `-- name: CreateWarningLetter :one

INSERT INTO discipline_warning_letters (school_id, academic_year_id, student_id, level, number, points_snapshot, snapshot, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, school_id, academic_year_id, student_id, level, number, points_snapshot, snapshot, created_by, created_at
`

type CreateWarningLetterParams struct {
	SchoolID       int64       `json:"school_id"`
	AcademicYearID int64       `json:"academic_year_id"`
	StudentID      int64       `json:"student_id"`
	Level          int32       `json:"level"`
	Number         string      `json:"number"`
	PointsSnapshot int32       `json:"points_snapshot"`
	Snapshot       []byte      `json:"snapshot"`
	CreatedBy      pgtype.Int8 `json:"created_by"`
}

// -- discipline_warning_letters --
func (q *Queries) CreateWarningLetter(ctx context.Context, arg CreateWarningLetterParams) (DisciplineWarningLetter, error) {
	row := q.db.QueryRow(ctx, createWarningLetter,
		arg.SchoolID,
		arg.AcademicYearID,
		arg.StudentID,
		arg.Level,
		arg.Number,
		arg.PointsSnapshot,
		arg.Snapshot,
		arg.CreatedBy,
	)
	var i DisciplineWarningLetter
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.StudentID,
		&i.Level,
		&i.Number,
		&i.PointsSnapshot,
		&i.Snapshot,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStudentViolation = `-- name: DeleteStudentViolation :execrows
DELETE FROM student_violations WHERE id = $1 AND school_id = $2
`

type DeleteStudentViolationParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

// Menghapus CATATAN saja — surat yang sudah terbit TIDAK disentuh (snapshot
// immutable, lihat discipline_warning_letters).
func (q *Queries) DeleteStudentViolation(ctx context.Context, arg DeleteStudentViolationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStudentViolation, arg.ID, arg.SchoolID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteViolationType = `-- name: DeleteViolationType :execrows
DELETE FROM violation_types WHERE id = $1 AND school_id = $2
`

type DeleteViolationTypeParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) DeleteViolationType(ctx context.Context, arg DeleteViolationTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteViolationType, arg.ID, arg.SchoolID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disciplineSummary = `-- name: DisciplineSummary :many

SELECT s.id AS student_id, s.name AS student_name, s.nis AS student_nis,
       COALESCE(c.name, '') AS class_name,
       COALESCE(SUM(vt.points), 0)::bigint AS total_points,
       COUNT(sv.id) AS record_count,
       MAX(sv.occurred_on) AS last_at
FROM student_violations sv
JOIN students s ON s.id = sv.student_id
JOIN violation_types vt ON vt.id = sv.violation_type_id
LEFT JOIN enrollments e ON e.student_id = s.id
LEFT JOIN classes c ON c.id = e.class_id AND c.academic_year_id = $1::bigint
WHERE sv.school_id = $2::bigint
  AND ($3::bigint IS NULL OR c.id = $3::bigint)
  AND ($4::date IS NULL OR sv.occurred_on >= $4::date)
  AND ($5::date IS NULL OR sv.occurred_on <= $5::date)
GROUP BY s.id, s.name, s.nis, c.name
ORDER BY total_points DESC, s.name
`

type DisciplineSummaryParams struct {
	AcademicYearID int64       `json:"academic_year_id"`
	SchoolID       int64       `json:"school_id"`
	ClassID        pgtype.Int8 `json:"class_id"`
	FromDate       pgtype.Date `json:"from_date"`
	ToDate         pgtype.Date `json:"to_date"`
}

type DisciplineSummaryRow struct {
	StudentID   int64       `json:"student_id"`
	StudentName string      `json:"student_name"`
	StudentNis  string      `json:"student_nis"`
	ClassName   string      `json:"class_name"`
	TotalPoints int64       `json:"total_points"`
	RecordCount int64       `json:"record_count"`
	LastAt      interface{} `json:"last_at"`
}

// -- rekap --
// GET /api/discipline/summary?class_id=&from=&to= — kelas SELALU dari
// enrollment TA AKTIF (sama keputusan dgn ListStudentViolations).
func (q *Queries) DisciplineSummary(ctx context.Context, arg DisciplineSummaryParams) ([]DisciplineSummaryRow, error) {
	rows, err := q.db.Query(ctx, disciplineSummary,
		arg.AcademicYearID,
		arg.SchoolID,
		arg.ClassID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DisciplineSummaryRow
	for rows.Next() {
		var i DisciplineSummaryRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentName,
			&i.StudentNis,
			&i.ClassName,
			&i.TotalPoints,
			&i.RecordCount,
			&i.LastAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHomeroomTeacherUserID = `-- name: GetHomeroomTeacherUserID :one
SELECT t.user_id
FROM enrollments e
JOIN classes c ON c.id = e.class_id
JOIN teachers t ON t.id = c.homeroom_teacher_id
WHERE e.student_id = $1 AND c.school_id = $2 AND c.academic_year_id = $3
LIMIT 1
`

type GetHomeroomTeacherUserIDParams struct {
	StudentID      int64 `json:"student_id"`
	SchoolID       int64 `json:"school_id"`
	AcademicYearID int64 `json:"academic_year_id"`
}

// Dipakai notifikasi "discipline.sp_issued" ke wali kelas (docs tugas: "ke
// ortu + wali kelas"). Kelas diresolusi dari enrollment TAHUN AJARAN yang
// SAMA dengan surat diterbitkan. pgx.ErrNoRows (siswa tidak terdaftar di
// kelas manapun, atau kelasnya belum punya wali) ditangani Service sebagai
// "tidak ada wali kelas untuk dinotifikasi" — bukan error.
func (q *Queries) GetHomeroomTeacherUserID(ctx context.Context, arg GetHomeroomTeacherUserIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getHomeroomTeacherUserID, arg.StudentID, arg.SchoolID, arg.AcademicYearID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getSPSettings = `-- name: GetSPSettings :one

SELECT school_id, academic_year_id, sp1, sp2, sp3 FROM discipline_sp_settings WHERE school_id = $1 AND academic_year_id = $2
`

type GetSPSettingsParams struct {
	SchoolID       int64 `json:"school_id"`
	AcademicYearID int64 `json:"academic_year_id"`
}

// -- discipline_sp_settings --
func (q *Queries) GetSPSettings(ctx context.Context, arg GetSPSettingsParams) (DisciplineSpSetting, error) {
	row := q.db.QueryRow(ctx, getSPSettings, arg.SchoolID, arg.AcademicYearID)
	var i DisciplineSpSetting
	err := row.Scan(
		&i.SchoolID,
		&i.AcademicYearID,
		&i.Sp1,
		&i.Sp2,
		&i.Sp3,
	)
	return i, err
}

const getStudentBasic = `-- name: GetStudentBasic :one

SELECT id, name, nis FROM students WHERE id = $1 AND school_id = $2
`

type GetStudentBasicParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetStudentBasicRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Nis  string `json:"nis"`
}

// -- validasi lintas modul (join read-only ke tabel bersama, pola yang sama
// -- dengan internal/attendance/queries.sql "SELECT id, name, nis FROM students") --
func (q *Queries) GetStudentBasic(ctx context.Context, arg GetStudentBasicParams) (GetStudentBasicRow, error) {
	row := q.db.QueryRow(ctx, getStudentBasic, arg.ID, arg.SchoolID)
	var i GetStudentBasicRow
	err := row.Scan(&i.ID, &i.Name, &i.Nis)
	return i, err
}

const getStudentClassName = `-- name: GetStudentClassName :one
SELECT c.name FROM enrollments e JOIN classes c ON c.id = e.class_id
WHERE e.student_id = $1 AND c.school_id = $2 AND c.academic_year_id = $3
LIMIT 1
`

type GetStudentClassNameParams struct {
	StudentID      int64 `json:"student_id"`
	SchoolID       int64 `json:"school_id"`
	AcademicYearID int64 `json:"academic_year_id"`
}

// Dipakai GET /api/students/{id}/discipline (nama kelas siswa pada TA yang
// direquest, dipasangkan dgn ListViolationsForStudentYear yang TIDAK
// membawa info kelas).
func (q *Queries) GetStudentClassName(ctx context.Context, arg GetStudentClassNameParams) (string, error) {
	row := q.db.QueryRow(ctx, getStudentClassName, arg.StudentID, arg.SchoolID, arg.AcademicYearID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getStudentViolationByID = `-- name: GetStudentViolationByID :one
SELECT sv.id, sv.school_id, sv.academic_year_id, sv.student_id, sv.violation_type_id,
       sv.attendance_session_id, sv.noted_by, sv.note, sv.occurred_on, sv.created_at,
       s.name AS student_name, s.nis AS student_nis, COALESCE(c.name, '') AS class_name,
       vt.name AS violation_name, vt.points AS violation_points, u.name AS noted_by_name
FROM student_violations sv
JOIN students s ON s.id = sv.student_id
JOIN violation_types vt ON vt.id = sv.violation_type_id
JOIN users u ON u.id = sv.noted_by
LEFT JOIN enrollments e ON e.student_id = s.id
LEFT JOIN classes c ON c.id = e.class_id AND c.academic_year_id = sv.academic_year_id
WHERE sv.id = $1 AND sv.school_id = $2
`

type GetStudentViolationByIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetStudentViolationByIDRow struct {
	ID                  int64              `json:"id"`
	SchoolID            int64              `json:"school_id"`
	AcademicYearID      int64              `json:"academic_year_id"`
	StudentID           int64              `json:"student_id"`
	ViolationTypeID     int64              `json:"violation_type_id"`
	AttendanceSessionID pgtype.Int8        `json:"attendance_session_id"`
	NotedBy             int64              `json:"noted_by"`
	Note                string             `json:"note"`
	OccurredOn          pgtype.Date        `json:"occurred_on"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	StudentName         string             `json:"student_name"`
	StudentNis          string             `json:"student_nis"`
	ClassName           string             `json:"class_name"`
	ViolationName       string             `json:"violation_name"`
	ViolationPoints     int32              `json:"violation_points"`
	NotedByName         string             `json:"noted_by_name"`
}

// Dipakai (a) DELETE (audit old value) DAN (b) memuat ulang RecordView
// lengkap setelah CreateStudentViolation (pola yang sama dengan
// leave.buildRequestView: insert lalu reload SEKALI dengan join lengkap,
// bukan compose manual dari beberapa fetch terpisah). Kelas diresolusi dari
// enrollment PADA TAHUN AJARAN baris ini dibuat (sv.academic_year_id) —
// BEDA dari ListStudentViolations yang selalu memakai TA AKTIF sekarang.
func (q *Queries) GetStudentViolationByID(ctx context.Context, arg GetStudentViolationByIDParams) (GetStudentViolationByIDRow, error) {
	row := q.db.QueryRow(ctx, getStudentViolationByID, arg.ID, arg.SchoolID)
	var i GetStudentViolationByIDRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.StudentID,
		&i.ViolationTypeID,
		&i.AttendanceSessionID,
		&i.NotedBy,
		&i.Note,
		&i.OccurredOn,
		&i.CreatedAt,
		&i.StudentName,
		&i.StudentNis,
		&i.ClassName,
		&i.ViolationName,
		&i.ViolationPoints,
		&i.NotedByName,
	)
	return i, err
}

const getViolationTypeByID = `-- name: GetViolationTypeByID :one
SELECT id, school_id, name, points, category, active FROM violation_types WHERE id = $1 AND school_id = $2
`

type GetViolationTypeByIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) GetViolationTypeByID(ctx context.Context, arg GetViolationTypeByIDParams) (ViolationType, error) {
	row := q.db.QueryRow(ctx, getViolationTypeByID, arg.ID, arg.SchoolID)
	var i ViolationType
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.Points,
		&i.Category,
		&i.Active,
	)
	return i, err
}

const getWarningLetterByID = `-- name: GetWarningLetterByID :one
SELECT id, school_id, academic_year_id, student_id, level, number, points_snapshot, snapshot, created_by, created_at FROM discipline_warning_letters WHERE id = $1 AND school_id = $2
`

type GetWarningLetterByIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) GetWarningLetterByID(ctx context.Context, arg GetWarningLetterByIDParams) (DisciplineWarningLetter, error) {
	row := q.db.QueryRow(ctx, getWarningLetterByID, arg.ID, arg.SchoolID)
	var i DisciplineWarningLetter
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.StudentID,
		&i.Level,
		&i.Number,
		&i.PointsSnapshot,
		&i.Snapshot,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listStudentViolations = `-- name: ListStudentViolations :many
SELECT
    sv.id, sv.occurred_on, sv.note, sv.attendance_session_id, sv.created_at,
    s.id AS student_id, s.name AS student_name, s.nis AS student_nis,
    COALESCE(c.name, '') AS class_name,
    vt.id AS violation_type_id, vt.name AS violation_name, vt.points AS violation_points,
    sv.noted_by, u.name AS noted_by_name
FROM student_violations sv
JOIN students s ON s.id = sv.student_id
JOIN violation_types vt ON vt.id = sv.violation_type_id
JOIN users u ON u.id = sv.noted_by
LEFT JOIN enrollments e ON e.student_id = s.id
LEFT JOIN classes c ON c.id = e.class_id AND c.academic_year_id = $1::bigint
WHERE sv.school_id = $2::bigint
  AND ($3::bigint IS NULL OR sv.student_id = $3::bigint)
  AND ($4::bigint IS NULL OR c.id = $4::bigint)
  AND ($5::date IS NULL OR sv.occurred_on >= $5::date)
  AND ($6::date IS NULL OR sv.occurred_on <= $6::date)
ORDER BY sv.occurred_on DESC, sv.id DESC
LIMIT $8::int OFFSET $7::int
`

type ListStudentViolationsParams struct {
	AcademicYearID int64       `json:"academic_year_id"`
	SchoolID       int64       `json:"school_id"`
	StudentID      pgtype.Int8 `json:"student_id"`
	ClassID        pgtype.Int8 `json:"class_id"`
	FromDate       pgtype.Date `json:"from_date"`
	ToDate         pgtype.Date `json:"to_date"`
	OffsetRows     int32       `json:"offset_rows"`
	LimitRows      int32       `json:"limit_rows"`
}

type ListStudentViolationsRow struct {
	ID                  int64              `json:"id"`
	OccurredOn          pgtype.Date        `json:"occurred_on"`
	Note                string             `json:"note"`
	AttendanceSessionID pgtype.Int8        `json:"attendance_session_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	StudentID           int64              `json:"student_id"`
	StudentName         string             `json:"student_name"`
	StudentNis          string             `json:"student_nis"`
	ClassName           string             `json:"class_name"`
	ViolationTypeID     int64              `json:"violation_type_id"`
	ViolationName       string             `json:"violation_name"`
	ViolationPoints     int32              `json:"violation_points"`
	NotedBy             int64              `json:"noted_by"`
	NotedByName         string             `json:"noted_by_name"`
}

// GET /api/discipline/records?student_id=&class_id=&from=&to=&page= — class
// SELALU diresolusi dari enrollment TAHUN AJARAN AKTIF (sqlc.arg(academic_year_id)),
// BUKAN historis per tanggal pelanggaran (keputusan sendiri, sama pola dgn
// modul lain yang menampilkan "kelas siswa saat ini").
func (q *Queries) ListStudentViolations(ctx context.Context, arg ListStudentViolationsParams) ([]ListStudentViolationsRow, error) {
	rows, err := q.db.Query(ctx, listStudentViolations,
		arg.AcademicYearID,
		arg.SchoolID,
		arg.StudentID,
		arg.ClassID,
		arg.FromDate,
		arg.ToDate,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentViolationsRow
	for rows.Next() {
		var i ListStudentViolationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredOn,
			&i.Note,
			&i.AttendanceSessionID,
			&i.CreatedAt,
			&i.StudentID,
			&i.StudentName,
			&i.StudentNis,
			&i.ClassName,
			&i.ViolationTypeID,
			&i.ViolationName,
			&i.ViolationPoints,
			&i.NotedBy,
			&i.NotedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViolationTypes = `-- name: ListViolationTypes :many
SELECT id, school_id, name, points, category, active FROM violation_types WHERE school_id = $1 ORDER BY name
`

func (q *Queries) ListViolationTypes(ctx context.Context, schoolID int64) ([]ViolationType, error) {
	rows, err := q.db.Query(ctx, listViolationTypes, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ViolationType
	for rows.Next() {
		var i ViolationType
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Name,
			&i.Points,
			&i.Category,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViolationsForStudentYear = `-- name: ListViolationsForStudentYear :many
SELECT sv.id, sv.occurred_on, sv.note, sv.attendance_session_id, sv.created_at,
       vt.id AS violation_type_id, vt.name AS violation_name, vt.points AS violation_points,
       sv.noted_by, u.name AS noted_by_name
FROM student_violations sv
JOIN violation_types vt ON vt.id = sv.violation_type_id
JOIN users u ON u.id = sv.noted_by
WHERE sv.school_id = $1 AND sv.academic_year_id = $2 AND sv.student_id = $3
ORDER BY sv.occurred_on, sv.id
`

type ListViolationsForStudentYearParams struct {
	SchoolID       int64 `json:"school_id"`
	AcademicYearID int64 `json:"academic_year_id"`
	StudentID      int64 `json:"student_id"`
}

type ListViolationsForStudentYearRow struct {
	ID                  int64              `json:"id"`
	OccurredOn          pgtype.Date        `json:"occurred_on"`
	Note                string             `json:"note"`
	AttendanceSessionID pgtype.Int8        `json:"attendance_session_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	ViolationTypeID     int64              `json:"violation_type_id"`
	ViolationName       string             `json:"violation_name"`
	ViolationPoints     int32              `json:"violation_points"`
	NotedBy             int64              `json:"noted_by"`
	NotedByName         string             `json:"noted_by_name"`
}

// Dipakai GET /api/students/{id}/discipline DAN penyusunan snapshot surat
// (Service.recordViolation) — SATU sumber, TIDAK diduplikasi. Total poin
// dihitung MURNI di Go dari hasil query ini (jumlah baris kecil per siswa per
// TA, tidak butuh query SUM terpisah).
func (q *Queries) ListViolationsForStudentYear(ctx context.Context, arg ListViolationsForStudentYearParams) ([]ListViolationsForStudentYearRow, error) {
	rows, err := q.db.Query(ctx, listViolationsForStudentYear, arg.SchoolID, arg.AcademicYearID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListViolationsForStudentYearRow
	for rows.Next() {
		var i ListViolationsForStudentYearRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredOn,
			&i.Note,
			&i.AttendanceSessionID,
			&i.CreatedAt,
			&i.ViolationTypeID,
			&i.ViolationName,
			&i.ViolationPoints,
			&i.NotedBy,
			&i.NotedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarningLetters = `-- name: ListWarningLetters :many
SELECT dwl.id, dwl.school_id, dwl.academic_year_id, dwl.student_id, dwl.level, dwl.number,
       dwl.points_snapshot, dwl.snapshot, dwl.created_by, dwl.created_at,
       s.name AS student_name, s.nis AS student_nis
FROM discipline_warning_letters dwl
JOIN students s ON s.id = dwl.student_id
WHERE dwl.school_id = $1::bigint
  AND ($2::int IS NULL OR dwl.level = $2::int)
ORDER BY dwl.created_at DESC
LIMIT $4::int OFFSET $3::int
`

type ListWarningLettersParams struct {
	SchoolID   int64       `json:"school_id"`
	Level      pgtype.Int4 `json:"level"`
	OffsetRows int32       `json:"offset_rows"`
	LimitRows  int32       `json:"limit_rows"`
}

type ListWarningLettersRow struct {
	ID             int64              `json:"id"`
	SchoolID       int64              `json:"school_id"`
	AcademicYearID int64              `json:"academic_year_id"`
	StudentID      int64              `json:"student_id"`
	Level          int32              `json:"level"`
	Number         string             `json:"number"`
	PointsSnapshot int32              `json:"points_snapshot"`
	Snapshot       []byte             `json:"snapshot"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StudentName    string             `json:"student_name"`
	StudentNis     string             `json:"student_nis"`
}

func (q *Queries) ListWarningLetters(ctx context.Context, arg ListWarningLettersParams) ([]ListWarningLettersRow, error) {
	rows, err := q.db.Query(ctx, listWarningLetters,
		arg.SchoolID,
		arg.Level,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWarningLettersRow
	for rows.Next() {
		var i ListWarningLettersRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.AcademicYearID,
			&i.StudentID,
			&i.Level,
			&i.Number,
			&i.PointsSnapshot,
			&i.Snapshot,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.StudentName,
			&i.StudentNis,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarningLettersForStudentYear = `-- name: ListWarningLettersForStudentYear :many
SELECT id, school_id, academic_year_id, student_id, level, number, points_snapshot, snapshot, created_by, created_at FROM discipline_warning_letters WHERE school_id = $1 AND academic_year_id = $2 AND student_id = $3 ORDER BY level
`

type ListWarningLettersForStudentYearParams struct {
	SchoolID       int64 `json:"school_id"`
	AcademicYearID int64 `json:"academic_year_id"`
	StudentID      int64 `json:"student_id"`
}

func (q *Queries) ListWarningLettersForStudentYear(ctx context.Context, arg ListWarningLettersForStudentYearParams) ([]DisciplineWarningLetter, error) {
	rows, err := q.db.Query(ctx, listWarningLettersForStudentYear, arg.SchoolID, arg.AcademicYearID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DisciplineWarningLetter
	for rows.Next() {
		var i DisciplineWarningLetter
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.AcademicYearID,
			&i.StudentID,
			&i.Level,
			&i.Number,
			&i.PointsSnapshot,
			&i.Snapshot,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextLetterSeq = `-- name: NextLetterSeq :one

INSERT INTO discipline_letter_number_counters (school_id, year, seq) VALUES ($1, $2, 1)
ON CONFLICT (school_id, year) DO UPDATE SET seq = discipline_letter_number_counters.seq + 1
RETURNING seq
`

type NextLetterSeqParams struct {
	SchoolID int64  `json:"school_id"`
	Year     string `json:"year"`
}

// -- nomor surat (counter atomik per sekolah+tahun) --
func (q *Queries) NextLetterSeq(ctx context.Context, arg NextLetterSeqParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextLetterSeq, arg.SchoolID, arg.Year)
	var seq int32
	err := row.Scan(&seq)
	return seq, err
}

const updateViolationType = `-- name: UpdateViolationType :one
UPDATE violation_types SET
    name = COALESCE($1, name),
    points = COALESCE($2, points),
    category = COALESCE($3, category),
    active = COALESCE($4, active)
WHERE id = $5 AND school_id = $6
RETURNING id, school_id, name, points, category, active
`

type UpdateViolationTypeParams struct {
	Name     pgtype.Text `json:"name"`
	Points   pgtype.Int4 `json:"points"`
	Category pgtype.Text `json:"category"`
	Active   pgtype.Bool `json:"active"`
	ID       int64       `json:"id"`
	SchoolID int64       `json:"school_id"`
}

func (q *Queries) UpdateViolationType(ctx context.Context, arg UpdateViolationTypeParams) (ViolationType, error) {
	row := q.db.QueryRow(ctx, updateViolationType,
		arg.Name,
		arg.Points,
		arg.Category,
		arg.Active,
		arg.ID,
		arg.SchoolID,
	)
	var i ViolationType
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.Points,
		&i.Category,
		&i.Active,
	)
	return i, err
}

const upsertSPSettings = `-- name: UpsertSPSettings :one
INSERT INTO discipline_sp_settings (school_id, academic_year_id, sp1, sp2, sp3)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (school_id, academic_year_id) DO UPDATE SET sp1 = $3, sp2 = $4, sp3 = $5
RETURNING school_id, academic_year_id, sp1, sp2, sp3
`

type UpsertSPSettingsParams struct {
	SchoolID       int64 `json:"school_id"`
	AcademicYearID int64 `json:"academic_year_id"`
	Sp1            int32 `json:"sp1"`
	Sp2            int32 `json:"sp2"`
	Sp3            int32 `json:"sp3"`
}

func (q *Queries) UpsertSPSettings(ctx context.Context, arg UpsertSPSettingsParams) (DisciplineSpSetting, error) {
	row := q.db.QueryRow(ctx, upsertSPSettings,
		arg.SchoolID,
		arg.AcademicYearID,
		arg.Sp1,
		arg.Sp2,
		arg.Sp3,
	)
	var i DisciplineSpSetting
	err := row.Scan(
		&i.SchoolID,
		&i.AcademicYearID,
		&i.Sp1,
		&i.Sp2,
		&i.Sp3,
	)
	return i, err
}
