// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package exitpermitdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelExitPermit = `-- name: CancelExitPermit :execrows
UPDATE student_exit_permits SET status = 'canceled'
WHERE id = $1 AND school_id = $2
  AND status IN ('pending_duty_teacher', 'pending_class_teacher', 'pending_bk', 'pending_leadership')
`

type CancelExitPermitParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

func (q *Queries) CancelExitPermit(ctx context.Context, arg CancelExitPermitParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelExitPermit, arg.ID, arg.SchoolID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveExitPermits = `-- name: CountActiveExitPermits :one
SELECT count(*) FROM student_exit_permits
WHERE school_id = $1 AND student_id = $2
  AND status NOT IN ('exited', 'rejected', 'canceled')
`

type CountActiveExitPermitsParams struct {
	SchoolID  int64 `json:"school_id"`
	StudentID int64 `json:"student_id"`
}

// Maks 1 permit AKTIF (pending_*/issued) per siswa (docs tugas).
func (q *Queries) CountActiveExitPermits(ctx context.Context, arg CountActiveExitPermitsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveExitPermits, arg.SchoolID, arg.StudentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExitPermit = `-- name: CreateExitPermit :one
INSERT INTO student_exit_permits (school_id, academic_year_id, student_id, reason, status)
VALUES ($1, $2, $3, $4, 'pending_duty_teacher')
RETURNING id
`

type CreateExitPermitParams struct {
	SchoolID       int64  `json:"school_id"`
	AcademicYearID int64  `json:"academic_year_id"`
	StudentID      int64  `json:"student_id"`
	Reason         string `json:"reason"`
}

func (q *Queries) CreateExitPermit(ctx context.Context, arg CreateExitPermitParams) (int64, error) {
	row := q.db.QueryRow(ctx, createExitPermit,
		arg.SchoolID,
		arg.AcademicYearID,
		arg.StudentID,
		arg.Reason,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const gateScanExitPermit = `-- name: GateScanExitPermit :execrows
UPDATE student_exit_permits SET status = 'exited', exited_by = $3, exited_at = now()
WHERE gate_token = $1 AND school_id = $2 AND status = 'issued'
`

type GateScanExitPermitParams struct {
	GateToken pgtype.Text `json:"gate_token"`
	SchoolID  int64       `json:"school_id"`
	ExitedBy  pgtype.Int8 `json:"exited_by"`
}

func (q *Queries) GateScanExitPermit(ctx context.Context, arg GateScanExitPermitParams) (int64, error) {
	result, err := q.db.Exec(ctx, gateScanExitPermit, arg.GateToken, arg.SchoolID, arg.ExitedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExitPermitByGateToken = `-- name: GetExitPermitByGateToken :one
SELECT
    p.id, p.school_id, p.academic_year_id, p.student_id, p.reason, p.status,
    p.duty_by, p.duty_at, p.class_by, p.class_at, p.bk_by, p.bk_at,
    p.leadership_by, p.leadership_at, p.rejected_by, p.rejected_at, p.reject_comment,
    p.gate_token, p.gate_expires_at, p.exited_by, p.exited_at, p.created_at,
    s.name AS student_name, s.nis AS student_nis, COALESCE(c.name, '') AS class_name,
    du.name AS duty_by_name, cu.name AS class_by_name, bu.name AS bk_by_name,
    lu.name AS leadership_by_name, ru.name AS rejected_by_name, eu.name AS exited_by_name
FROM student_exit_permits p
JOIN students s ON s.id = p.student_id
LEFT JOIN enrollments en ON en.student_id = p.student_id
LEFT JOIN classes c ON c.id = en.class_id AND c.academic_year_id = p.academic_year_id
LEFT JOIN users du ON du.id = p.duty_by
LEFT JOIN users cu ON cu.id = p.class_by
LEFT JOIN users bu ON bu.id = p.bk_by
LEFT JOIN users lu ON lu.id = p.leadership_by
LEFT JOIN users ru ON ru.id = p.rejected_by
LEFT JOIN users eu ON eu.id = p.exited_by
WHERE p.gate_token = $1 AND p.school_id = $2
LIMIT 1
`

type GetExitPermitByGateTokenParams struct {
	GateToken pgtype.Text `json:"gate_token"`
	SchoolID  int64       `json:"school_id"`
}

type GetExitPermitByGateTokenRow struct {
	ID               int64              `json:"id"`
	SchoolID         int64              `json:"school_id"`
	AcademicYearID   int64              `json:"academic_year_id"`
	StudentID        int64              `json:"student_id"`
	Reason           string             `json:"reason"`
	Status           string             `json:"status"`
	DutyBy           pgtype.Int8        `json:"duty_by"`
	DutyAt           pgtype.Timestamptz `json:"duty_at"`
	ClassBy          pgtype.Int8        `json:"class_by"`
	ClassAt          pgtype.Timestamptz `json:"class_at"`
	BkBy             pgtype.Int8        `json:"bk_by"`
	BkAt             pgtype.Timestamptz `json:"bk_at"`
	LeadershipBy     pgtype.Int8        `json:"leadership_by"`
	LeadershipAt     pgtype.Timestamptz `json:"leadership_at"`
	RejectedBy       pgtype.Int8        `json:"rejected_by"`
	RejectedAt       pgtype.Timestamptz `json:"rejected_at"`
	RejectComment    string             `json:"reject_comment"`
	GateToken        pgtype.Text        `json:"gate_token"`
	GateExpiresAt    pgtype.Timestamptz `json:"gate_expires_at"`
	ExitedBy         pgtype.Int8        `json:"exited_by"`
	ExitedAt         pgtype.Timestamptz `json:"exited_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	StudentName      string             `json:"student_name"`
	StudentNis       string             `json:"student_nis"`
	ClassName        string             `json:"class_name"`
	DutyByName       pgtype.Text        `json:"duty_by_name"`
	ClassByName      pgtype.Text        `json:"class_by_name"`
	BkByName         pgtype.Text        `json:"bk_by_name"`
	LeadershipByName pgtype.Text        `json:"leadership_by_name"`
	RejectedByName   pgtype.Text        `json:"rejected_by_name"`
	ExitedByName     pgtype.Text        `json:"exited_by_name"`
}

func (q *Queries) GetExitPermitByGateToken(ctx context.Context, arg GetExitPermitByGateTokenParams) (GetExitPermitByGateTokenRow, error) {
	row := q.db.QueryRow(ctx, getExitPermitByGateToken, arg.GateToken, arg.SchoolID)
	var i GetExitPermitByGateTokenRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.StudentID,
		&i.Reason,
		&i.Status,
		&i.DutyBy,
		&i.DutyAt,
		&i.ClassBy,
		&i.ClassAt,
		&i.BkBy,
		&i.BkAt,
		&i.LeadershipBy,
		&i.LeadershipAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectComment,
		&i.GateToken,
		&i.GateExpiresAt,
		&i.ExitedBy,
		&i.ExitedAt,
		&i.CreatedAt,
		&i.StudentName,
		&i.StudentNis,
		&i.ClassName,
		&i.DutyByName,
		&i.ClassByName,
		&i.BkByName,
		&i.LeadershipByName,
		&i.RejectedByName,
		&i.ExitedByName,
	)
	return i, err
}

const getExitPermitDetail = `-- name: GetExitPermitDetail :one
SELECT
    p.id, p.school_id, p.academic_year_id, p.student_id, p.reason, p.status,
    p.duty_by, p.duty_at, p.class_by, p.class_at, p.bk_by, p.bk_at,
    p.leadership_by, p.leadership_at, p.rejected_by, p.rejected_at, p.reject_comment,
    p.gate_token, p.gate_expires_at, p.exited_by, p.exited_at, p.created_at,
    s.name AS student_name, s.nis AS student_nis, COALESCE(c.name, '') AS class_name,
    du.name AS duty_by_name, cu.name AS class_by_name, bu.name AS bk_by_name,
    lu.name AS leadership_by_name, ru.name AS rejected_by_name, eu.name AS exited_by_name
FROM student_exit_permits p
JOIN students s ON s.id = p.student_id
LEFT JOIN enrollments en ON en.student_id = p.student_id
LEFT JOIN classes c ON c.id = en.class_id AND c.academic_year_id = p.academic_year_id
LEFT JOIN users du ON du.id = p.duty_by
LEFT JOIN users cu ON cu.id = p.class_by
LEFT JOIN users bu ON bu.id = p.bk_by
LEFT JOIN users lu ON lu.id = p.leadership_by
LEFT JOIN users ru ON ru.id = p.rejected_by
LEFT JOIN users eu ON eu.id = p.exited_by
WHERE p.id = $1 AND p.school_id = $2
LIMIT 1
`

type GetExitPermitDetailParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

type GetExitPermitDetailRow struct {
	ID               int64              `json:"id"`
	SchoolID         int64              `json:"school_id"`
	AcademicYearID   int64              `json:"academic_year_id"`
	StudentID        int64              `json:"student_id"`
	Reason           string             `json:"reason"`
	Status           string             `json:"status"`
	DutyBy           pgtype.Int8        `json:"duty_by"`
	DutyAt           pgtype.Timestamptz `json:"duty_at"`
	ClassBy          pgtype.Int8        `json:"class_by"`
	ClassAt          pgtype.Timestamptz `json:"class_at"`
	BkBy             pgtype.Int8        `json:"bk_by"`
	BkAt             pgtype.Timestamptz `json:"bk_at"`
	LeadershipBy     pgtype.Int8        `json:"leadership_by"`
	LeadershipAt     pgtype.Timestamptz `json:"leadership_at"`
	RejectedBy       pgtype.Int8        `json:"rejected_by"`
	RejectedAt       pgtype.Timestamptz `json:"rejected_at"`
	RejectComment    string             `json:"reject_comment"`
	GateToken        pgtype.Text        `json:"gate_token"`
	GateExpiresAt    pgtype.Timestamptz `json:"gate_expires_at"`
	ExitedBy         pgtype.Int8        `json:"exited_by"`
	ExitedAt         pgtype.Timestamptz `json:"exited_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	StudentName      string             `json:"student_name"`
	StudentNis       string             `json:"student_nis"`
	ClassName        string             `json:"class_name"`
	DutyByName       pgtype.Text        `json:"duty_by_name"`
	ClassByName      pgtype.Text        `json:"class_by_name"`
	BkByName         pgtype.Text        `json:"bk_by_name"`
	LeadershipByName pgtype.Text        `json:"leadership_by_name"`
	RejectedByName   pgtype.Text        `json:"rejected_by_name"`
	ExitedByName     pgtype.Text        `json:"exited_by_name"`
}

func (q *Queries) GetExitPermitDetail(ctx context.Context, arg GetExitPermitDetailParams) (GetExitPermitDetailRow, error) {
	row := q.db.QueryRow(ctx, getExitPermitDetail, arg.ID, arg.SchoolID)
	var i GetExitPermitDetailRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.AcademicYearID,
		&i.StudentID,
		&i.Reason,
		&i.Status,
		&i.DutyBy,
		&i.DutyAt,
		&i.ClassBy,
		&i.ClassAt,
		&i.BkBy,
		&i.BkAt,
		&i.LeadershipBy,
		&i.LeadershipAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.RejectComment,
		&i.GateToken,
		&i.GateExpiresAt,
		&i.ExitedBy,
		&i.ExitedAt,
		&i.CreatedAt,
		&i.StudentName,
		&i.StudentNis,
		&i.ClassName,
		&i.DutyByName,
		&i.ClassByName,
		&i.BkByName,
		&i.LeadershipByName,
		&i.RejectedByName,
		&i.ExitedByName,
	)
	return i, err
}

const getStudentClassID = `-- name: GetStudentClassID :one
SELECT e.class_id FROM enrollments e
JOIN classes c ON c.id = e.class_id
WHERE e.student_id = $1 AND c.school_id = $2 AND c.academic_year_id = $3
`

type GetStudentClassIDParams struct {
	StudentID      int64 `json:"student_id"`
	SchoolID       int64 `json:"school_id"`
	AcademicYearID int64 `json:"academic_year_id"`
}

// Fase 15 GAP 3 (reject per tahap) — dipakai memvalidasi approver tahap 2
// (guru pengajar KELAS siswa jam berjalan/berikutnya), query LANGSUNG ke
// tabel students/enrollments/classes (pola sama internal/grading yang query
// langsung tabel siswa lintas modul, TANPA memanggil modul student).
func (q *Queries) GetStudentClassID(ctx context.Context, arg GetStudentClassIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getStudentClassID, arg.StudentID, arg.SchoolID, arg.AcademicYearID)
	var class_id int64
	err := row.Scan(&class_id)
	return class_id, err
}

const getStudentUserID = `-- name: GetStudentUserID :one
SELECT COALESCE(user_id, 0)::bigint AS user_id FROM students WHERE id = $1 AND school_id = $2
`

type GetStudentUserIDParams struct {
	ID       int64 `json:"id"`
	SchoolID int64 `json:"school_id"`
}

// Fase 15 GAP 3 — akun login siswa (bila sudah aktivasi) dipakai notifikasi
// "exitpermit.rejected" ke siswa sendiri (selain ortu).
func (q *Queries) GetStudentUserID(ctx context.Context, arg GetStudentUserIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getStudentUserID, arg.ID, arg.SchoolID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const listExitPermitsActiveToday = `-- name: ListExitPermitsActiveToday :many
SELECT
    p.id, p.school_id, p.academic_year_id, p.student_id, p.reason, p.status,
    p.duty_by, p.duty_at, p.class_by, p.class_at, p.bk_by, p.bk_at,
    p.leadership_by, p.leadership_at, p.rejected_by, p.rejected_at, p.reject_comment,
    p.gate_token, p.gate_expires_at, p.exited_by, p.exited_at, p.created_at,
    s.name AS student_name, s.nis AS student_nis, COALESCE(c.name, '') AS class_name,
    du.name AS duty_by_name, cu.name AS class_by_name, bu.name AS bk_by_name,
    lu.name AS leadership_by_name, ru.name AS rejected_by_name, eu.name AS exited_by_name
FROM student_exit_permits p
JOIN students s ON s.id = p.student_id
LEFT JOIN enrollments en ON en.student_id = p.student_id
LEFT JOIN classes c ON c.id = en.class_id AND c.academic_year_id = p.academic_year_id
LEFT JOIN users du ON du.id = p.duty_by
LEFT JOIN users cu ON cu.id = p.class_by
LEFT JOIN users bu ON bu.id = p.bk_by
LEFT JOIN users lu ON lu.id = p.leadership_by
LEFT JOIN users ru ON ru.id = p.rejected_by
LEFT JOIN users eu ON eu.id = p.exited_by
WHERE p.school_id = $1 AND p.created_at >= $2::timestamptz AND p.created_at < $3::timestamptz
  AND p.status NOT IN ('exited', 'rejected', 'canceled')
ORDER BY p.created_at DESC
`

type ListExitPermitsActiveTodayParams struct {
	SchoolID int64              `json:"school_id"`
	FromAt   pgtype.Timestamptz `json:"from_at"`
	ToAt     pgtype.Timestamptz `json:"to_at"`
}

type ListExitPermitsActiveTodayRow struct {
	ID               int64              `json:"id"`
	SchoolID         int64              `json:"school_id"`
	AcademicYearID   int64              `json:"academic_year_id"`
	StudentID        int64              `json:"student_id"`
	Reason           string             `json:"reason"`
	Status           string             `json:"status"`
	DutyBy           pgtype.Int8        `json:"duty_by"`
	DutyAt           pgtype.Timestamptz `json:"duty_at"`
	ClassBy          pgtype.Int8        `json:"class_by"`
	ClassAt          pgtype.Timestamptz `json:"class_at"`
	BkBy             pgtype.Int8        `json:"bk_by"`
	BkAt             pgtype.Timestamptz `json:"bk_at"`
	LeadershipBy     pgtype.Int8        `json:"leadership_by"`
	LeadershipAt     pgtype.Timestamptz `json:"leadership_at"`
	RejectedBy       pgtype.Int8        `json:"rejected_by"`
	RejectedAt       pgtype.Timestamptz `json:"rejected_at"`
	RejectComment    string             `json:"reject_comment"`
	GateToken        pgtype.Text        `json:"gate_token"`
	GateExpiresAt    pgtype.Timestamptz `json:"gate_expires_at"`
	ExitedBy         pgtype.Int8        `json:"exited_by"`
	ExitedAt         pgtype.Timestamptz `json:"exited_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	StudentName      string             `json:"student_name"`
	StudentNis       string             `json:"student_nis"`
	ClassName        string             `json:"class_name"`
	DutyByName       pgtype.Text        `json:"duty_by_name"`
	ClassByName      pgtype.Text        `json:"class_by_name"`
	BkByName         pgtype.Text        `json:"bk_by_name"`
	LeadershipByName pgtype.Text        `json:"leadership_by_name"`
	RejectedByName   pgtype.Text        `json:"rejected_by_name"`
	ExitedByName     pgtype.Text        `json:"exited_by_name"`
}

// scope=active: permit hari ini (created_at lokal sekolah — rentang UTC
// diteruskan service) yang statusnya BUKAN final.
func (q *Queries) ListExitPermitsActiveToday(ctx context.Context, arg ListExitPermitsActiveTodayParams) ([]ListExitPermitsActiveTodayRow, error) {
	rows, err := q.db.Query(ctx, listExitPermitsActiveToday, arg.SchoolID, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExitPermitsActiveTodayRow
	for rows.Next() {
		var i ListExitPermitsActiveTodayRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.AcademicYearID,
			&i.StudentID,
			&i.Reason,
			&i.Status,
			&i.DutyBy,
			&i.DutyAt,
			&i.ClassBy,
			&i.ClassAt,
			&i.BkBy,
			&i.BkAt,
			&i.LeadershipBy,
			&i.LeadershipAt,
			&i.RejectedBy,
			&i.RejectedAt,
			&i.RejectComment,
			&i.GateToken,
			&i.GateExpiresAt,
			&i.ExitedBy,
			&i.ExitedAt,
			&i.CreatedAt,
			&i.StudentName,
			&i.StudentNis,
			&i.ClassName,
			&i.DutyByName,
			&i.ClassByName,
			&i.BkByName,
			&i.LeadershipByName,
			&i.RejectedByName,
			&i.ExitedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExitPermitsAll = `-- name: ListExitPermitsAll :many
SELECT
    p.id, p.school_id, p.academic_year_id, p.student_id, p.reason, p.status,
    p.duty_by, p.duty_at, p.class_by, p.class_at, p.bk_by, p.bk_at,
    p.leadership_by, p.leadership_at, p.rejected_by, p.rejected_at, p.reject_comment,
    p.gate_token, p.gate_expires_at, p.exited_by, p.exited_at, p.created_at,
    s.name AS student_name, s.nis AS student_nis, COALESCE(c.name, '') AS class_name,
    du.name AS duty_by_name, cu.name AS class_by_name, bu.name AS bk_by_name,
    lu.name AS leadership_by_name, ru.name AS rejected_by_name, eu.name AS exited_by_name
FROM student_exit_permits p
JOIN students s ON s.id = p.student_id
LEFT JOIN enrollments en ON en.student_id = p.student_id
LEFT JOIN classes c ON c.id = en.class_id AND c.academic_year_id = p.academic_year_id
LEFT JOIN users du ON du.id = p.duty_by
LEFT JOIN users cu ON cu.id = p.class_by
LEFT JOIN users bu ON bu.id = p.bk_by
LEFT JOIN users lu ON lu.id = p.leadership_by
LEFT JOIN users ru ON ru.id = p.rejected_by
LEFT JOIN users eu ON eu.id = p.exited_by
WHERE p.school_id = $1
  AND ($2::timestamptz IS NULL OR p.created_at >= $2)
  AND ($3::timestamptz IS NULL OR p.created_at < $3)
ORDER BY p.created_at DESC
`

type ListExitPermitsAllParams struct {
	SchoolID int64              `json:"school_id"`
	FromAt   pgtype.Timestamptz `json:"from_at"`
	ToAt     pgtype.Timestamptz `json:"to_at"`
}

type ListExitPermitsAllRow struct {
	ID               int64              `json:"id"`
	SchoolID         int64              `json:"school_id"`
	AcademicYearID   int64              `json:"academic_year_id"`
	StudentID        int64              `json:"student_id"`
	Reason           string             `json:"reason"`
	Status           string             `json:"status"`
	DutyBy           pgtype.Int8        `json:"duty_by"`
	DutyAt           pgtype.Timestamptz `json:"duty_at"`
	ClassBy          pgtype.Int8        `json:"class_by"`
	ClassAt          pgtype.Timestamptz `json:"class_at"`
	BkBy             pgtype.Int8        `json:"bk_by"`
	BkAt             pgtype.Timestamptz `json:"bk_at"`
	LeadershipBy     pgtype.Int8        `json:"leadership_by"`
	LeadershipAt     pgtype.Timestamptz `json:"leadership_at"`
	RejectedBy       pgtype.Int8        `json:"rejected_by"`
	RejectedAt       pgtype.Timestamptz `json:"rejected_at"`
	RejectComment    string             `json:"reject_comment"`
	GateToken        pgtype.Text        `json:"gate_token"`
	GateExpiresAt    pgtype.Timestamptz `json:"gate_expires_at"`
	ExitedBy         pgtype.Int8        `json:"exited_by"`
	ExitedAt         pgtype.Timestamptz `json:"exited_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	StudentName      string             `json:"student_name"`
	StudentNis       string             `json:"student_nis"`
	ClassName        string             `json:"class_name"`
	DutyByName       pgtype.Text        `json:"duty_by_name"`
	ClassByName      pgtype.Text        `json:"class_by_name"`
	BkByName         pgtype.Text        `json:"bk_by_name"`
	LeadershipByName pgtype.Text        `json:"leadership_by_name"`
	RejectedByName   pgtype.Text        `json:"rejected_by_name"`
	ExitedByName     pgtype.Text        `json:"exited_by_name"`
}

// scope=all: SEMUA status, opsional rentang tanggal (created_at, lokal
// sekolah — rentang UTC diteruskan service; NULL = tanpa filter tanggal).
func (q *Queries) ListExitPermitsAll(ctx context.Context, arg ListExitPermitsAllParams) ([]ListExitPermitsAllRow, error) {
	rows, err := q.db.Query(ctx, listExitPermitsAll, arg.SchoolID, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExitPermitsAllRow
	for rows.Next() {
		var i ListExitPermitsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.AcademicYearID,
			&i.StudentID,
			&i.Reason,
			&i.Status,
			&i.DutyBy,
			&i.DutyAt,
			&i.ClassBy,
			&i.ClassAt,
			&i.BkBy,
			&i.BkAt,
			&i.LeadershipBy,
			&i.LeadershipAt,
			&i.RejectedBy,
			&i.RejectedAt,
			&i.RejectComment,
			&i.GateToken,
			&i.GateExpiresAt,
			&i.ExitedBy,
			&i.ExitedAt,
			&i.CreatedAt,
			&i.StudentName,
			&i.StudentNis,
			&i.ClassName,
			&i.DutyByName,
			&i.ClassByName,
			&i.BkByName,
			&i.LeadershipByName,
			&i.RejectedByName,
			&i.ExitedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExitPermitsExitedOnDate = `-- name: ListExitPermitsExitedOnDate :many
SELECT
    p.id, p.school_id, p.academic_year_id, p.student_id, p.reason, p.status,
    p.duty_by, p.duty_at, p.class_by, p.class_at, p.bk_by, p.bk_at,
    p.leadership_by, p.leadership_at, p.rejected_by, p.rejected_at, p.reject_comment,
    p.gate_token, p.gate_expires_at, p.exited_by, p.exited_at, p.created_at,
    s.name AS student_name, s.nis AS student_nis, COALESCE(c.name, '') AS class_name,
    du.name AS duty_by_name, cu.name AS class_by_name, bu.name AS bk_by_name,
    lu.name AS leadership_by_name, ru.name AS rejected_by_name, eu.name AS exited_by_name
FROM student_exit_permits p
JOIN students s ON s.id = p.student_id
LEFT JOIN enrollments en ON en.student_id = p.student_id
LEFT JOIN classes c ON c.id = en.class_id AND c.academic_year_id = p.academic_year_id
LEFT JOIN users du ON du.id = p.duty_by
LEFT JOIN users cu ON cu.id = p.class_by
LEFT JOIN users bu ON bu.id = p.bk_by
LEFT JOIN users lu ON lu.id = p.leadership_by
LEFT JOIN users ru ON ru.id = p.rejected_by
LEFT JOIN users eu ON eu.id = p.exited_by
WHERE p.school_id = $1 AND p.status = 'exited' AND p.exited_at >= $2::timestamptz AND p.exited_at < $3::timestamptz
ORDER BY p.exited_at DESC
`

type ListExitPermitsExitedOnDateParams struct {
	SchoolID int64              `json:"school_id"`
	FromAt   pgtype.Timestamptz `json:"from_at"`
	ToAt     pgtype.Timestamptz `json:"to_at"`
}

type ListExitPermitsExitedOnDateRow struct {
	ID               int64              `json:"id"`
	SchoolID         int64              `json:"school_id"`
	AcademicYearID   int64              `json:"academic_year_id"`
	StudentID        int64              `json:"student_id"`
	Reason           string             `json:"reason"`
	Status           string             `json:"status"`
	DutyBy           pgtype.Int8        `json:"duty_by"`
	DutyAt           pgtype.Timestamptz `json:"duty_at"`
	ClassBy          pgtype.Int8        `json:"class_by"`
	ClassAt          pgtype.Timestamptz `json:"class_at"`
	BkBy             pgtype.Int8        `json:"bk_by"`
	BkAt             pgtype.Timestamptz `json:"bk_at"`
	LeadershipBy     pgtype.Int8        `json:"leadership_by"`
	LeadershipAt     pgtype.Timestamptz `json:"leadership_at"`
	RejectedBy       pgtype.Int8        `json:"rejected_by"`
	RejectedAt       pgtype.Timestamptz `json:"rejected_at"`
	RejectComment    string             `json:"reject_comment"`
	GateToken        pgtype.Text        `json:"gate_token"`
	GateExpiresAt    pgtype.Timestamptz `json:"gate_expires_at"`
	ExitedBy         pgtype.Int8        `json:"exited_by"`
	ExitedAt         pgtype.Timestamptz `json:"exited_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	StudentName      string             `json:"student_name"`
	StudentNis       string             `json:"student_nis"`
	ClassName        string             `json:"class_name"`
	DutyByName       pgtype.Text        `json:"duty_by_name"`
	ClassByName      pgtype.Text        `json:"class_by_name"`
	BkByName         pgtype.Text        `json:"bk_by_name"`
	LeadershipByName pgtype.Text        `json:"leadership_by_name"`
	RejectedByName   pgtype.Text        `json:"rejected_by_name"`
	ExitedByName     pgtype.Text        `json:"exited_by_name"`
}

// gate-history: permit exited pada rentang tanggal (lokal sekolah, rentang
// UTC diteruskan service), by exited_at.
func (q *Queries) ListExitPermitsExitedOnDate(ctx context.Context, arg ListExitPermitsExitedOnDateParams) ([]ListExitPermitsExitedOnDateRow, error) {
	rows, err := q.db.Query(ctx, listExitPermitsExitedOnDate, arg.SchoolID, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExitPermitsExitedOnDateRow
	for rows.Next() {
		var i ListExitPermitsExitedOnDateRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.AcademicYearID,
			&i.StudentID,
			&i.Reason,
			&i.Status,
			&i.DutyBy,
			&i.DutyAt,
			&i.ClassBy,
			&i.ClassAt,
			&i.BkBy,
			&i.BkAt,
			&i.LeadershipBy,
			&i.LeadershipAt,
			&i.RejectedBy,
			&i.RejectedAt,
			&i.RejectComment,
			&i.GateToken,
			&i.GateExpiresAt,
			&i.ExitedBy,
			&i.ExitedAt,
			&i.CreatedAt,
			&i.StudentName,
			&i.StudentNis,
			&i.ClassName,
			&i.DutyByName,
			&i.ClassByName,
			&i.BkByName,
			&i.LeadershipByName,
			&i.RejectedByName,
			&i.ExitedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExitPermitsForStudents = `-- name: ListExitPermitsForStudents :many
SELECT
    p.id, p.school_id, p.academic_year_id, p.student_id, p.reason, p.status,
    p.duty_by, p.duty_at, p.class_by, p.class_at, p.bk_by, p.bk_at,
    p.leadership_by, p.leadership_at, p.rejected_by, p.rejected_at, p.reject_comment,
    p.gate_token, p.gate_expires_at, p.exited_by, p.exited_at, p.created_at,
    s.name AS student_name, s.nis AS student_nis, COALESCE(c.name, '') AS class_name,
    du.name AS duty_by_name, cu.name AS class_by_name, bu.name AS bk_by_name,
    lu.name AS leadership_by_name, ru.name AS rejected_by_name, eu.name AS exited_by_name
FROM student_exit_permits p
JOIN students s ON s.id = p.student_id
LEFT JOIN enrollments en ON en.student_id = p.student_id
LEFT JOIN classes c ON c.id = en.class_id AND c.academic_year_id = p.academic_year_id
LEFT JOIN users du ON du.id = p.duty_by
LEFT JOIN users cu ON cu.id = p.class_by
LEFT JOIN users bu ON bu.id = p.bk_by
LEFT JOIN users lu ON lu.id = p.leadership_by
LEFT JOIN users ru ON ru.id = p.rejected_by
LEFT JOIN users eu ON eu.id = p.exited_by
WHERE p.school_id = $1 AND p.student_id = ANY($2::bigint[])
ORDER BY p.created_at DESC
`

type ListExitPermitsForStudentsParams struct {
	SchoolID   int64   `json:"school_id"`
	StudentIds []int64 `json:"student_ids"`
}

type ListExitPermitsForStudentsRow struct {
	ID               int64              `json:"id"`
	SchoolID         int64              `json:"school_id"`
	AcademicYearID   int64              `json:"academic_year_id"`
	StudentID        int64              `json:"student_id"`
	Reason           string             `json:"reason"`
	Status           string             `json:"status"`
	DutyBy           pgtype.Int8        `json:"duty_by"`
	DutyAt           pgtype.Timestamptz `json:"duty_at"`
	ClassBy          pgtype.Int8        `json:"class_by"`
	ClassAt          pgtype.Timestamptz `json:"class_at"`
	BkBy             pgtype.Int8        `json:"bk_by"`
	BkAt             pgtype.Timestamptz `json:"bk_at"`
	LeadershipBy     pgtype.Int8        `json:"leadership_by"`
	LeadershipAt     pgtype.Timestamptz `json:"leadership_at"`
	RejectedBy       pgtype.Int8        `json:"rejected_by"`
	RejectedAt       pgtype.Timestamptz `json:"rejected_at"`
	RejectComment    string             `json:"reject_comment"`
	GateToken        pgtype.Text        `json:"gate_token"`
	GateExpiresAt    pgtype.Timestamptz `json:"gate_expires_at"`
	ExitedBy         pgtype.Int8        `json:"exited_by"`
	ExitedAt         pgtype.Timestamptz `json:"exited_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	StudentName      string             `json:"student_name"`
	StudentNis       string             `json:"student_nis"`
	ClassName        string             `json:"class_name"`
	DutyByName       pgtype.Text        `json:"duty_by_name"`
	ClassByName      pgtype.Text        `json:"class_by_name"`
	BkByName         pgtype.Text        `json:"bk_by_name"`
	LeadershipByName pgtype.Text        `json:"leadership_by_name"`
	RejectedByName   pgtype.Text        `json:"rejected_by_name"`
	ExitedByName     pgtype.Text        `json:"exited_by_name"`
}

func (q *Queries) ListExitPermitsForStudents(ctx context.Context, arg ListExitPermitsForStudentsParams) ([]ListExitPermitsForStudentsRow, error) {
	rows, err := q.db.Query(ctx, listExitPermitsForStudents, arg.SchoolID, arg.StudentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExitPermitsForStudentsRow
	for rows.Next() {
		var i ListExitPermitsForStudentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.AcademicYearID,
			&i.StudentID,
			&i.Reason,
			&i.Status,
			&i.DutyBy,
			&i.DutyAt,
			&i.ClassBy,
			&i.ClassAt,
			&i.BkBy,
			&i.BkAt,
			&i.LeadershipBy,
			&i.LeadershipAt,
			&i.RejectedBy,
			&i.RejectedAt,
			&i.RejectComment,
			&i.GateToken,
			&i.GateExpiresAt,
			&i.ExitedBy,
			&i.ExitedAt,
			&i.CreatedAt,
			&i.StudentName,
			&i.StudentNis,
			&i.ClassName,
			&i.DutyByName,
			&i.ClassByName,
			&i.BkByName,
			&i.LeadershipByName,
			&i.RejectedByName,
			&i.ExitedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectExitPermit = `-- name: RejectExitPermit :execrows
UPDATE student_exit_permits SET status = 'rejected', rejected_by = $3, rejected_at = now(), reject_comment = $4
WHERE id = $1 AND school_id = $2 AND status NOT IN ('exited', 'rejected', 'canceled')
`

type RejectExitPermitParams struct {
	ID            int64       `json:"id"`
	SchoolID      int64       `json:"school_id"`
	RejectedBy    pgtype.Int8 `json:"rejected_by"`
	RejectComment string      `json:"reject_comment"`
}

func (q *Queries) RejectExitPermit(ctx context.Context, arg RejectExitPermitParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectExitPermit,
		arg.ID,
		arg.SchoolID,
		arg.RejectedBy,
		arg.RejectComment,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateExitPermitBKStage = `-- name: UpdateExitPermitBKStage :execrows
UPDATE student_exit_permits SET status = 'pending_leadership', bk_by = $3, bk_at = now()
WHERE id = $1 AND school_id = $2 AND status = 'pending_bk'
`

type UpdateExitPermitBKStageParams struct {
	ID       int64       `json:"id"`
	SchoolID int64       `json:"school_id"`
	BkBy     pgtype.Int8 `json:"bk_by"`
}

func (q *Queries) UpdateExitPermitBKStage(ctx context.Context, arg UpdateExitPermitBKStageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateExitPermitBKStage, arg.ID, arg.SchoolID, arg.BkBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateExitPermitClassStage = `-- name: UpdateExitPermitClassStage :execrows
UPDATE student_exit_permits SET status = 'pending_bk', class_by = $3, class_at = now()
WHERE id = $1 AND school_id = $2 AND status = 'pending_class_teacher'
`

type UpdateExitPermitClassStageParams struct {
	ID       int64       `json:"id"`
	SchoolID int64       `json:"school_id"`
	ClassBy  pgtype.Int8 `json:"class_by"`
}

func (q *Queries) UpdateExitPermitClassStage(ctx context.Context, arg UpdateExitPermitClassStageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateExitPermitClassStage, arg.ID, arg.SchoolID, arg.ClassBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateExitPermitDutyStage = `-- name: UpdateExitPermitDutyStage :execrows
UPDATE student_exit_permits SET status = 'pending_class_teacher', duty_by = $3, duty_at = now()
WHERE id = $1 AND school_id = $2 AND status = 'pending_duty_teacher'
`

type UpdateExitPermitDutyStageParams struct {
	ID       int64       `json:"id"`
	SchoolID int64       `json:"school_id"`
	DutyBy   pgtype.Int8 `json:"duty_by"`
}

func (q *Queries) UpdateExitPermitDutyStage(ctx context.Context, arg UpdateExitPermitDutyStageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateExitPermitDutyStage, arg.ID, arg.SchoolID, arg.DutyBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateExitPermitLeadershipStage = `-- name: UpdateExitPermitLeadershipStage :execrows
UPDATE student_exit_permits SET status = 'issued', leadership_by = $3, leadership_at = now(),
    gate_token = $4, gate_expires_at = $5
WHERE id = $1 AND school_id = $2 AND status = 'pending_leadership'
`

type UpdateExitPermitLeadershipStageParams struct {
	ID            int64              `json:"id"`
	SchoolID      int64              `json:"school_id"`
	LeadershipBy  pgtype.Int8        `json:"leadership_by"`
	GateToken     pgtype.Text        `json:"gate_token"`
	GateExpiresAt pgtype.Timestamptz `json:"gate_expires_at"`
}

func (q *Queries) UpdateExitPermitLeadershipStage(ctx context.Context, arg UpdateExitPermitLeadershipStageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateExitPermitLeadershipStage,
		arg.ID,
		arg.SchoolID,
		arg.LeadershipBy,
		arg.GateToken,
		arg.GateExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
