// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package teacherqrdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeTeacherQRToken = `-- name: ConsumeTeacherQRToken :one
UPDATE teacher_qr_tokens SET consumed_at = $3::timestamptz
WHERE token = $1 AND school_id = $2 AND consumed_at IS NULL AND expires_at > $3::timestamptz
RETURNING user_id
`

type ConsumeTeacherQRTokenParams struct {
	Token    string             `json:"token"`
	SchoolID int64              `json:"school_id"`
	Now      pgtype.Timestamptz `json:"now"`
}

// Atomik: hanya baris consumed_at IS NULL & belum kedaluwarsa yang cocok —
// dua pemanggil bersamaan pada token yang sama, HANYA SATU berhasil (row
// lock implisit UPDATE Postgres, tidak butuh SELECT FOR UPDATE terpisah).
func (q *Queries) ConsumeTeacherQRToken(ctx context.Context, arg ConsumeTeacherQRTokenParams) (int64, error) {
	row := q.db.QueryRow(ctx, consumeTeacherQRToken, arg.Token, arg.SchoolID, arg.Now)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const createTeacherQRToken = `-- name: CreateTeacherQRToken :one
INSERT INTO teacher_qr_tokens (school_id, user_id, token, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateTeacherQRTokenParams struct {
	SchoolID  int64              `json:"school_id"`
	UserID    int64              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateTeacherQRToken(ctx context.Context, arg CreateTeacherQRTokenParams) (int64, error) {
	row := q.db.QueryRow(ctx, createTeacherQRToken,
		arg.SchoolID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredTeacherQRTokensForUser = `-- name: DeleteExpiredTeacherQRTokensForUser :exec
DELETE FROM teacher_qr_tokens
WHERE school_id = $1 AND user_id = $2 AND expires_at <= $3::timestamptz
`

type DeleteExpiredTeacherQRTokensForUserParams struct {
	SchoolID int64              `json:"school_id"`
	UserID   int64              `json:"user_id"`
	Now      pgtype.Timestamptz `json:"now"`
}

// Cleanup lazy (docs tugas): token kedaluwarsa milik user ini dihapus setiap
// kali dia generate token baru.
func (q *Queries) DeleteExpiredTeacherQRTokensForUser(ctx context.Context, arg DeleteExpiredTeacherQRTokensForUserParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredTeacherQRTokensForUser, arg.SchoolID, arg.UserID, arg.Now)
	return err
}
